### ISSUE TITLE
how can i override producer properties?

### ISSUE THREAD

**Issue by SpenserZC** [confluentinc/kafka-connect-jdbc#1020]
sach as max.request.size  buffer.memory

**Comment by SpenserZC** [comment]
Ok ,It's connector-distribute.config .

**Comment by eaglesinchina** [comment]
my confluent platform is 5.5 ,but  connector-distribute.config did not work, i solve this as:
echo socket.request.max.bytes=524288000 >> kafka.properties
echo message.max.bytes=419430400 >> kafka.properties
echo producer.max.request.size=524288000 >> connect.properties
echo consumer.max.request.size=524288000 >> connect.properties
