### ISSUE TITLE
Oracle Source Connector Only loads initial/current data and don't create new events for inserts or updates after that

### ISSUE THREAD

**Issue by Psykepro** [confluentinc/kafka-connect-jdbc#1033]
Hello I'm using Kafka Connect version: 6.0.2-ccs and I  have a Kafka Source Connector for Oracle which stops updating loading the initial/current  data without printing any error just stops incrementing and updating here is the configuration of the connector:
```
{
  "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
  "topic.prefix": "",
  "mode": "timestamp+incrementing",
  "numeric.mapping": "best_fit",
  "table.whitelist": "PAN.TRANSACTIONS",
  "tasks.max": "4",
  "connection.url": "jdbc:oracle:thin:@**.**.**.*:1521:*****",
  "connection.user": "*******",
  "connection.password": "*******",
  "key.converter": "io.confluent.connect.avro.AvroConverter",
  "key.converter.schema.registry.url": "https://******.com",
  "value.converter": "io.confluent.connect.avro.AvroConverter",
  "value.converter.schema.registry.url": "https://******.com",
  "transforms": "ValueToKey",
  "transforms.ValueToKey.type": "org.apache.kafka.connect.transforms.ValueToKey",
  "transforms.ValueToKey.fields": "TRN_SERIAL",
  "connection.attempts": "30",
  "errors.log.enable": true,
  "errors.log.include.messages": true,
  "timestamp.column.name": "TRN_TIME",
  "incrementing.column.name": "TRN_SERIAL"
}
``` 

Even tries to check the status of the connector but it gives me just this:
```
{
    "name": "oracle-source-TRANSACTIONS",
    "connector": {
        "state": "RUNNING",
        "worker_id": "kafka-connect.*****:8083"
    },
    "tasks": [
        {
            "id": 0,
            "state": "RUNNING",
            "worker_id": "kafka-connect.*****:8083"
        }
    ],
    "type": "source"
}
```

No errors just stops updating.

Please help me to fix it.

**Comment by Psykepro** [comment]
Actually it is only loading the initial data and it stops after that. And this is only for  `"mode": "timestamp+incrementing"` if I use  `"mode": "incrementing"` the updating is working. I read somewhere that this can be a problem from the timezone and I saw the timezone on the server and of the values is BST so I added `"db.timezone": "Europe/London"` but still no success. Only loads current data and no updates are captured on creating or updating records.

**Comment by Psykepro** [comment]
Btw his is only for  `"mode": "timestamp+incrementing"` if I use  `"mode": "incrementing"` the updating is working. I read here https://github.com/confluentinc/kafka-connect-jdbc/issues/103 that this can be a problem from the time zone and I saw the time zone on the server and of the values is BST so I added `"db.timezone": "Europe/London"` but still no success. Only loads current data and no updates are captured on creating or updating records.

**Comment by mariusneo** [comment]
Please check the following

```
confluent local services connect log
```

You can customize the logging degree via the file

```
$CONFLUENT_HOME/etc/kafka/connect-log4j.properties
```

Check in the logs what is the query being executed in the database.

Describe your scenario with a bit more details.

e.g. : 

i have 10 entries in the table
i start the connector
i see the 10 entries in the kafka output topic

```
kafka-console-consumer \  
  --bootstrap-server localhost:9092 \ 
  --from-beginning true \
  --property print.key=true \
  --property key.separator=' ' \
  --topic your_output_topic \
  --property schema.registry.url=http://localhost:8081
```

i enter an 11th entry.

Pls add more details here regarding the newly entered entry.
Does it have a timestamp greater than what exists already in connect-offset topic ?

```
kafka-console-consumer \
  --bootstrap-server localhost:9092 \     
  --from-beginning true \               
  --property print.key=true \
  --property key.separator=' ' \
  --topic connect-offsets
```

current behavior:
i don't see right away the entry.

Do you see it with some delay (~ 1/2 hours) ?

expected behavior:
i should see right away the entry.

**Comment by Psykepro** [comment]
Yesterday I've created 1 table which creates records each minute and the TIMESTAMP_UPDATED column is UTC. 
And I've started a connector. 

In the table the count of the records are: 310
In the topic the count of messages are: 247
The offset in the offsets topic is:
`rowtime: 2021/04/08 12:29:04.275 Z, key: {"SERIAL": 1168}, value: {"SERIAL": 1168, "TIMESTAMP_UPDATED": 1617884940449}`

Here Is some log:
https://pastebin.com/si7ARUEv

The records in this table have serials from 915 to 1220. 
I don't understand why it stops at 1168 and then slows down.

It loads them until the 247th record and after that starts inserting 1 by 1 per some time new records. But why it doesn't load all of the current records in the table before everything else?

**Comment by Psykepro** [comment]
So, yes - it takes delay. But why is that? how can avoid it?

**Comment by mariusneo** [comment]
```
Apr 8, 2021 @ 15:29:39.311	[2021-04-08 12:29:39,310] DEBUG [oracle-source-BE__CLE_TEST|task-0] Executing prepared statement with start time value = 2021-04-08 12:29:00.449 end time = 2021-04-08 12:29:39.310 and incrementing value = 1168 
```

Do you maybe have `timestamp.delay.interval.ms` also set ?

https://docs.confluent.io/kafka-connect-jdbc/current/source-connector/source_config_options.html


What is the timestamp for the entry with the ID 1169?

**Comment by Psykepro** [comment]
the timestamp of the current at the time offset incremental: 1191, timestamp: 1617886321015:

The timestamp converted to datetime by dividing it by 1000 in Python like that:
`datetime.datetime.fromtimestamp(1617886321015/1000)`
Gives Result:
datetime.datetime(2021, 4, 8, 15, 52, 1, 15000)

Which is the current time here in my timezone EET but in the table the timestamp for that record is:
2021-04-08 12:52:01.015139

**Comment by Psykepro** [comment]
And I don't know why the timstamp is in my timezone while on the server the timezone is BST

**Comment by Psykepro** [comment]
O my god yes the timezone was the problem for the main table now we switched to UTC timestamp_updated column and it is updating

**Comment by Psykepro** [comment]
Closing this issue thank you very much for the help! :)

**Comment by mariusneo** [comment]
```
SELECT DBTIMEZONE FROM dual;
```
see the timezone on the oracle server.

:) 

was just about to suggest to look what values are being written in the db.
