### ISSUE TITLE
Typo in io.confluent.connect.jdbc.source.TimestampIncrementingCriteria.CriteriaValues

### ISSUE THREAD

**Issue by mariusneo** [confluentinc/kafka-connect-jdbc#1035]
https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingCriteria.java#L53,L61

Timetamp -> Timestamp

It survived quite a few releases unchanged :)

**Comment by NathanNam** [comment]
@mariusneo You have an eagle eye! Thanks for creating a PR.
