### ISSUE TITLE
sink connector auto.create table

### ISSUE THREAD

**Issue by yingyingqiqi** [confluentinc/kafka-connect-jdbc#1058]
![image](https://user-images.githubusercontent.com/48437786/117956644-d311a480-b34b-11eb-9471-8b09cd15ba7c.png)

connector config
```
auto.create=true
topics=connect_Sc.maas.t_bank_account_log
table.name.format=${topic}
```
create table error!!

**Comment by ZZa** [comment]
This is definitely not a bug.

You database table simply cannot be named `connect_Sc.maas.t_bank_account_log` as you want it to be named, use some reasonable value for `table.name.format` instead of `${topic}`.

I.e. `table.name.format=T_BANK_ACCOUNT_LOG`
