### ISSUE TITLE
Sink Connector for PostgreSQL fails to delete record if key type is UUID 

### ISSUE THREAD

**Issue by abodalevsky** [confluentinc/kafka-connect-jdbc#1084]
PostgreSQL Sink connector fails to delete record from db when receives tombstone message if key type is UUID. Upsert operations performs well. Also delete works for tables where PK has integer type.

**Error from connector log**
```
[2021-06-10 13:41:32,009] ERROR Error encountered in task psql-sink-0. Executing stage 'TASK_PUT' with class 'org.apache.kafka.connect.sink.SinkTask'. (org.apache.kafka.connect.runtime.errors.LogReporter)
java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Batch entry 0 DELETE FROM "test" WHERE "carrier_account_id" = 'd25f41f4-7379-dead-beef-a98811111111' AND "broker_account_id" = 'd25f41f4-7379-abab-bebe-a98861565001' was aborted: ERROR: operator does not exist: uuid = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 47  Call getNextException to see other errors in the batch.
org.postgresql.util.PSQLException: ERROR: operator does not exist: uuid = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 47
org.postgresql.util.PSQLException: ERROR: operator does not exist: uuid = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 47

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.getAllMessagesException(JdbcSinkTask.java:150)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.unrollAndRetry(JdbcSinkTask.java:138)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:111)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[2021-06-10 13:41:32,009] INFO Closing connection #2 to PostgreSql (io.confluent.connect.jdbc.util.CachedConnectionProvider)
```

 My configuration is following:
 
 **PostgreSQL table**
 ```sql
 CREATE TABLE IF NOT EXISTS public.test(
	broker_account_id uuid NOT NULL,
	carrier_account_id uuid NOT NULL,
	created_on timestamp NOT NULL DEFAULT now(),
	CONSTRAINT c_pkey PRIMARY KEY (broker_account_id, carrier_account_id)
);
 ```
 
 **Sink config**
 ```json
 {
    "name": "psql-sink",
    "config": {
        "name": "psql-sink",
        "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
        "tasks.max": "1",
        "topics": "ksink-test",
        "connection.url": "jdbc:postgresql://postgres:5432/ksink",
        "connection.user": "postgres",
        "connection.password": "pp",
        "dialect.name": "PostgreSqlDatabaseDialect",
        "table.name.format": "test",
        "auto.create": "false",
        "errors.log.enable": true,
        "errors.tolerance": "all",
        "consumer.override.auto.offset.reset": "latest",
        "pk.mode": "record_key",
        "pk.fields": "broker_account_id, carrier_account_id",
        "insert.mode": "upsert",
        "delete.enabled": true,
        "transforms": " timestamp",
        "transforms.timestamp.type": "org.apache.kafka.connect.transforms.TimestampConverter$Value",
        "transforms.timestamp.target.type": "Timestamp",
        "transforms.timestamp.field": "created_on",
        "transforms.timestamp.format": "yyyy-MM-dd'T'HH:mm:ss"
    }
}
 ```
 
 **Schema**
 I use JSON format
 _key_
 ```json
 {
    "subject": "ksink-test-key",
    "version": 2,
    "id": 1,
    "schemaType": "JSON",
    "schema": "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"TestKey\",\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"broker_account_id\":{\"type\":\"string\",\"format\":\"guid\"},\"carrier_account_id\":{\"type\":\"string\",\"format\":\"guid\"}}}"
}
 ```
 _value_
 ```json
{
    "subject": "ksink-test-value",
    "version": 1,
    "id": 2,
    "schemaType": "JSON",
    "schema": "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"TestValue\",\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"created_on\":{\"type\":\"string\",\"format\":\"date-time\"}}}"
}
 ```

Would be appreciated for any solution, workaround or fix, as far as this issue blocks integration of Connectors into our solutions.

**Comment by infiycloud** [comment]
@abodalevsky 
I have the same issue :)
did you found any workaround or solution?

**Comment by abodalevsky** [comment]
Hi @infiycloud ,
not really.
The only workaround that I've found is to implicit conversion varchar to uuid on database.
```sql
CREATE CAST (varchar AS uuid)
  WITH INOUT
  AS IMPLICIT;
```
but it looks too dangerous to use it as generic solution.

**Comment by infiycloud** [comment]
@abodalevsky  
Thanks for details, below workaround worked for me without explicit cast
https://github.com/confluentinc/kafka-connect-jdbc/pull/477#issuecomment-638318570

**Comment by abodalevsky** [comment]
yep, this solves my problem as well. Thanks for pointing it out.

**Comment by monsterbka** [comment]
Hi @abodalevsky,
I have problem with Sink Connector for PostgreSQL, i using same Sink config like you, but when i delete row from source database, it did not generate query to Delete to distance Database like your log
`[2021-10-29 08:45:12,954] WARN [JdbcSinkConnector1234|task-0] Found tombstone record; record ignored silently. (io.confluent.connect.transforms.TombstoneHandler:120)
[2021-10-29 08:45:22,188] INFO [JdbcSinkConnector1234|task-0] WorkerSinkTask{id=JdbcSinkConnector1234-0} Committing offsets asynchronously using sequence number 29: {10.32.79.17.public.FiinAdjustedRatio-0=OffsetAndMetadata{offset=11, leaderEpoch=null, metadata=''}} (org.apache.kafka.connect.runtime.WorkerSinkTask:346)`
Do you have any specials config like "delete.on.null" or any custom config?
Thank you for your help!

**Comment by abodalevsky** [comment]
@monsterbka `Found tombstone record;` means that message has been received by Sink connector. Then it was ignored, probably by misconfiguration. 
Please check `pk.mode` `pk.field` and  double check that `"delete.enabled": true,`
Delete functionality will work if table's PK is used and configured properly.
This [tutorial](https://www.youtube.com/watch?v=ABOJGB5G35k) may help.

**Comment by monsterbka** [comment]
@abodalevsky  thank you for quick reply, i think all config is good

> {
  "name": "JdbcSinkConnector1234",
  "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
  "connection.password": "*********",
  "topics": "*********.public.FiinAdjustedRatio",
  "delete.enabled": "true",
  "connection.user": "*********",
  "connection.url": "jdbc:postgresql://*********",
  "insert.mode": "upsert",
  "key.converter": "io.confluent.connect.avro.AvroConverter",
  "value.converter": "io.confluent.connect.avro.AvroConverter",
  "value.converter.schema.registry.url": "*********",
  "key.converter.schema.registry.url": "*********",
  "value.converter.schemas.enable": "true",
  "key.converter.schemas.enable": "true",
  "auto.evolve": "true",
  "auto.create": "false",
  "pk.fields": "Id",
  "pk.mode": "record_key",
  "transforms": "renameTopic,tombstoneHandlerExample,ExtractField",
  "transforms.renameTopic.type": "org.apache.kafka.connect.transforms.RegexRouter",
  "transforms.renameTopic.regex": "*********.public.FiinAdjustedRatio",
  "transforms.renameTopic.replacement": "FiinAdjustedRatio",
  "transforms.tombstoneHandlerExample.type": "io.confluent.connect.transforms.TombstoneHandler",
  "transforms.tombstoneHandlerExample.behavior": "ignore",
  "time.precision.mode": "connect",
  "transforms.ExtractField.type":"org.apache.kafka.connect.transforms.ExtractField$Key",
  "transforms.ExtractField.field":"Id",
  "behavior.on.null.values": "delete",
  "delete.on.null": "true"
}

I'll follow the tutorial to check it again, thank you!

**Comment by monsterbka** [comment]
@abodalevsky i remove 2 tombstoneHandlerExample config and its work now, thank you!
```
"transforms.tombstoneHandlerExample.type": "io.confluent.connect.transforms.TombstoneHandler",
"transforms.tombstoneHandlerExample.behavior": "ignore",
```

**Comment by maximilianobl** [comment]
> yep, this solves my problem as well. Thanks for pointing it out.

Hello! Do you happen to have an example in a repository? I would like to see the interaction of the source with the sink.
:)
