### ISSUE TITLE
 No tasks will be run because no tables were found

### ISSUE THREAD

**Issue by sultan022** [confluentinc/kafka-connect-jdbc#1085]
i have a standalone kafka runing on windows and a JDBC source connector connected with postgress db which is available on my machine. when i try to run the connector it shows a warning that no tasks will be run because no tables were found. whereas if i connect the same connector with mysql db (which is also locally installed). it is able to pick up the tables and works fine. please note that i am using confluent's jdbc connector with default apache-kafka.

below is the warning i get with postgress

```
 (org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig:372)
[2021-06-16 14:31:53,771] WARN No tasks will be run because no tables were found (io.confluent.connect.jdbc.JdbcSourceConnector:152)
[2021-06-16 14:31:53,773] INFO Created connector postgress-to-topic (org.apache.kafka.connect.cli.ConnectStandalone:109)
```

here are the configurations of my jdbc source worker

```
name=postgress-to-topic
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
connection.url=jdbc:postgresql://localhost:5432/test-kafka
connection.user=postgres
connection.password=postgress
topic.prefix=postgres-
#mode=bulk
mode=incrementing
incrementing.column.name=id
errors.log.enable=true
errors.log.include.messages=true
tasks.max=1
poll.interval.ms =100
schema.pattern=test-kafka
#catalog.pattern=test-kafka
table.whitelist=mytable
#dialect.name=PostgreSqlDatabaseDialect
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
topic.prefix=postgress-
```
these are mysql configs in the same file which are commented for now.

 ```
#mysql configs
    #connection.user=root
    #connection.password=root
    #connection.url=jdbc:mysql://localhost:3306/test-kafka?useSSL=false
    #name=mysql-to-topic
    #topic.prefix=mysql2-
    #schema.pattern=test-kafka
    #table.whitelist=user-data-1
```
below is how my postgress db looks like

```
CREATE TABLE "test-kafka".mytable (
	id serial NOT NULL,
	name varchar NULL,
	age varchar NULL,
	CONSTRAINT mytable_pkey PRIMARY KEY (id)
);
```

![image](https://user-images.githubusercontent.com/16632730/122198146-52961480-ceb2-11eb-93a5-b5ddb8da1630.png)

and below is how my mysql db looks like (which is working fine)

![image](https://user-images.githubusercontent.com/16632730/122198243-6ccff280-ceb2-11eb-9a6f-9bf67e555e32.png)

**Comment by sultan022** [comment]
has nothing to do with connector itself

**Comment by punit-zeta** [comment]
hi @sultan022 what was the error? I am having the same issue.

**Comment by sultan022** [comment]
you have to provide your postgreSQL schema name in the **schema.pattern** property. i was providing db name, which was the problem.

**Comment by sultan022** [comment]
> hi @sultan022 what was the error? I am having the same issue.

you have to provide your postgreSQL schema name in the schema.pattern property. i was providing db name, which was the problem.
