### ISSUE TITLE
cannot get topics.regex working

### ISSUE THREAD

**Issue by lfnt3** [confluentinc/kafka-connect-jdbc#1150]
Hello,

I'm using "confluentinc/kafka-connect-jdbc:10.2.6".

When I set "topics" explicitly then it's working fine, but when I set "topics.regex" instead then no tables are being created in questDB.
What am I missing?

This is working:
{
  "name": "jdbc_sink_ftx",
  "config": {
    "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
    "topics": "trades-FTX-ETH-USD-PERP, trades-FTX-FTM-USD-PERP",
    "table.name.format": "${topic}",
    "connection.url": "jdbc:postgresql://questdb:8812/qdb?useSSL=false",
    "connection.user": "admin",
    "connection.password": "quest",
    "auto.create": "true",
    "insert.mode": "insert",
    "dialect.name": "PostgreSqlDatabaseDialect"
  }
}

This is not working:
{
  "name": "jdbc_sink_ftx_regex",
  "config": {
    "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
    "topics.regex": "FTX",
    "table.name.format": "${topic}",
    "connection.url": "jdbc:postgresql://questdb:8812/qdb?useSSL=false",
    "connection.user": "admin",
    "connection.password": "quest",
    "auto.create": "true",
    "insert.mode": "insert",
    "dialect.name": "PostgreSqlDatabaseDialect"
  }
}

**Comment by OneCricketeer** [comment]
You need to match the whole topic name, not a substring. 

Surely you want something like `trades-FTX-.*`

**Comment by lfnt3** [comment]
Perfect, that's it, thanks a lot!
