### ISSUE TITLE
Does JDBC sink supports sending a message to a different topic after successful write, in a way similar to publishing to a dead letter queue after error?

### ISSUE THREAD

**Issue by limjf85** [confluentinc/kafka-connect-jdbc#1171]

**Comment by limjf85** [comment]
I do not see a way to easily determine if a particular message was successfully consumed by the connector.

**Comment by OneCricketeer** [comment]
The consumer offsets topic is updated when events are consumed, and the group lag should reduce

**Comment by limjf85** [comment]
Thanks
