### ISSUE TITLE
Delete mode fails in JDBC Connector 

### ISSUE THREAD

**Issue by williehao** [confluentinc/kafka-connect-jdbc#1172]
I have tried to use JDBC Source and Sink Connectors with the MSSQL server, it is okay between updating and inserting records, but unfortunately, delete still doesn't work for me, please help me to fix this issue. 

Source connector

```
{"name":"source2","config":{
"key.converter": "org.apache.kafka.connect.json.JsonConverter",
"value.converter": "org.apache.kafka.connect.json.JsonConverter",
"key.converter.schemas.enable": "true",
"value.converter.schemas.enable": "true",
"connector.class":"io.confluent.connect.jdbc.JdbcSourceConnector",
"connection.url": "jdbc:sqlserver://192.168.21.109:1433;databaseName=source_database;",
"connection.password":"~!Qaz2wsx",
"connection.user":"sa",
"table.whitelist":"source_users1",
"incrementing.column.name": "id",
"validate.non.null": "false",
"mode":"timestamp",
"topic.prefix": "",
"transforms":"copyFieldToKey,extractKeyFromStruct",
"transforms.copyFieldToKey.type":"org.apache.kafka.connect.transforms.ValueToKey",
"transforms.copyFieldToKey.fields":"id",
"transforms.extractKeyFromStruct.type":"org.apache.kafka.connect.transforms.ExtractField$Key",
"transforms.extractKeyFromStruct.field":"id"
}}
```

Sink  Connector
```
{"name":"sink2","config":{
"key.converter": "org.apache.kafka.connect.json.JsonConverter",
"value.converter": "org.apache.kafka.connect.json.JsonConverter",
"key.converter.schemas.enable": "true",
"value.converter.schemas.enable": "true",
"connector.class":"io.confluent.connect.jdbc.JdbcSinkConnector",
"connection.url": "jdbc:sqlserver://192.168.21.109:1433;databaseName=target_database",
"connection.password":"~!Qaz2wsx",
"connection.user":"sa",
"topics":"source_users1",
"auto.create":"true",
"auto.evolve":"true",
"insert.mode":"upsert",
"delete.enabled" : "true",
"delete.retention.ms":"100",
"pk.mode": "record_key",
"pk.fields":"id"
}}
```

MSSQL:

```
create  table source_users1
(
    id int identity(1,1) primary key ,
    username nvarchar(16),
    nickname nvarchar(Max)
);
```

**Comment by teimyBr** [comment]
I had same issues with postgres. In my case the user rights was the problem. Whats the error message in the connector. In best case in debug mode

**Comment by rmoff** [comment]
Can you give more detail than " delete still doesn't work for me" ? Do you get an error? 
Also check these resources: 
- https://www.youtube.com/watch?v=ABOJGB5G35k&t=1766s
- https://rmoff.net/2021/03/12/kafka-connect-jdbc-sink-deep-dive-working-with-primary-keys/#_deleting_records_in_the_target_database_with_kafka_connect_jdbc_sink_connector

**Comment by williehao** [comment]
@OneCricketeer  Thanks for your message, in fact, I have tried to change from JDBC Source connector to Debezium, but unfortunately, Deletion still doesn't work(add and update are okay).
my question 
1. Could you do me a favor to give me a simple example between Debezium source Json content and JDBC sink Json content , if this solution is okay for me to fix my issue.

Thanks again.

**Comment by OneCricketeer** [comment]
@williehao I suggest posting your specific Debezium issues to Stackoverflow or Debezium's own issue board if you were not able to get it working

Also you should read this page for how it functions with delete events https://debezium.io/documentation/reference/stable/transformations/event-flattening.html

**Comment by williehao** [comment]
@rmoff I'm very new to Kafka, and I've seen your blog or youtube many times, unfortunately, I still don't know how to delete row data, hopefully, you can help me to fix my issue.
**I. My Apache Kafka test**
1. Connectet-distributed.properties
```
bootstrap.servers=kafka1:9092,kafka2:9092,kafka3:9092
group.id=connect-cluster

#internal.key.converter=org.apache.kafka.connect.json.JsonConverter
#internal.value.converter=org.apache.kafka.connect.json.JsonConverter
#internal.key.converter.schemas.enable=false
#internal.value.converter.schemas.enable=false

key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false

offset.storage.topic=connect-offsets
offset.storage.replication.factor=1
#offset.storage.partitions=12

config.storage.topic=connect-configs
config.storage.replication.factor=1

status.storage.topic=connect-status
status.storage.replication.factor=1
#status.storage.partitions=6

offset.flush.interval.ms=10000
plugin.path=/plugins,/plugins/confluentinc-kafka-connect-jdbc-10.1.7
```
2. JDBC Source connector

```
{"name":"source2","config":{
"key.converter": "org.apache.kafka.connect.json.JsonConverter",
"value.converter": "org.apache.kafka.connect.json.JsonConverter",
"key.converter.schemas.enable": "true",
"value.converter.schemas.enable": "true",
"connector.class":"io.confluent.connect.jdbc.JdbcSourceConnector",
"connection.url": "jdbc:sqlserver://192.168.21.109:1433;databaseName=source_database;",
"connection.password":"~!Qaz2wsx",
"connection.user":"sa",
"table.whitelist":"source_users1",
"incrementing.column.name": "id",
"validate.non.null": "false",
"mode":"timestamp",
"topic.prefix": "",
"transforms":"copyFieldToKey,extractKeyFromStruct",
"transforms.copyFieldToKey.type":"org.apache.kafka.connect.transforms.ValueToKey",
"transforms.copyFieldToKey.fields":"id",
"transforms.extractKeyFromStruct.type":"org.apache.kafka.connect.transforms.ExtractField$Key",
"transforms.extractKeyFromStruct.field":"id"
}}
```

4. JDBC Sink  Connector 
```
{"name":"sink2","config":{
"key.converter": "org.apache.kafka.connect.json.JsonConverter",
"value.converter": "org.apache.kafka.connect.json.JsonConverter",
"key.converter.schemas.enable": "true",
"value.converter.schemas.enable": "true",
"connector.class":"io.confluent.connect.jdbc.JdbcSinkConnector",
"connection.url": "jdbc:sqlserver://192.168.21.109:1433;databaseName=target_database",
"connection.password":"~!Qaz2wsx",
"connection.user":"sa",
"topics":"source_users1",
"auto.create":"true",
"auto.evolve":"true",
"insert.mode":"upsert",
"delete.enabled" : "true",
"delete.retention.ms":"100",
"pk.mode": "record_key",
"pk.fields":"id"
}}
```

5. MSSQL Server DB table:(create 2 tables(source and target) at the same MSSQL Server )

```
create  table source_users1
(
    id int identity(1,1) primary key ,
    username nvarchar(16),
    nickname nvarchar(Max)
);
```
PS: 
1. I didn't see any error message when I deleted or update or inserted
2. I've also used the Confluent Kafka with docker-compose.yml to try the JDBC source and sink connector but it still has the same question.(Deletion isn't worked but Add and Update are okay)

**Comment by OneCricketeer** [comment]
Hello again @williehao

What exactly has been unclear about the information provided?

1. The exact timestamp to a video for handling null values **from the sink connector** has been linked, as well as mentioned in a blog
2. We've stated the _source JDBC connector_  is **not** able to put those tombstone messages into the topic for the JDBC sink to read. You can verify this yourself using a plain console consumer, reading messages from the source connector without any sink connector at all

So, your issue here cannot be solved with the JDBC source. You've still not shown the Debezium config, connector configuration, but that then wouldn't be an issue with the github repo here 

And using Docker doesn't change the answer; it's still the same _Apache_ Kafka
