### ISSUE TITLE
How to invoke a oracle stored procedure or a function using JDBC source connector

### ISSUE THREAD

**Issue by kafkaconnectBeginner** [confluentinc/kafka-connect-jdbc#1238]
We can't use a CDC connector as we don't have Oracle DB LogMinor access. So we have developed a Oracle PL/SQL based CDC framework that gives us updates in a similar way. 
Since this is a Stored procedures and functions based implementation so we are trying to see a possibility of invoking Oracle stored procedures/functions from JDBC connector. There was a suggestion in another issue [Issue-194](https://github.com/confluentinc/kafka-connect-jdbc/issues/194) to use private temporary tables and multiple sql statements (semi-colon separated), So I created below query and passed with the 'query' parameter in the connector JSON, but that is failing with the error "ORA-00933: SQL command not properly ended".

CREATE PRIVATE TEMPORARY TABLE ORA$PTT_ORDERS (ORDER_ID NUMBER, STATUS VARCHAR(50)) ON COMMIT DROP DEFINITION; INSERT INTO ORA$PTT_ORDERS (ORDER_ID, STATUS) SELECT X.* FROM XMLTABLE('/ROWSET/ROW' PASSING XMLTYPE(AT_TEST_FUNC()) COLUMNS ORDER_ID NUMBER, STATUS VARCHAR(50)) X; SELECT * FROM (SELECT ORDER_ID, STATUS FROM ORA$PTT_ORDERS) A

Please can someone help in figuring out whether it is possible to invoke a stored proc/function from JDBC connector.

Thanks

**Comment by kafkaconnectBeginner** [comment]
Now able to access pl/sql function. Closing the issue. Thanks

**Comment by shosing** [comment]
@kafkaconnectBeginner what steps did you take ?
