### ISSUE TITLE
Problem with sql server using JDBC Connector using Decimal for incrementingColumn

### ISSUE THREAD

**Issue by wegged** [confluentinc/kafka-connect-jdbc#125]
Hi I am trying to use Kafka Connect with some vendor data in SQL Server.  The vendor is using DECIMAL(10,0) for their primary key.  this is resulting in the following exception.  Please advise.

We are using jtds 1.3.1 jdbc driver.

Thanks,
Eli

> 
> [2016-09-08 16:02:30,221] ERROR Task sql12Alloc-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
> org.apache.kafka.connect.errors.ConnectException: Invalid type for incrementing column: BYTES
>         at io.confluent.connect.jdbc.TimestampIncrementingTableQuerier.extractRecord(TimestampIncrementingTableQuerier.java:191)
>         at io.confluent.connect.jdbc.JdbcSourceTask.poll(JdbcSourceTask.java:217)
>         at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:155)
>         at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
>         at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
> [2016-09-08 16:02:30,236] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:143)

**Comment by shikhar** [comment]
We should be able to fix this and #31 by coercing the `Decimal` logical type in `TimestampIncrementingTableQuerier.extractRecord()` to `long`.

We could make sure that the value is less than `Long.MAX_VALUE` before the downcast from `BigDecimal` and otherwise throw an error.

**Comment by Asim23** [comment]
@shikhar I have to import data from kafka to my local sql server (on my local machine). For kafka i am using landoop docker image. i have configured jdbc connector on http://127.0.0.1:3030/kafka-connect-ui
here's the configuration detail:
"connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
  "topics": "sqltest",
  "tasks.max": "1",
  "name": "SQLServerSinkConnector",
  "connection.url": "jdbc:sqlserver://mysqlserver:1433;database=mydb;user=sa;password=****",
  "table.whitelist": "SqlTest2"

But its not working. I have checked landoop log here's the error detail
ERROR Task SQLServerSinkConnector-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask:482)
org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: No suitable driver found for jdbc:sqlserver://192.168.99.1:1433;database=PaperSource;user=sa;password=123
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getValidConnection(CachedConnectionProvider.java:59)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:52)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:66)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:464)
