### ISSUE TITLE
is it possible to include the key from a Kafka message in the sink record?

### ISSUE THREAD

**Issue by cyberjar09** [confluentinc/kafka-connect-jdbc#1278]
hi im trying to find either native support or support via transformers to write the kafka record key in the sink payload

I see that s3 has support for this ([link](https://docs.confluent.io/kafka-connectors/s3-sink/current/overview.html#writing-record-keys-and-headers)) but I don't see any such option in the JDBC sink connector. 

appreciate the guidance, im new to this ecosystem so pls excuse the question if im overlooking something obvious =)

**Comment by OneCricketeer** [comment]
The primary key of the database should map to the key of the kafka record.

**Comment by cyberjar09** [comment]
hey thanks for the response. What im trying to achieve tho is to include the PK of the db row in the record value as well. It only appears in the key and the key is not written to the JDBC sink

**Comment by OneCricketeer** [comment]
> include the PK of the db row in the record value as well.

Use a transform.

> the key is not written to the JDBC sink

Are you sure about that? It's the primary key when you use `'pk.mode' = 'record_key'`. Refer https://rmoff.net/2021/03/12/kafka-connect-jdbc-sink-deep-dive-working-with-primary-keys/

**Comment by OneCricketeer** [comment]
Then change it? You asked me if it was possible to put the key in the database, and it is.

**Comment by cyberjar09** [comment]
hey @OneCricketeer thanks for the response. My requirements unfortunately need me to keep track of the kafka offset etc so using `kafka` is what I must do. No matter, with the help of Robin Moffatt I was directed to 
- https://github.com/jzaralim/KeyToValueTransform
- https://www.mail-archive.com/users@kafka.apache.org/msg37254.html

so this should solve my problem
