### ISSUE TITLE
Issue with kafka connect-api version

### ISSUE THREAD

**Issue by gowtham1984** [confluentinc/kafka-connect-jdbc#157]
Looks like kafka connect-api version seems to be incorrect and is taking the project version. Had to update the connect-api version to 0.10.0.1 in pom.xml and then it was successful. Probably something to fix in the source

**Comment by ewencp** [comment]
@gowtham1984 Not sure what you mean, the pom file references the `kafka.version` which seems to be set correctly from what I can tell: https://github.com/confluentinc/kafka-connect-jdbc/blob/master/pom.xml#L78 Which branch are you seeing the problem on? Or maybe this is a case of https://github.com/confluentinc/kafka-connect-jdbc/wiki/FAQ#when-i-try-to-compile-i-get-an-error-about-a-missing-snapshot-dependency ?

**Comment by gowtham1984** [comment]
@ewencp yeah looks like the issue is related to the missing snapshot dependency (link that you posted). Thanks
