### ISSUE TITLE
Unsigned numeric fields not correctly supported

### ISSUE THREAD

**Issue by andybryant** [confluentinc/kafka-connect-jdbc#165]
I am reading from a MariaDB database with an unsigned INT field to store IP address.
`DataConverter.java` ignores whether the field is signed or not when generating the Kafka Connect Schema, always converting `Types.INTEGER` into `Schema.OPTIONAL_INT32_SCHEMA` or `Schema.INT32_SCHEMA`.

When reading from the database this results in a `resultSet.getInt` call which will fail when the value is greater than `Integer.MAX_VALUE`. Here's an example of this happening...

```
[2016-11-11 15:58:49,574] WARN Ignoring record due to SQL error: (io.confluent.connect.jdbc.JdbcSourceTask:73)
java.sql.SQLException: Out of range value for column 'customers_ip_number' : value 3707109316 is not in class java.lang.Integer range
	at org.mariadb.jdbc.internal.queryresults.resultset.MariaSelectResultSet.rangeCheck(MariaSelectResultSet.java:3005)
	at org.mariadb.jdbc.internal.queryresults.resultset.MariaSelectResultSet.getInt(MariaSelectResultSet.java:1016)
	at org.mariadb.jdbc.internal.queryresults.resultset.MariaSelectResultSet.getInt(MariaSelectResultSet.java:956)
	at io.confluent.connect.jdbc.DataConverter.convertFieldValue(DataConverter.java:299)
	at io.confluent.connect.jdbc.DataConverter.convertRecord(DataConverter.java:68)
	at io.confluent.connect.jdbc.TimestampIncrementingTableQuerier.extractRecord(TimestampIncrementingTableQuerier.java:179)
	at io.confluent.connect.jdbc.JdbcSourceTask.poll(JdbcSourceTask.java:217)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:155)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The Kafka Connect Schema spec should either support unsigned types like `SchemaBuilder.int32().optional().unsigned()` or kafka-connect-jdbc could check the signed flag when reading the DB schema and conservatively assign a schema that will always be able to read the data if unsigned.

The first approach seems cleaner, but would involve a change on the Kafka Connect API as well as all connectors.

Note TINYINT is also currently not handled correctly as according to this page, these are always unsigned and so should be read as a short not a byte.
https://www.cis.upenn.edu/~bcpierce/courses/629/jdkdocs/guide/jdbc/getstart/mapping.doc.htm

Finally unsigned BIGINT values should be read in as BigIntegers not Longs.

If the second approach is preferred, I can make a PR.

**Comment by andybryant** [comment]
Added issue to KafkaConnect to support knowledge of numeric sign to schemas. See https://issues.apache.org/jira/browse/KAFKA-4404

**Comment by vamossagar12** [comment]
@andybryant We've experience a similar issue. I had sent a PR regarding this for tinyint.

https://github.com/confluentinc/kafka-connect-jdbc/pull/152

There are a couple more PRs on Kafka-connect and Schema-Registry level. That's how I ran it...

**Comment by andybryant** [comment]
Thanks for the heads up @vamossagar12 - the way I was thinking of it was to check the resultSet metadata if the type was unsigned or signed then set the schema accordingly (int8 or int16) and then update the parsing in the same way (similar to how you did it).
The Kafka Connect API should document that their numeric types are always signed to make it clear that connector developers use them consistently.

**Comment by vamossagar12** [comment]
Well looks like a new version of Confluent got released today..

https://www.confluent.io/blog/announcing-confluent-3-1-with-apache-kafka-0-10-1-0/

Maybe @shikhar can confirm if these changes are baked in there.. We have been discussing on the other PR wherein he mentioned he had some other ideas of fixing this issue.

**Comment by shikhar** [comment]
@andybryant the idea to use a wider integer type when `!metadata.isSigned(col)` seems reasonable to me. Would you like to submit a PR for that?

**Comment by shikhar** [comment]
To summarize two possible solutions which seem reasonable to me without any changes to the Connect data API:

1. As you suggested, check `metadata.isSigned(col)` and use that for mapping to the next wider type that is available if unsigned.

| SQL      | signed | unsigned |
|----------|--------|----------|
| TINYINT  | INT8   | INT16    |
| SMALLINT | INT16  | INT32    |
| INTEGER  | INT32  | INT64    |
| BIGINT   | INT64  | Decimal  |

One drawback is that this may cause a schema change for existing users.

2. Don't update the schema inferred by the connector. However, at the time of converting field values avoid exception if it is unsigned by using the accessor for the wider type.

| SQL      | signed | unsigned |
|----------|--------|----------|
| TINYINT  | resultSet.getByte(col)   | (byte) resultSet.getShort(col)    |
| SMALLINT | resultSet.getShort(col) | (short) resultSet.getInt(col)    |
| INTEGER  | resultSet.getInt(col)  | (int) resultSet.getLong(col)  |
| BIGINT   | resultSet.getLong(col)  | resultSet.getBigDecimal(col).longValue()  |

This has the benefit of avoiding a schema change, and is at least an improvement over the current situation of getting exceptions from the MySQL JDBC driver. However, no information about the type needing to be read as unsigned is conveyed in the record and that needs to be handled separately with explicit knowledge of which fields should be treated as unsigned (whether by consumers at read time, with a separate stream processing step, or single-message-transforms which is a new feature we are considering).

cc @ewencp in case you have any thoughts. I think 1 is the most straightforward but we may want to put it behind a config option as Ewen mentioned in https://github.com/confluentinc/kafka-connect-jdbc/issues/98#issuecomment-231431470. (Is type widening is a backwards-compatible change? Not sure.)

**Comment by andybryant** [comment]
@shikhar - thanks for the great summary. I'll work on a PR for option 1 to see what how it pans out.

**Comment by andybryant** [comment]
PR here: https://github.com/confluentinc/kafka-connect-jdbc/pull/169
