### ISSUE TITLE
Integration with Connect sinks

### ISSUE THREAD

**Issue by Arttii** [confluentinc/kafka-connect-jdbc#17]
Hi,

Sorry for posting this here, but not sure where to ask questions about this. 
Im trying to get the connector to work with the 0.9 Kafka but with the current Confluent registry and serializers.
I can get new rows pushed to Kafka and can see them using a normal console consumer, but say if I try the Kafka connect console sink or file sink I get

```
java.lang.StackOverflowError
        at io.confluent.connect.avro.AvroData.toConnectSchema
```

I would really appreciate the help, this is basically the only thing that currently supports our usecase.

Artyom

**Comment by ewencp** [comment]
I think this was resolved before the official 0.9 release and had to do with an issue with converting values that was incorrectly recursing in a case it shouldn't have been.

I'm going to close this for now. @Arttii, if this is still an issue, please reopen and let us know. Thanks!
