### ISSUE TITLE
Unending memory rise then Out of Memory on JDBC sink

### ISSUE THREAD

**Issue by GLStephen** [confluentinc/kafka-connect-jdbc#170]
We have a JDBC sink consuming 5 topics with smallish messages (5-10, 20 character strings) with a batch size of 100. Rate of messages is 10-15 per second. They are consuming into a remote MySQL DB. The process has a heap size of 4gigs. The memory for the sink grows until it uses all memory available on the machine. Then starts throwing memory errors and other errors.

Is this a bug in the sink or is there config to handle this? I don't need real-time sinking. The sink can lag a bit. The DB is very powerful and can handle large batches.

**Comment by shikhar** [comment]
We are not closing the `PreparedStatement` that is used for writing to the target database.  That's a nasty bug, thank you for reporting. I'll create a PR.
