### ISSUE TITLE
If this is open source, why this page says it is not?

### ISSUE THREAD

**Issue by sunshineo** [confluentinc/kafka-connect-jdbc#182]
http://docs.confluent.io/3.1.1/cp-docker-images/docs/intro.html
It list this under Enterprise

**Comment by rnpridgeon** [comment]
See the note directly below the table:

> Although the Kafka Connect image primarily contains an open source project, it is labeled as “Enterprise” because it contains the Confluent Control Center package. This package is required because the interceptors are needed when running Connect with Control Center."

The table in Confluent's documentation is  representative of how things are packaged not necessarily how products are licensed.
