### ISSUE TITLE
Issue when using MSSQL as sink

### ISSUE THREAD

**Issue by sebastianvoss** [confluentinc/kafka-connect-jdbc#186]
I'm using MSSQL as a sink with kafka-connect-jdbc (`CLASSPATH=sqljdbc42.jar`). When producing messages with:

    kafka-avro-console-producer  --broker-list localhost:9092 --topic orders -property value.schema='{"type":"record","name":"myrecord2","fields":[{"name":"id","type":"int"},{"name":"value","type":"int","default":0}]}'

    {"id":1,"value":10}

The table is populated, but the columns are swapped:

    id = 10
    value = 1

This only happens when upsert mode is enabled:

    insert.mode=upsert
    pk.mode=record_value
    pk.fields=id

**Comment by shikhar** [comment]
This was reported in https://github.com/confluentinc/kafka-connect-jdbc/issues/179 and a fix is included in the upcoming bugfix release (3.1.2 -- out very soon)
