### ISSUE TITLE
JDBC sink to support Hive JDBC Driver

### ISSUE THREAD

**Issue by bharatviswa504** [confluentinc/kafka-connect-jdbc#193]
As currently Hive JDBC is not supported for auto creation of tables.
This issue is to create a pull request for support for Hive JDBC driver.

**Comment by gwenshap** [comment]
Did you look at the HDFS connector? It has Hive support and can create and update Hive tables. It may be a better fit than trying to do this via JDBC.

**Comment by bharatviswa504** [comment]
@gwenshap Ya I have looked in that and using it. But with HDFS Connector external tables are created with avro/paruqet formatted and it also does not support time, date and other data types. If I want my connector to create managed tables, then I think adding this support would it make sense?
