### ISSUE TITLE
Possibility to execute a stored procedure in source connector and sink connector

### ISSUE THREAD

**Issue by c3f8** [confluentinc/kafka-connect-jdbc#194]
Is there any possibility of executing a SQL Server stored procedure to obtain the values for kafka?
And calling a stored procedure for sink connector?

Best regards.

**Comment by SanketMore** [comment]
Is there any possibility of executing a SQL Server stored procedure to obtain the values for kafka?
And calling a stored procedure for sink connector?

Best regards.

**Comment by HM-RAJESH** [comment]
There is way that we can call SP though property of source connector; query: "<call sp here by creating temp table and insert data>"

**Comment by Mayankdataxproduct** [comment]
How did you implement it? Can you please explain the steps? If you can attach the code snippets if possible, that would be helpful.

**Comment by sanketfajage** [comment]
Can you please add the implementation steps? If you can add code snippets, that would be helpful.

**Comment by HM-RAJESH** [comment]
"query": "CREATE TABLE #TempTable(Column list); INSERT INTO #TempTable EXEC My_SP; SELECT * FROM #TempTable",

**Comment by sangvk** [comment]
I want read the input data from my kafka topic and execute store procedure using sink connector, is that possible?

**Comment by dmarupov** [comment]
> I want read the input data from my kafka topic and execute store procedure using sink connector, is that possible?

I am also interested in this.

**Comment by HM-RAJESH** [comment]
I think we need write custom connector. Basically source is for read, sink is for write.

**Comment by anuragtelang** [comment]
> I think we need to write custom connector. Basically source is for read, sink is for write.

I have tried invoking oracle function as per your above suggestion but kafka connect JDBC connector is throwing error "ORA-00933: SQL command not properly ended". 
Can you please elaborate the implementation steps in more details.

**Comment by mails2irfan** [comment]
Hi, I am new to kafka. Can anyone please share examples how to connect kafka with oracle to execute stored procedure. 

Thank You.,
