### ISSUE TITLE
Possibility to disable java.sql.ResultSetMetaData.isNullable to define schema constraints in source connector

### ISSUE THREAD

**Issue by EduardHL** [confluentinc/kafka-connect-jdbc#197]
Some JDBC drivers, such as the one for Teradata, don't always provide correct values for `java.sql.ResultSetMetaData.isNullable` ([see here](https://community.teradata.com/t5/Connectivity/Teradata-JDBC-Driver-returns-the-wrong-schema-column-nullability/td-p/40628))
This is particularly problematic when the value returned is `columnNoNulls` for a column that can actually be null, as the source connector won't allow nulls ([see here](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/source/DataConverter.java#L87)); at runtime we will get `org.apache.kafka.connect.errors.DataException: Invalid value: null used for required field`.
Since `java.sql.ResultSetMetaData.isNullable` is not trustable for all JDBC drivers, would it be possible to add a configuration property `enforce.jdbc.metadata.nulls` (by default set to true) that would allow to ignore returned values by the driver (to do as if they were always `columnNullableUnknown`). I can gladly make a PR for this or a better approach to make kafka-connect-jdbc usable for Teradata.

**Comment by bruce-szalwinski** [comment]
I think what you are looking for is validate.non.null, https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java#L152.

**Comment by bruce-szalwinski** [comment]
Ah, yes.  My bad.  I had to use `validate.non.null` on a Postgres db because it didn't understand parts of ResultSetMetadata either :(.  But I see now that isn't the problem you are trying to solve.

**Comment by gwenshap** [comment]
A bit late,  but this sounds like a reasonable accommodation. Let us know if you have a PR for this.

**Comment by wicknicks** [comment]
this has been addressed in `5.0.0` here: [GenericDatabaseDialect.java#L661](https://github.com/confluentinc/kafka-connect-jdbc/blob/v5.0.0/src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java#L650). Feel free to reopen this ticket if this still insufficient to work with Teradata. Thanks!
