### ISSUE TITLE
Add in retry logic for Jdbc source connector if connection cannot be acquired 

### ISSUE THREAD

**Issue by sjdurfey** [confluentinc/kafka-connect-jdbc#198]
The [CachedConnectionProvider#getValidConnection](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/util/CachedConnectionProvider.java#L49-L62) doesn't have retry logic to attempt to get a new connection if the first attempt fails. So, as soon as it fails the task is killed and it needs to be restarted to start again. Killing the task will eventually need to happen, but ideally there is more than one attempt.

**Comment by mkwhitacre** [comment]
So to better articulate the problem @sjdurfey logged this issue for...

We have a situation where on a scheduled basis the database is restarted.  (please don't just we aren't in charge of it).  This causes problems for us in that those restarting the database neglect/forget the Kafka Connect instances requiring us to have to restart the Kafka Connect instances each time as well.  

Therefore the goal would be that Kafka Connect would be resilient to polling data during those temporary downtimes.  For this reason the PR attached to this was written to try and be resilient to this situation.  The behavior should now be:

* On startup/connect if the connection isn't valid then it will fail and stop the connector from running
* JdbcSinkConnector will behave the same way as it currently does (b/c we don't need it right now)
* JdbcSourceConnector + TableMonitorThread will not kill the connector instance if it encounters a connection problem but instead keep retrying at the expected intervals with lots of log messages.  

The last bullet point should therefore help the JdbcSourceConnector tasks recover when we've validated the connection properties are good (b/c done on startup) but when the DB instance is down for an unknown period.

Thoughts?

**Comment by makeittotop** [comment]
Hi, has this been already merged into master?

**Comment by rhauch** [comment]
Yes, it was merged.
