### ISSUE TITLE
table creation fails under oracle with ORA-02329

### ISSUE THREAD

**Issue by jorgheymans** [confluentinc/kafka-connect-jdbc#226]
Hi,

Using jdbcsink with autocreate the following statement is generated for my case

```sql
CREATE TABLE "test" (
"__connect_topic" CLOB NOT NULL,
"__connect_partition" NUMBER(10,0) NOT NULL,
"__connect_offset" NUMBER(19,0) NOT NULL,
"PAYLOAD" BLOB NOT NULL,
PRIMARY KEY("__connect_topic","__connect_partition","__connect_offset"))
```
This results in ORA-02329: column of datatype LOB cannot be unique or a primary key

It seems that topic names can be max 249 characters, so an obvious fix would be "VARCHAR(249 CHAR)" to allow for 249 **characters** . If topic names cannot contain multibyte characters then VARCHAR(249) is sufficient.

**Comment by asthraa** [comment]
@jorgheymans : I have this same issue with JDBC Sink. Please refer to issue #842
