### ISSUE TITLE
Inserting a current timestamp value specifying when a Kafka message was stored by the Cassandra sink

### ISSUE THREAD

**Issue by abhinavsinha1991** [confluentinc/kafka-connect-jdbc#255]
HeIlo,

I have managed to setup the Open Source Confluent Platform to work with Cassandra using the Cassandra Sink and it worked to send some sample data from a SQL source to Cassandra. However, I would like to send data that contains a timestamp with the current timestamp value(i.e when the Kafka message hit the Cassandra sink). 
This would ideally tell when a particular record was inserted/upserted in Cassandra.

 Is it possible to send timestamp data like that and if yes what should be modified? The KCQL or the Avro message?

**Comment by ewencp** [comment]
I don't think there's a setting to do this in the Cassandra connector, but for details on that connector you're best off asking [on the author's repo](https://github.com/datamountaineer/stream-reactor/tree/master/kafka-connect-cassandra).

There is a [single message transform](http://kafka.apache.org/documentation.html#connect_transforms) for [inserting fields based on message metadata](http://kafka.apache.org/documentation.html#org.apache.kafka.connect.transforms.InsertField) which will insert a field containing the timestamp from the record. This isn't quite what you're looking for, but you could use that as a template for building a transformation that adds current wall clock time to the message just before it is passed to the Cassandra connector.

**Comment by dollschasingmen** [comment]
@ewencp it looks like SMT will [update with](https://github.com/apache/kafka/blob/763ea5aad191b09ed3deefaa12ce7b9925ebe7dc/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/InsertField.java#L151-L153) `record.timestamp`  ... wouldn't that be basically the wall clock time of when the connect consumed the message?

**Comment by ewencp** [comment]
@dollschasingmen No, `record.timestamp` in a sink connector would be whatever timestamp in the Kafka record. This would be either whatever the application that produced it set it to, or the time it was written to Kafka if using log append time.

**Comment by dollschasingmen** [comment]
fwiw I put something together here: https://github.com/dollschasingmen/confluent-extensions

might be a good place for others to start.
