### ISSUE TITLE
One topic sink to multiple tables in kafka connect

### ISSUE THREAD

**Issue by ntwobike** [confluentinc/kafka-connect-jdbc#277]
This question is basically relates to the kakfa connect, my source and sink both are mysql dbs(i use the jdbc connector). I need to import multiple tables(user, order and payment) to kakfa and multiple sinks from some topics

1. Can we import a table via a schema that have registered in schema registry? ex: table has 10 columns but i need only 2 columns. I know possible write a query in the source connector if you have one table. But if its possible to use a schema that would be very easy with multiple tables

2. Lets say i have one topic, i want to sink it into multiple tables, like below currently we do it by using consumers, is it possible to achieve this via sink connector? if so should use 2 properties files with the task 1? or is there any better way to achieve this in kafka?
            

- Source Table: user(col1..5)

- Sink table1: user_address(col2, col5) 
- Sink table2: user_profile (col1, col2, col3)

**Comment by tmancill** [comment]
Hi @ntwobike .  Regarding question (1) - using a single source for multiple tables, we've having good luck using a VIEW to join the tables together with a single source connector.  Just be sure to set `table.types=VIEW` in your source connector properties.  You can also `table.whitelist` to be just the name of the view.

I haven't tried a configuration like (2), but believe that you can easily configure two separate sinks to achieve this easily.

**Comment by gmyrianthous** [comment]
What configuration is required in order to stream data from a single kafka topic into two distinct tables (which are placed under two distinct databases) so that both tables contain exactly the same data?

**Comment by tmancill** [comment]
Hi @gmyrianthous .  I believe you simply need to run two separate connectors, each configured as a sink reading from the same topic.  One of them writes to database_a and the other writes to database_b.
