### ISSUE TITLE
JDBC Connector throws OOM Error

### ISSUE THREAD

**Issue by amit-c1x** [confluentinc/kafka-connect-jdbc#279]
My source table is huge with 2M+ rows and i am using incrementing mode with custom query. However, right after starting the connector, jvm throws out of memory error. 

Looking at the generated SQL query
`select * from my_table WHERE `sna_id` > ? ORDER BY `sna_id` ASC`

There is a high chance this query will throw OOM at the initial pass. 
Has this issue never been encountered before?
Is there something i am doing differently?

The SQL query should have LIMIT <VALUE> to limit the number of rows returned.

**Comment by zhensun** [comment]
I think it's related to #34 .

**Comment by amit-c1x** [comment]
Ok, will close this one.

**Comment by laratutoteam** [comment]
**get this easy error solving** https://laratuto.com/solved-out-of-memory-error-in-query-sybase_connect/
