### ISSUE TITLE
JDBC Source: All topic partitions are empty except one

### ISSUE THREAD

**Issue by amit-c1x** [confluentinc/kafka-connect-jdbc#294]
I am sourcing a table into kafka. My topic has 50 partitions but all partitions but one are empty.

Here is what I have investigated so far:

- I do not see any partitioning related config in JDBC connector.
- Even increasing the ```tasks.max``` config from 1 to 10 does not have any effect.

Is there a way I can evenly distribute my data into ALL the partitions?

**Comment by rhauch** [comment]
As you mention above, the JDBC source connector current creates records without a partition number (see [here](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/source/BulkTableQuerier.java#L86) and [here](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java#L224)).

When no partition is specified in the record, the standard Kafka producer will attempt to partition based upon the record's key. However, the JDBC source connector currently generates a null key (see #28). That means that the producer has no information on which to determine the partition where the record is to be written.

There are two options, and both involve using Single Message Transforms (SMTs). The first option is to use `ValueToKey` transformation (see the [Kafka documentation](https://kafka.apache.org/documentation/#connect_transforms)) to extract a set of fields from the value into the key. Once your records have a key, the default producer partitioner will use that to send all messages with the same key to the same partition.

The second option is to use a custom SMT that computes the partition number directly. There's a more detailed description on [StackOverflow](https://stackoverflow.com/questions/44810221/setting-partition-strategy-in-a-kafka-connector).
