### ISSUE TITLE
Add DBMS-specific dialects to source connector

### ISSUE THREAD

**Issue by rhauch** [confluentinc/kafka-connect-jdbc#303]
Change the JDBC source connector to use dialect components, and create the first default dialect that has all of the existing functionality. The framework should determine which dialect to use based upon the JDBC connection URL string and/or the JDBC Connection instance. (Note the dialect is not involved in establishing the connection.) Include an abstract test class that can be used to easily verify the functionality of individual dialects.

This change will make it easier to correct DBMS-specific issues, including but not limited to:
* #230 
* #231 
* #101 
* #103 
* #213 
* #221 
* #299 
* #101 
* #103 
* #116 
* #81 
* #211 
* #46

Feel free to mention this issue on other issues that will be easier to fix once the source connector has DBMS-specific dialects.

**Comment by giampaolotrapasso** [comment]
Hi! Any updates on the release of this change? I'm interested in particular in the Sybase compatibility.

**Comment by rhauch** [comment]
I hope to get back to this soon. We're getting close to releasing 4.1, and this seemed too risky without additional testing to verify it introduces no regression. Any additional testing of #333 would be appreciated. I'd love to incorporate integration tests into the Maven build (see #342) so we can run against multiple DBMSes (with different profiles).
