### ISSUE TITLE
Non-Resolvable parent POM when building kafka-connect-jdbc development version

### ISSUE THREAD

**Issue by dperez4787** [confluentinc/kafka-connect-jdbc#320]
I am attempting to build a local development version of the kafka-connect-jdbc project (version 4.0.0-post).   The 3.3.1 version of the kafka-connect-jdbc project has bult successfully for me in the past (version 3.3.1 and below), but the introduction of the following into the pom.xml seems to be preventing a successful local build: 

`    <parent>
        <groupId>io.confluent</groupId>
        <artifactId>common</artifactId>
        <version>4.1.0-SNAPSHOT</version>
    </parent>`

The following maven project build error is printed: 

`Project build error: Non-resolvable parent POM for io.confluent:kafka-connect-jdbc:[unknown-version]: Failure to transfer io.confluent:common:pom:4.0.0 from ${confluent.maven.repo} was cached in the local repository, resolution will not be reattempted until the update interval of confluent has elapsed or updates are forced. Original error: Could not transfer artifact io.confluent:common:pom:4.0.0 from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: AetherRepositoryConnectorFactory, BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM`

How can I gain access to the parent pom.xml file to resolve this issue?

**Comment by kkonstantine** [comment]
Please checkout, build and install locally the following repo: 

https://github.com/confluentinc/common

There was a need to consolidate dependencies among various modules (especially connectors) across the `confluentinc` org.

**Comment by dperez4787** [comment]
@kkonstantine thanks for the prompt explanation.  Installing the common project via maven allowed me to build everything successfully (including the schema-registry after installing the rest-utils project as well).

**Comment by Kiran381** [comment]
Hi,
After importing project to my STS and running mvn install am facing an issue **Non-resolvable parent POM for io.confluent:kafka-connect-jdbc:[unknown-version]: Could not transfer artifact io.confluent:common:pom:5.5.0-SNAPSHOT from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 22, column 13: Cannot access ${confluent.maven.repo} using the registered transporter factories: WagonTransporterFactory: Unsupported transport protocol -> [Help 2]**
Tried Solution given by **kkonstantine**
Still found the same issue.
Can any One resolve the error.
I think am facing the same issues faced by **dperez4787**
How can I gain access to the parent pom.xml file to resolve this issue?
PFA

![KafkaJdbcError](https://user-images.githubusercontent.com/47963378/70706849-c921e700-1cfc-11ea-922e-23a5902004ec.png)
