### ISSUE TITLE
HDFS CONNECT

### ISSUE THREAD

**Issue by imthiyas15** [confluentinc/kafka-connect-jdbc#322]
I am not able to load the below kafka message to HDFS or Hive using connector.

Message in kafka
1211,dasd,asdsad,asdsadas
1233,sad,dasdas,dsadasdd
1234,null

I am getting a error while load with null record into hive 
How to load this message into hive using hdfs-connect

**Comment by kkonstantine** [comment]
I will have to close this issue because it's submitted in the wrong repo. 

Please re-submit in https://github.com/confluentinc/kafka-connect-hdfs if this is still an issue for you.
