### ISSUE TITLE
Support for Kafka transactions in source

### ISSUE THREAD

**Issue by maver1ck** [confluentinc/kafka-connect-jdbc#325]
I'd like to have in this connector support for Kafka transactions.
This gives us possibility to process every record exactly-once

**Comment by rhauch** [comment]
Connectors don't actually talk to Kafka, and instead Connect does all the work of writing to and reading from Kafka. EOS support in Connect is already on the roadmap, though for source connectors.

**Comment by ghilainm** [comment]
@rhauch Any idea when those enhancement will arrive in Kafka? What is the recommended way to have exactly-once semantic when using JDBC source?
