### ISSUE TITLE
No suitable driver for jdbc...

### ISSUE THREAD

**Issue by glarus089** [confluentinc/kafka-connect-jdbc#329]
Hello. 
Tying to create jdbc source connector (confluent 4.0.0.0) and getting errors  "No suitable driver..."
but nessesary driver jar was added to /usr/share/java/kafka-connect-jdbc

**Comment by cdtran** [comment]
Running into the same issue

**Comment by wicknicks** [comment]
Could you give us some more details? It would be useful to know which database (name, version) we are working with, stacktrace (if any), and the folder contents of the /usr/share/java/kafka-connect-jdbc directory.

**Comment by ketchupex** [comment]
Im using docker and i have same problem. Kafka Connect downloads connectors from repository, but somehow it doesnt see it on its classpath. I downloaded them from website and included manually in /tmp/quickstart/jars/ (and by using  -v /tmp/quickstart/jars:/etc/kafka-connect/jars while running docker, it copies it to folder, where Kafka Connect sees it) and it worked. However, its only a workaround

**Comment by rhauch** [comment]
Did you download and include the JDBC driver JAR in the same directory where the JDBC connector's JARs are located?

> Kafka Connect downloads connectors from repository

Are you referring to what happens when Confluent's Docker image is created? Connect certainly doesn't download anything during runtime.

**Comment by ketchupex** [comment]
Yep, i downloaded jars and included them into container's /etc/kafka-connect/jars directory. Im using cp-kafka-connect image from docker hub (version 4.0.0). In the [dockerfile](https://github.com/confluentinc/cp-docker-images/blob/4.0.x/debian/kafka-connect/Dockerfile) there's such a command

```bash
RUN echo "===> Installing JDBC, Elasticsearch and Hadoop connectors ..." \
    && apt-get -qq update \
    && apt-get install -y \
        confluent-kafka-connect-jdbc=${CONFLUENT_VERSION}${CONFLUENT_PLATFORM_LABEL}-${CONFLUENT_DEB_VERSION} \
        confluent-kafka-connect-hdfs=${CONFLUENT_VERSION}${CONFLUENT_PLATFORM_LABEL}-${CONFLUENT_DEB_VERSION} \
        confluent-kafka-connect-elasticsearch=${CONFLUENT_VERSION}${CONFLUENT_PLATFORM_LABEL}-${CONFLUENT_DEB_VERSION} \
        confluent-kafka-connect-storage-common=${CONFLUENT_VERSION}${CONFLUENT_PLATFORM_LABEL}-${CONFLUENT_DEB_VERSION} \
        confluent-kafka-connect-s3=${CONFLUENT_VERSION}${CONFLUENT_PLATFORM_LABEL}-${CONFLUENT_DEB_VERSION} \
    && echo "===> Cleaning up ..."  \
    && apt-get clean && rm -rf /tmp/* /var/lib/apt/lists/*
```
and I thought that means that it downloads connectors . I looked down the folders and I found them at /usr/share/java/ (if i remember it properly), however when I tried to create new connector through REST API (according to the tutorial), kafka-connect couldn't find any matching connector (i tried to create JdbcSourceConnector). Thats why I included them manually into /etc/kafka-connect/jars/ while creating kafka-connect containernand it worked out.

**Comment by adammsteele** [comment]
Try adding 
`CONNECT_PLUGIN_PATH: /usr/share/java` 
as an environment variable to your connect docker image.

**Comment by glarus089** [comment]
In my case i have 3 Centos7 hosts with confluent 4 installed. By this recommendations https://docs.confluent.io/current/connect/connect-jdbc/docs/source_connector.html#configuration mysql jdbc driver jar placed into  /usr/share/java/kafka-connect-jdbc/ :+1: 
```
[administrator@kfk1~]$ ls -l /usr/share/java/kafka-connect-jdbc/
итого 10076
-rw-r--r--. 1 root root   20846 ноя 21 22:32 common-utils-4.0.0.jar
-rw-r--r--. 1 root root   87325 ноя 21 22:32 jline-0.9.94.jar
-rw-r--r--. 1 root root  141498 ноя 21 22:32 kafka-connect-jdbc-4.0.0.jar
-rw-r--r--. 1 root root  489884 ноя 21 22:32 log4j-1.2.17.jar
-rw-r--r--. 1 root root  999810 янв  7 02:54 mysql-connector-java-5.1.45-bin.jar
-rw-r--r--. 1 root root 1330394 ноя 21 22:32 netty-3.10.5.Final.jar
-rw-r--r--. 1 root root  658466 ноя 21 22:32 postgresql-9.4-1206-jdbc41.jar
-rw-r--r--. 1 root root   41203 ноя 21 22:32 slf4j-api-1.7.25.jar
-rw-r--r--. 1 root root 5575351 ноя 21 22:32 sqlite-jdbc-3.8.11.2.jar
-rw-r--r--. 1 root root   74798 ноя 21 22:32 zkclient-0.10.jar
-rw-r--r--. 1 root root  871369 ноя 21 22:32 zookeeper-3.4.10.jar 
```
Then ps command out is :
```
conflue+  9435 25.6 28.0 2332056 212368 pts/0  Sl   03:10   0:23 java -Xmx256M -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent -Djava.awt.headless=true -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dkafka.logs.dir=/var/log/kafka -Dlog4j.configuration=file:/etc/kafka/connect-log4j.properties -cp /usr/share/java/kafka/*:/usr/share/java/confluent-common/*:/usr/share/java/kafka-serde-tools/*:/bin/../share/java/kafka/*:/bin/../share/java/confluent-support-metrics/*:/usr/share/java/confluent-support-metrics/* org.apache.kafka.connect.cli.ConnectDistributed /tmp/confluent.uMKJiSOw/connect/connect.properties
```
and connect log with classpath is :
```
jvm.classpath = /usr/share/java/kafka/aopalliance-repackaged-2.5.0-b32.jar:/usr/share/java/kafka/kafka-log4j-appender-1.0.0-cp1.jar:/usr/share/java/kafka/argparse4j-0.7.0.jar:/usr/share/java/kafka/xz-1.5.jar:/usr/share/java/kafka/avro-1.8.2.jar:/usr/share/java/kafka/kafka-streams-1.0.0-cp1.jar:/usr/share/java/kafka/commons-beanutils-1.8.3.jar:/usr/share/java/kafka/kafka-streams-examples-1.0.0-cp1.jar:/usr/share/java/kafka/commons-codec-1.9.jar:/usr/share/java/kafka/jersey-container-servlet-core-2.25.1.jar:/usr/share/java/kafka/commons-collections-3.2.1.jar:/usr/share/java/kafka/kafka-tools-1.0.0-cp1.jar:/usr/share/java/kafka/commons-compress-1.8.1.jar:/usr/share/java/kafka/kafka.jar:/usr/share/java/kafka/commons-digester-1.8.1.jar:/usr/share/java/kafka/kafka_2.11-1.0.0-cp1-javadoc.jar:/usr/share/java/kafka/commons-lang3-3.1.jar:/usr/share/java/kafka/kafka_2.11-1.0.0-cp1-scaladoc.jar:/usr/share/java/kafka/commons-lang3-3.5.jar:/usr/share/java/kafka/kafka_2.11-1.0.0-cp1-sources.jar:/usr/share/java/kafka/commons-logging-1.2.jar:/usr/share/java/kafka/kafka_2.11-1.0.0-cp1-test.jar:/usr/share/java/kafka/commons-validator-1.4.1.jar:/usr/share/java/kafka/kafka_2.11-1.0.0-cp1.jar:/usr/share/java/kafka/connect-api-1.0.0-cp1.jar:/usr/share/java/kafka/log4j-1.2.17.jar:/usr/share/java/kafka/connect-file-1.0.0-cp1.jar:/usr/share/java/kafka/lz4-java-1.4.jar:/usr/share/java/kafka/connect-json-1.0.0-cp1.jar:/usr/share/java/kafka/jersey-guava-2.25.1.jar:/usr/share/java/kafka/connect-runtime-1.0.0-cp1.jar:/usr/share/java/kafka/jersey-media-jaxb-2.25.1.jar:/usr/share/java/kafka/connect-transforms-1.0.0-cp1.jar:/usr/share/java/kafka/zkclient-0.10.jar:/usr/share/java/kafka/guava-20.0.jar:/usr/share/java/kafka/maven-artifact-3.5.0.jar:/usr/share/java/kafka/hk2-api-2.5.0-b32.jar:/usr/share/java/kafka/metrics-core-2.2.0.jar:/usr/share/java/kafka/hk2-locator-2.5.0-b32.jar:/usr/share/java/kafka/osgi-resource-locator-1.0.1.jar:/usr/share/java/kafka/hk2-utils-2.5.0-b32.jar:/usr/share/java/kafka/paranamer-2.7.jar:/usr/share/java/kafka/httpclient-4.5.2.jar:/usr/share/java/kafka/zookeeper-3.4.10.jar:/usr/share/java/kafka/httpcore-4.4.4.jar:/usr/share/java/kafka/httpmime-4.5.2.jar:/usr/share/java/kafka/jetty-server-9.2.22.v20170606.jar:/usr/share/java/kafka/jackson-annotations-2.9.1.jar:/usr/share/java/kafka/plexus-utils-3.0.24.jar:/usr/share/java/kafka/jackson-core-2.9.1.jar:/usr/share/java/kafka/reflections-0.9.11.jar:/usr/share/java/kafka/jackson-core-asl-1.9.13.jar:/usr/share/java/kafka/rocksdbjni-5.7.3.jar:/usr/share/java/kafka/jackson-databind-2.9.1.jar:/usr/share/java/kafka/jetty-servlet-9.2.22.v20170606.jar:/usr/share/java/kafka/jackson-jaxrs-base-2.9.1.jar:/usr/share/java/kafka/jersey-common-2.25.1.jar:/usr/share/java/kafka/jackson-jaxrs-json-provider-2.9.1.jar:/usr/share/java/kafka/jetty-servlets-9.2.22.v20170606.jar:/usr/share/java/kafka/jackson-mapper-asl-1.9.13.jar:/usr/share/java/kafka/jersey-container-servlet-2.25.1.jar:/usr/share/java/kafka/jackson-module-jaxb-annotations-2.9.1.jar:/usr/share/java/kafka/scala-library-2.11.11.jar:/usr/share/java/kafka/javassist-3.20.0-GA.jar:/usr/share/java/kafka/slf4j-api-1.7.25.jar:/usr/share/java/kafka/javassist-3.21.0-GA.jar:/usr/share/java/kafka/jetty-util-9.2.22.v20170606.jar:/usr/share/java/kafka/javax.annotation-api-1.2.jar:/usr/share/java/kafka/javax.inject-1.jar:/usr/share/java/kafka/slf4j-log4j12-1.7.25.jar:/usr/share/java/kafka/javax.inject-2.5.0-b32.jar:/usr/share/java/kafka/snappy-java-1.1.4.jar:/usr/share/java/kafka/javax.servlet-api-3.1.0.jar:/usr/share/java/kafka/support-metrics-client-4.0.0.jar:/usr/share/java/kafka/javax.ws.rs-api-2.0.1.jar:/usr/share/java/kafka/support-metrics-common-4.0.0.jar:/usr/share/java/kafka/jersey-client-2.25.1.jar:/usr/share/java/kafka/jersey-server-2.25.1.jar:/usr/share/java/kafka/jetty-security-9.2.22.v20170606.jar:/usr/share/java/kafka/jetty-continuation-9.2.22.v20170606.jar:/usr/share/java/kafka/jopt-simple-5.0.4.jar:/usr/share/java/kafka/jetty-http-9.2.22.v20170606.jar:/usr/share/java/kafka/kafka-clients-1.0.0-cp1.jar:/usr/share/java/kafka/jetty-io-9.2.22.v20170606.jar:/usr/share/java/kafka/kafka_2.11-1.0.0-cp1-test-sources.jar:/usr/share/java/kafka/validation-api-1.1.0.Final.jar:/usr/share/java/confluent-common/build-tools-4.0.0.jar:/usr/share/java/confluent-common/common-config-4.0.0.jar:/usr/share/java/confluent-common/common-metrics-4.0.0.jar:/usr/share/java/confluent-common/common-utils-4.0.0.jar:/usr/share/java/confluent-common/jline-0.9.94.jar:/usr/share/java/confluent-common/log4j-1.2.17.jar:/usr/share/java/confluent-common/netty-3.10.5.Final.jar:/usr/share/java/confluent-common/slf4j-api-1.7.25.jar:/usr/share/java/confluent-common/zkclient-0.10.jar:/usr/share/java/confluent-common/zookeeper-3.4.10.jar:/usr/share/java/kafka-serde-tools/avro-1.8.2.jar:/usr/share/java/kafka-serde-tools/commons-compress-1.8.1.jar:/usr/share/java/kafka-serde-tools/jackson-annotations-2.9.1.jar:/usr/share/java/kafka-serde-tools/jackson-core-2.9.1.jar:/usr/share/java/kafka-serde-tools/jackson-core-asl-1.9.13.jar:/usr/share/java/kafka-serde-tools/jackson-databind-2.9.1.jar:/usr/share/java/kafka-serde-tools/jackson-mapper-asl-1.9.13.jar:/usr/share/java/kafka-serde-tools/kafka-avro-serializer-4.0.0.jar:/usr/share/java/kafka-serde-tools/kafka-connect-avro-converter-4.0.0.jar:/usr/share/java/kafka-serde-tools/kafka-json-serializer-4.0.0.jar:/usr/share/java/kafka-serde-tools/kafka-schema-registry-client-4.0.0.jar:/usr/share/java/kafka-serde-tools/paranamer-2.7.jar:/usr/share/java/kafka-serde-tools/snappy-java-1.1.1.3.jar:/usr/share/java/kafka-serde-tools/xz-1.5.jar:/bin/../share/java/kafka/aopalliance-repackaged-2.5.0-b32.jar:/bin/../share/java/kafka/kafka-log4j-appender-1.0.0-cp1.jar:/bin/../share/java/kafka/argparse4j-0.7.0.jar:/bin/../share/java/kafka/xz-1.5.jar:/bin/../share/java/kafka/avro-1.8.2.jar:/bin/../share/java/kafka/kafka-streams-1.0.0-cp1.jar:/bin/../share/java/kafka/commons-beanutils-1.8.3.jar:/bin/../share/java/kafka/kafka-streams-examples-1.0.0-cp1.jar:/bin/../share/java/kafka/commons-codec-1.9.jar:/bin/../share/java/kafka/jersey-container-servlet-core-2.25.1.jar:/bin/../share/java/kafka/commons-collections-3.2.1.jar:/bin/../share/java/kafka/kafka-tools-1.0.0-cp1.jar:/bin/../share/java/kafka/commons-compress-1.8.1.jar:/bin/../share/java/kafka/kafka.jar:/bin/../share/java/kafka/commons-digester-1.8.1.jar:/bin/../share/java/kafka/kafka_2.11-1.0.0-cp1-javadoc.jar:/bin/../share/java/kafka/commons-lang3-3.1.jar:/bin/../share/java/kafka/kafka_2.11-1.0.0-cp1-scaladoc.jar:/bin/../share/java/kafka/commons-lang3-3.5.jar:/bin/../share/java/kafka/kafka_2.11-1.0.0-cp1-sources.jar:/bin/../share/java/kafka/commons-logging-1.2.jar:/bin/../share/java/kafka/kafka_2.11-1.0.0-cp1-test.jar:/bin/../share/java/kafka/commons-validator-1.4.1.jar:/bin/../share/java/kafka/kafka_2.11-1.0.0-cp1.jar:/bin/../share/java/kafka/connect-api-1.0.0-cp1.jar:/bin/../share/java/kafka/log4j-1.2.17.jar:/bin/../share/java/kafka/connect-file-1.0.0-cp1.jar:/bin/../share/java/kafka/lz4-java-1.4.jar:/bin/../share/java/kafka/connect-json-1.0.0-cp1.jar:/bin/../share/java/kafka/jersey-guava-2.25.1.jar:/bin/../share/java/kafka/connect-runtime-1.0.0-cp1.jar:/bin/../share/java/kafka/jersey-media-jaxb-2.25.1.jar:/bin/../share/java/kafka/connect-transforms-1.0.0-cp1.jar:/bin/../share/java/kafka/zkclient-0.10.jar:/bin/../share/java/kafka/guava-20.0.jar:/bin/../share/java/kafka/maven-artifact-3.5.0.jar:/bin/../share/java/kafka/hk2-api-2.5.0-b32.jar:/bin/../share/java/kafka/metrics-core-2.2.0.jar:/bin/../share/java/kafka/hk2-locator-2.5.0-b32.jar:/bin/../share/java/kafka/osgi-resource-locator-1.0.1.jar:/bin/../share/java/kafka/hk2-utils-2.5.0-b32.jar:/bin/../share/java/kafka/paranamer-2.7.jar:/bin/../share/java/kafka/httpclient-4.5.2.jar:/bin/../share/java/kafka/zookeeper-3.4.10.jar:/bin/../share/java/kafka/httpcore-4.4.4.jar:/bin/../share/java/kafka/httpmime-4.5.2.jar:/bin/../share/java/kafka/jetty-server-9.2.22.v20170606.jar:/bin/../share/java/kafka/jackson-annotations-2.9.1.jar:/bin/../share/java/kafka/plexus-utils-3.0.24.jar:/bin/../share/java/kafka/jackson-core-2.9.1.jar:/bin/../share/java/kafka/reflections-0.9.11.jar:/bin/../share/java/kafka/jackson-core-asl-1.9.13.jar:/bin/../share/java/kafka/rocksdbjni-5.7.3.jar:/bin/../share/java/kafka/jackson-databind-2.9.1.jar:/bin/../share/java/kafka/jetty-servlet-9.2.22.v20170606.jar:/bin/../share/java/kafka/jackson-jaxrs-base-2.9.1.jar:/bin/../share/java/kafka/jersey-common-2.25.1.jar:/bin/../share/java/kafka/jackson-jaxrs-json-provider-2.9.1.jar:/bin/../share/java/kafka/jetty-servlets-9.2.22.v20170606.jar:/bin/../share/java/kafka/jackson-mapper-asl-1.9.13.jar:/bin/../share/java/kafka/jersey-container-servlet-2.25.1.jar:/bin/../share/java/kafka/jackson-module-jaxb-annotations-2.9.1.jar:/bin/../share/java/kafka/scala-library-2.11.11.jar:/bin/../share/java/kafka/javassist-3.20.0-GA.jar:/bin/../share/java/kafka/slf4j-api-1.7.25.jar:/bin/../share/java/kafka/javassist-3.21.0-GA.jar:/bin/../share/java/kafka/jetty-util-9.2.22.v20170606.jar:/bin/../share/java/kafka/javax.annotation-api-1.2.jar:/bin/../share/java/kafka/javax.inject-1.jar:/bin/../share/java/kafka/slf4j-log4j12-1.7.25.jar:/bin/../share/java/kafka/javax.inject-2.5.0-b32.jar:/bin/../share/java/kafka/snappy-java-1.1.4.jar:/bin/../share/java/kafka/javax.servlet-api-3.1.0.jar:/bin/../share/java/kafka/support-metrics-client-4.0.0.jar:/bin/../share/java/kafka/javax.ws.rs-api-2.0.1.jar:/bin/../share/java/kafka/support-metrics-common-4.0.0.jar:/bin/../share/java/kafka/jersey-client-2.25.1.jar:/bin/../share/java/kafka/jersey-server-2.25.1.jar:/bin/../share/java/kafka/jetty-security-9.2.22.v20170606.jar:/bin/../share/java/kafka/jetty-continuation-9.2.22.v20170606.jar:/bin/../share/java/kafka/jopt-simple-5.0.4.jar:/bin/../share/java/kafka/jetty-http-9.2.22.v20170606.jar:/bin/../share/java/kafka/kafka-clients-1.0.0-cp1.jar:/bin/../share/java/kafka/jetty-io-9.2.22.v20170606.jar:/bin/../share/java/kafka/kafka_2.11-1.0.0-cp1-test-sources.jar:/bin/../share/java/kafka/validation-api-1.1.0.Final.jar:/bin/../share/java/confluent-support-metrics/*:/usr/share/java/confluent-support-metrics/*
```

**Comment by wicknicks** [comment]
@glarus089: Thanks for the details! 

Since you are loading jdbc as a driver, set `plugin.path` in your connect properties to `/usr/share/java`. If you are using docker, then set the environment variable `CONNECT_PLUGIN_PATH` as @adammsteele pointed out.

**Comment by glarus089** [comment]
@wicknicks Thanks for reply.
My /etc/kafka/connect-distributed.properties  alredy contains plugin.path=/usr/share/java

**Comment by wicknicks** [comment]
It might be that you need a different version of mysql driver for your database. Or, the driver need to be compiled against a different version of Java (for example, the jar you have was built for java 8, but Conenct is running on a Java 7 VM). We saw an issue here a couple of days ago, where downgrading the oracle driver to an older version got things to work. The stack trace might give more details.

**Comment by wicknicks** [comment]
Also, what is your `connection.url` in worker properties?

**Comment by glarus089** [comment]
@wicknicks , thank you. So, sorry for not very fast reply. What we have... In our case only placing in /usr/share/java/kafka/ resolved problem.

**Comment by wicknicks** [comment]
Ok cool! Glad your problem is resolved. Closing this issue.

**Comment by gunjdesai** [comment]
@wicknicks , I've run into a similar problem. Unfortunately, I didnt find this thread earlier and posted the question on StackOverflow.

[Question Link](https://stackoverflow.com/questions/49433199/kafka-connect-jdbc-source-connector-not-working-for-microsoft-sql-server)

I have mentioned all the details there, it would really great if you can point out where i might be going wrong

**Comment by gunjdesai** [comment]
@wicknicks, thanks for looking into the issue instantly. Really appreciate it.

**Comment by junaidrazzaq323** [comment]
I am running into the same exception:
`INFO Unable to connect to database on attempt 1/3. Will retry in 10000 ms. (io.confluent.connect.jdbc.util.CachedConnectionProvider:91)`
`java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/casb`

**Sink.properties:**

`name=test-sink`
`connector.class=io.confluent.connect.jdbc.JdbcSinkConnector`
`tasks.max=1`
`topics=fp_test`
`connection.url=jdbc:postgresql://localhost:5432/casb`
`connection.user=admin`
`connection.password=***`
`auto.create=true`

I have set `plugin.path=/usr/share/java/kafka-connect-jdbc`

On **/usr/share/java/kafka-connect-jdbc** I have the following files:

`kafka-connect-jdbc-4.0.0.jar` , `postgresql-9.4-1206-jdbc41.jar`, `sqlite-jdbc-3.8.11.2.jar` and some other jars that basically come packaged along with confluent.

Kindly help me out with this.

**Comment by rhauch** [comment]
As mentioned on #433, start by setting `plugin.path=/usr/share/java`. See [Installing Plugins](https://docs.confluent.io/current/connect/userguide.html#installing-plugins), where in this case `/usr/share/java/kafka-connect-jdbc` is a _plugin directory_ (i.e., the directory for the JDBC connector plugin) that is _inside_ one of the directories (e.g., `/usr/share/java`) on the plugin path. 

Then place all necessary JDBC driver JARs in the `/usr/share/java/kafka-connect-jdbc` directory so the JDBC connector plugin can find them. As you mention, the PG and Sqlite JDBC drivers are already there, but any other JDBC drivers (e.g., Calcite and any 3rd party dependencies) should be there, too.

**Comment by bkotesh** [comment]
@wicknicks , i am also facing the same issue while connecting mysql(5.6) version through jdbc.
Please help me to solve this.

[devkafka@CHBLUXPC01 confluent-5.0.0]$ ./bin/confluent load jdbc_source_mysql_foobar_01 -d /tmp/kafka-connect-jdbc-source.json
This CLI is intended for development only, not for production
https://docs.confluent.io/current/cli/index.html

{
  "error_code": 400,
  "message": "Connector configuration is invalid and contains the following 2 error(s):\nInvalid value java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/demo?user=rmoff&password=pw for configuration Couldn't open connection to jdbc:mysql://localhost:3306/demo?user=rmoff&password=pw\nInvalid value java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/demo?user=rmoff&password=pw for configuration Couldn't open connection to jdbc:mysql://localhost:3306/demo?user=rmoff&password=pw\nYou can also find the above list of errors at the endpoint `/{connectorType}/config/validate`"
}
=====================================================
[devkafka@CHBLUXPC01 confluent-5.0.0]$ cat /tmp/kafka-connect-jdbc-source.json
{
        "name": "jdbc_source_mysql_foobar_01",
        "config": {
                "_comment": "The JDBC connector class. Don't change this if you want to use the JDBC Source.",
                "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",

                "_comment": "How to serialise the value of keys - here use the Confluent Avro serialiser. Note that the JDBC Source Connector always returns null for the key ",
                "key.converter": "io.confluent.connect.avro.AvroConverter",

                "_comment": "Since we're using Avro serialisation, we need to specify the Confluent schema registry at which the created schema is to be stored. NB Schema Registry and Avro serialiser are both part of Confluent Open Source.",
                "key.converter.schema.registry.url": "http://localhost:8081",

                "_comment": "As above, but for the value of the message. Note that these key/value serialisation settings can be set globally for Connect and thus omitted for individual connector configs to make them shorter and clearer",
                "value.converter": "io.confluent.connect.avro.AvroConverter",
                "value.converter.schema.registry.url": "http://localhost:8081",


                "_comment": " --- JDBC-specific configuration below here  --- ",
                "_comment": "JDBC connection URL. This will vary by RDBMS. Consult your manufacturer's handbook for more information",
                "connection.url": "jdbc:mysql://localhost:3306/demo?user=rmoff&password=pw",

                "_comment": "Which table(s) to include",
                "table.whitelist": "foobar",

                "_comment": "Pull all rows based on an timestamp column. You can also do bulk or incrementing column-based extracts. For more information, see http://docs.confluent.io/current/connect/connect-jdbc/docs/source_config_options.html#mode",
                "mode": "timestamp",

                "_comment": "Which column has the timestamp value to use?  ",
                "timestamp.column.name": "update_ts",

                "_comment": "If the column is not defined as NOT NULL, tell the connector to ignore this  ",
                "validate.non.null": "false",

                "_comment": "The Kafka topic will be made up of this prefix, plus the table name  ",
                "topic.prefix": "mysql-"
        }
}

**Comment by rmoff** [comment]
@bkotesh please open a new ticket, and reference this one if you think it's relevant. Generally JDBC driver issues are down to the driver JAR not being in the correct path for Connect to locate.
