### ISSUE TITLE
Oracle Column Type Number Not Converted Back From Bytes

### ISSUE THREAD

**Issue by alogan44** [confluentinc/kafka-connect-jdbc#33]
I am getting unicode output from the avro-console-consumer for records that were inserted into number columns.  Sent to Kafka using JDBCSourceConnector.  

Steps to Reproduce:
1. I started zookeeper, single kafka server, and schema registry
2. I created simple table in oracle, with a couple columns of type number.
_**create table employees( empno Number(5), ename varchar2(20), created timestamp default sysdate);**_ 
3. I then inserted some records into the oracle table.
_**insert into employees(empno, ename) values(1, 'bob');**_
_**insert into employees(empno, ename) values(2, 'alice');**_
4. I started the kafka-avro-consumer and received the following as output:
_**{"EMPNO":{"bytes":"\u0002"},"ENAME":{"string":"alice"},"CREATED":{"long":1452175115000}}**_
_**{"EMPNO":{"bytes":"\u0001"},"ENAME":{"string":"bob"},"CREATED":{"long":1452175115000}}**_

Appears Conversions of column type number are not working properly in Connector

**Comment by ewencp** [comment]
@alogan44 Is this basically the same issue as #31? It looks like the problem in both cases is that the number type is being converted to bytes because it is being returned as a BigDecimal and that is the only way to fully preserve the possible precision, but in your case you would actually prefer it be returned as an integer?

**Comment by remosuurkivi** [comment]
Hi
Same issue is with MySQL at least currently and even more confusing between Avro and Json serializers:
Avro - original value 100.00 : result "current_amount":"\u0010"
          original value 0.00 : result "current_amount":"\u0000"
Json - original value 100.00 : result "credit_limit":"JxA="
           original value 100.00 : result "credit_limit":"AA=="

**Comment by shikhar** [comment]
Closing in favor of #101

**Comment by mancini77** [comment]
I wrote a script that will help you generate the appropriate NUMBER(scale,precison) casts, if anybody is using connect in query mode this may be helpful. 

SET SERVEROUTPUT ON;
DECLARE
   Q1    VARCHAR2 (4000 CHAR);
   str   VARCHAR2 (300 CHAR);
BEGIN
   FOR rec
      IN (SELECT  column_name AS column_name
            FROM all_tab_cols
           WHERE     owner = 'YOUR_SCHEMA'
                 AND TABLE_NAME = 'YOUR_TABLE'
                 AND DATA_TYPE = 'NUMBER')
   LOOP
      q1 :=
         'SELECT    REPLACE(''cast( ''
             || :1
             || '' as  NUMBER(''
             || TO_CHAR (MAX (LENGTH_OF_DECIMAL) + MAX (length_of_integer))
             || '',''
             || TO_CHAR (MAX (length_of_decimal))
             || ''))'',''NUMBER(0,0)'',''NUMBER'') as result
        FROM (SELECT charnum,
                     CASE
                        WHEN INSTR (charnum, ''.'') > 0
                        THEN
                           SUBSTR (charnum, INSTR (charnum, ''.'') + 1)
                        ELSE
                           NULL
                     END
                        AS decimal_part,
                     CASE
                        WHEN INSTR (charnum, ''.'') > 0
                        THEN
                           REPLACE (
                              REPLACE (
                                 SUBSTR (charnum,
                                         1,
                                         INSTR (charnum, ''.'') - 1),
                                 ''-'',
                                 ''''),
                              ''+'',
                              '''')
                        ELSE
                           REPLACE (REPLACE (charnum, ''-'', ''''), ''+'', '''')
                     END
                        AS integer_part,
                     CASE
                        WHEN INSTR (charnum, ''.'') > 0
                        THEN
                           LENGTH (
                              SUBSTR (charnum, INSTR (charnum, ''.'') + 1))
                        ELSE
                           0
                     END
                        AS length_of_decimal,
                     CASE
                        WHEN INSTR (charnum, ''.'') > 0
                        THEN
                           NVL (
                              LENGTH (
                                 REPLACE (
                                    REPLACE (
                                       SUBSTR (charnum,
                                               1,
                                               INSTR (charnum, ''.'') - 1),
                                       ''-'',
                                       ''''),
                                    ''+'',
                                    '''')),
                              0)
                        ELSE
                           NVL (
                              LENGTH (
                                 REPLACE (REPLACE (charnum, ''-'', ''''),
                                          ''+'',
                                          '''')),
                              0)
                     END
                        AS length_of_integer
                FROM (SELECT cast(col_name2 AS VARCHAR2 (50))
                                AS charnum
                        FROM YOUR_TABLE)) T1';

      q1 := REPLACE (q1, 'col_name2', rec.column_name);

      EXECUTE IMMEDIATE REPLACE (q1, 'col_name2', rec.column_name)
         INTO str
         USING rec.column_name;

      DBMS_OUTPUT.PUT_LINE (str);
   END LOOP;
END;
/

**Comment by mancini77** [comment]
I wrote the following script to help write queries for Kafka_Connect for tables that have generic NUMBER columns, if you use connect in query mode you might find it useful. Just replace 
```
SET SERVEROUTPUT ON;
DECLARE
   Q1    VARCHAR2 (4000 CHAR);
   str   VARCHAR2 (300 CHAR);
BEGIN
   FOR rec
      IN (SELECT  column_name AS column_name
            FROM all_tab_cols
           WHERE     owner = 'YOURSCHEMA'
                 AND TABLE_NAME = 'YOURTABLE'
                 AND DATA_TYPE = 'NUMBER')
   LOOP
      q1 :=
         'SELECT    REPLACE(''cast( ''
             || :1
             || '' as  NUMBER(''
             || TO_CHAR (MAX (LENGTH_OF_DECIMAL) + MAX (length_of_integer))
             || '',''
             || TO_CHAR (MAX (length_of_decimal))
             || ''))'',''NUMBER(0,0)'',''NUMBER'') as result
        FROM (SELECT charnum,
                     CASE
                        WHEN INSTR (charnum, ''.'') > 0
                        THEN
                           SUBSTR (charnum, INSTR (charnum, ''.'') + 1)
                        ELSE
                           NULL
                     END
                        AS decimal_part,
                     CASE
                        WHEN INSTR (charnum, ''.'') > 0
                        THEN
                           REPLACE (
                              REPLACE (
                                 SUBSTR (charnum,
                                         1,
                                         INSTR (charnum, ''.'') - 1),
                                 ''-'',
                                 ''''),
                              ''+'',
                              '''')
                        ELSE
                           REPLACE (REPLACE (charnum, ''-'', ''''), ''+'', '''')
                     END
                        AS integer_part,
                     CASE
                        WHEN INSTR (charnum, ''.'') > 0
                        THEN
                           LENGTH (
                              SUBSTR (charnum, INSTR (charnum, ''.'') + 1))
                        ELSE
                           0
                     END
                        AS length_of_decimal,
                     CASE
                        WHEN INSTR (charnum, ''.'') > 0
                        THEN
                           NVL (
                              LENGTH (
                                 REPLACE (
                                    REPLACE (
                                       SUBSTR (charnum,
                                               1,
                                               INSTR (charnum, ''.'') - 1),
                                       ''-'',
                                       ''''),
                                    ''+'',
                                    '''')),
                              0)
                        ELSE
                           NVL (
                              LENGTH (
                                 REPLACE (REPLACE (charnum, ''-'', ''''),
                                          ''+'',
                                          '''')),
                              0)
                     END
                        AS length_of_integer
                FROM (SELECT cast(col_name2 AS VARCHAR2 (50))
                                AS charnum
                        FROM YOUR_TABLE)) T1';

      q1 := REPLACE (q1, 'col_name2', rec.column_name);

      EXECUTE IMMEDIATE REPLACE (q1, 'col_name2', rec.column_name)
         INTO str
         USING rec.column_name;

      DBMS_OUTPUT.PUT_LINE (str);
   END LOOP;
END;
/
```

**Comment by boristyukin** [comment]
still an issue with Oracle type NUMBER (no precision). I tried SMT cast transform with no luck as well
