### ISSUE TITLE
Error Code 500 upon confluent load jdbc

### ISSUE THREAD

**Issue by PiotrBB** [confluentinc/kafka-connect-jdbc#344]
Hello,

I just upgraded my Confluent platform to the newest (4.0.0) version. I'm trying to load my mssql connectors, which i used on 3.3.0 few days ago, but it seems like jdbc class cannot be found:
```
confluent list connectors
```

> Bundled Predefined Connectors (edit configuration under etc/):
>   elasticsearch-sink
>   file-source
>   file-sink
>   jdbc-source
>   jdbc-sink
>   hdfs-sink
>   s3-sink

```
confluent load jdbc-source
```

> {
>   "error_code": 500,
>   "message": "Failed to find any class that implements Connector and which name matches io.confluent.connect.jdbc.JdbcSourceConnector, available connectors are: PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector, name='org.apache.kafka.connect.file.FileStreamSinkConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSourceConnector, name='org.apache.kafka.connect.file.FileStreamSourceConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.MockConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}"
> }

I followed the exact steps available on confluent site, not sure why those classes are gone. Same with all connectors exceps file. I am able to load file-source and file-sink only.

**Comment by PiotrBB** [comment]
Figured it out. Using 3.3 config file, where plugin.path is commented by default broke connector list. You need to make sure that your `/etc/schema-registry/connect-avro-distributed.properties` has `plugin.path=/usr/share/java` not commented.

**Comment by wicknicks** [comment]
Closing this ticket. Please re-open if the fix doesn't work.
