### ISSUE TITLE
Connector Status exposes Password in Cleartext

### ISSUE THREAD

**Issue by Tang8330** [confluentinc/kafka-connect-jdbc#348]
In the Kafka-Connect REST API, we are able to see the MySQL password in plaintext. 
I'm not sure if there are any additional places where the PW is exposed.

It would be great if we can pass in a flag that encrypts it or leaves it out.

![image](https://user-images.githubusercontent.com/4412200/34839868-0129cbc6-f6b8-11e7-9c9b-0cead52fddef.png)

**Comment by rhauch** [comment]
This is already being tracked as [KAFKA-5117](https://issues.apache.org/jira/browse/KAFKA-5117), since it's an aspect the Connect framework
