### ISSUE TITLE
CORRUPT_MESSAGE w/ MySQL source and null key when setting key.converter at connector level

### ISSUE THREAD

**Issue by k1th** [confluentinc/kafka-connect-jdbc#357]
When sourcing data from MySQL with this config:

	  "name": "<xyz>",
	  "config": {
	    "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
	    "tasks.max": "1",
	    "connection.url": "jdbc:mysql://<xyz>?defaultFetchSize=1000&useCursorFetch=true&useSSL=false&jdbcCompliantTruncation=false&readOnly=true",
	    "connection.user": "<xyz>",
	    "connection.password": "<xyz>",
	    "table.whitelist": "<xyz>",
	    "mode": "timestamp",
	    "table.types": "VIEW",
	    "timestamp.column.name": "TRANSACTTS",
	    "topic.prefix": "<xyz>",
	    "key.converter": "org.apache.kafka.connect.converters.ByteArrayConverter",
	    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
	    "key.converter.schemas.enable": false,
	    "value.converter.schemas.enable": false,
	    "validate.non.null": false
	  }
	  
The data is a very simple table with a timestamp column.
  
We run into `CORRUPT_MESSSAGE` errors.
  
	kafka-connect_1  | [2018-02-13 13:29:50,429] WARN [Producer clientId=producer-10] Got error produce response with correlation id 5 on topic-partition tax-faxin-faxin_udr_source_201801-0, retrying (2147483644 attempts left). Error: CORRUPT_MESSAGE (org.apache.kafka.clients.producer.internals.Sender)

This happens with the ByteArraySerializer and the StringDeserializer as well (no difference)

When changing the connector to create a key using:

    "key.converter": "org.apache.kafka.connect.storage.StringConverter",

defining SMTs like this:

	"transforms": "ExtractKey,ExtractKeyValue",
	"transforms.ExtractKey.type": "org.apache.kafka.connect.transforms.ValueToKey",
	"transforms.ExtractKey.fields": "CUSTOMERNO",
	"transforms.ExtractKeyValue.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
	"transforms.ExtractKeyValue.field": "CUSTOMERNO"

the error disappears.

When removing the key.converter config, the error disappears as well. That doesn't seem very logical because the connector should fall back to the key.converter defined at the worker level (which in our case is JsonConverter)

We are using Kafka 1.0 and Connect with the 4.0.0 distribution in Docker (confluentinc/cp-kafka-connect:4.0.0) with mysql-connector-java-5.1.43-bin.jar

**Comment by gmyrianthous** [comment]
I had the same issue. Most probably, you've set retention policy to `compact` that requires a key and a value. Since a view does not have a key, the message is corrupted. Changing policy to `delete` has fixed the issue for me.
