### ISSUE TITLE
Have a configurable get current timestamp query

### ISSUE THREAD

**Issue by zevektor** [confluentinc/kafka-connect-jdbc#365]
When in the JDBC Source Connector the mode is set to timestamp, the implementation tries to query the database to get the current time. This logic is implemented [here](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/util/JdbcUtils.java#L244-L251).

The query needed to get the current time could have been implemented as a string read from the config properties, instead I can see that the authors took for granted that most of the databases get the current timestamp with the query

`SELECT CURRENT_TIMESTAMP`

or a small subset of very specific variations. 

On the database I'm querying, I can get the current time using
`SELECT NOW()`
and the hardcoded query basically makes impossible to use this connector. 

Is there any way to easily replace this query? Otherwise I'm a bit stuck because I'd have to rely on the bulk mode, which I'd like to avoid.

**Comment by zevektor** [comment]
Created #366 to add this feature

**Comment by rhauch** [comment]
This should be addressed already as part of #333, without requiring the user to configure the timestamp yet still supporting the different ways each DBMS supports getting the current time. WDYT?

**Comment by zevektor** [comment]
@rhauch your solution surely is cleaner and more elegant than mine, but for the most common use case it could be an overkill.

The current timestamp query is, most of the times, what really prevents the connector from working properly. When such problem occurs, a developer might only want to change this property instead of having to create an entire `DatabaseDialect` implementation for each of the most uncommon drivers.
