### ISSUE TITLE
jdbc-source-connect: sharding tables surpport

### ISSUE THREAD

**Issue by michaelhuang** [confluentinc/kafka-connect-jdbc#372]
hi, 

now the connector generates one task per table(or one task multiple tables), one topic per table;
but when importing sharding tables,  this is really a nightmare.

does the the connector generates only one topic with sharding tables, and splits the tasks depends on the numbers of sharding tables?

```
"connection": [
                           	{
	                          "jdbcUrl": ["jdbc:mysql://url.1"],
	                          "table": ["t_table_[000-049]"]
	                        },
	                        {
	                          "jdbcUrl": ["jdbc:mysql://url.2l"],
	                          "table": ["t_table_[050-099]"]
	                        }
                        ]
```

**Comment by rhauch** [comment]
Yes, the connector outputs all messages for a single table to a single topic. It's not practical for every connector that needs this kind of customized routing to handle it within the connector. So, the preferred approach for this any all connectors is to use [Connect's Single Message Transforms](https://kafka.apache.org/documentation/#connect_transforms) (either the `RegexRouter ` transform or a custom one if you need different logic) to reroute the messages for multiple topics into a smaller number of topics. Note if you need to do more than just modify the topic (e.g., add original table information to the message), you may need multiple transformations.

Hope this helps.

**Comment by michaelhuang** [comment]
Thank you so much for responding to my question. 

Perhaps it's an overkill to put transforms on this easy situation. 
I would like to implements a TableQuerier for handling it.
```
# job config
query: select * from tables:table_0,table_1

# build sql
select * from (select * from table_0 WHERE  MODIFY_TIME  > ? AND  MODIFY_TIME  < ?  union all select * from table_1 WHERE  MODIFY_TIME  > ? AND  MODIFY_TIME  < ? ) ORDER BY MODIFY_TIME ASC
```

It's really helpful to put Transforms on my other ETL progresses. 
Thanks again. ☺
