### ISSUE TITLE
Task is still running after connector is paused

### ISSUE THREAD

**Issue by michaelhuang** [confluentinc/kafka-connect-jdbc#374]
Hi,  

When the task gets no new records from mysql, it can not be paused.

> WorkerSourceTask doesn't know the connector is paused, it will know this only after leaving of poll() method. But by design pool() method should block if no data is currently available.

https://issues.jboss.org/browse/DBZ-516

Connector config:
```
topic.prefix=test_jdbc_
name=mysql-local-source
incrementing.column.name=id
table.whitelist=users
timestamp.column.name=modified
tasks.max=1
connection.url=jdbc:mysql://localhost:3306/oltp?user=hzf&password=hzf
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
mode=timestamp+incrementing
#task ids: 0
```

Connector status:
```
connectorState:  PAUSED
workerId: 127.0.0.1:8083
numberOfTasks: 1
tasks:
  - taskId: 0
    taskState: RUNNING
    workerId: 127.0.0.1:8083
```

Traceback:
```
[2018-03-01 16:31:21,439] INFO Connector mysql-local-source target state change (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1107)
[2018-03-01 16:31:21,440] INFO Setting connector mysql-local-source state to PAUSED (org.apache.kafka.connect.runtime.Worker:566)
[2018-03-01 16:31:21,440] INFO Stopping table monitoring thread (io.confluent.connect.jdbc.JdbcSourceConnector:166)
[2018-03-01 16:56:24,689] INFO 127.0.0.1 - - [01/Mar/2018:08:56:24 +0000] "GET /connectors/mysql-local-source/status HTTP/1.1" 200 171  3 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2018-03-01 16:57:00,709] INFO 127.0.0.1 - - [01/Mar/2018:08:57:00 +0000] "GET /connectors/mysql-local-source/status HTTP/1.1" 200 170  2 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2018-03-01 16:57:08,153] INFO WorkerSourceTask{id=mysql-local-source-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:306)
[2018-03-01 16:57:08,153] INFO WorkerSourceTask{id=mysql-local-source-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:323)
[2018-03-01 16:57:08,254] INFO WorkerSourceTask{id=mysql-local-source-0} Finished commitOffsets successfully in 101 ms (org.apache.kafka.connect.runtime.WorkerSourceTask:405)
```

After insert a record into mysql
```
connectorState:  PAUSED
workerId: 127.0.0.1:8083
numberOfTasks: 1
tasks:
  - taskId: 0
    taskState: PAUSED
    workerId: 127.0.0.1:8083
```

**Comment by michaelhuang** [comment]
why use continue here? 
Could we change it to `break`  to handle this question?

https://github.com/confluentinc/kafka-connect-jdbc/blob/d921388ce3401b29a776feb22296ce2300dfee5f/src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java#L218

**Comment by obohrer** [comment]
Had this issue as well. We are expecting the connector to be paused & not produce any more data once /pause has been called.

**Comment by brandonwittwer** [comment]
+1

**Comment by Schmidt96u** [comment]
i'm going to take a look on it

**Comment by Schmidt96u** [comment]
I took a look and I manage to reproduce your error when i put pause on my connector, the task was in pause.

It seem that @michaelhuang  was right the `continue` needed to be replace by `break`

```JSON
{"name":"JDBC_My_SQL","config":{"connector.class":"io.confluent.connect.jdbc.JdbcSourceConnector","mode":"bulk","incrementing.column.name":"id","topic.prefix":"JDBC_","connection.password":"mdp123","tasks.max":"2","connection.user":"Schmidt96u","name":"JDBC_My_SQL","topic":"testFinal","connection.url":"jdbc:mysql://127.0.0.1:3306/JDBCTEST","table.whitelist":"test"},"tasks":[{"connector":"JDBC_My_SQL","task":0}],"type":"source"}{"name":"JDBC_My_SQL","connector":{"state":"RUNNING","worker_id":"localhost:8083"},"tasks":[{"id":0,"state":"RUNNING","worker_id":"localhost:8083"}],"type":"source"}
```
after putting in pause : 
```JSON

{"name":"JDBC_My_SQL","config":{"connector.class":"io.confluent.connect.jdbc.JdbcSourceConnector","mode":"bulk","incrementing.column.name":"id","topic.prefix":"JDBC_","connection.password":"mdp123","tasks.max":"2","connection.user":"Schmidt96u","name":"JDBC_My_SQL","topic":"testFinal","connection.url":"jdbc:mysql://127.0.0.1:3306/JDBCTEST","table.whitelist":"test"},"tasks":[{"connector":"JDBC_My_SQL","task":0}],"type":"source"}{"name":"JDBC_My_SQL","connector":{"state":"PAUSED","worker_id":"localhost:8083"},"tasks":[{"id":0,"state":"PAUSED","worker_id":"localhost:8083"}],"type":"source"}

```

**Comment by Schmidt96u** [comment]
I just look a bit closer and it seems that the task is paused it self after a small amount of time due to :

https://github.com/confluentinc/kafka-connect-jdbc/blob/d921388ce3401b29a776feb22296ce2300dfee5f/src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java#L217

So i'm gooing to looking to try to "skip" this small delay when the /pause request is send

**Comment by Schmidt96u** [comment]
Okay the Pull request is working and the issue fix

**Comment by ChhatralaNirmal** [comment]
Hi @Schmidt96u - In which confluent connector version is this issue got fixed and available ? We are having this issue with Jdbcsource connector confluent 5.3.0

**Comment by cbmanikiran** [comment]
Hello,

I am facing this issue with Oracle , I’m using 5.4.0 
Can you please let me know which version has this fix ??

**Comment by cbmanikiran** [comment]
> Hi,
> 
> When the task gets no new records from mysql, it can not be paused.
> 
> > WorkerSourceTask doesn't know the connector is paused, it will know this only after leaving of poll() method. But by design pool() method should block if no data is currently available.
> 
> https://issues.jboss.org/browse/DBZ-516
> 
> Connector config:
> 
> ```
> topic.prefix=test_jdbc_
> name=mysql-local-source
> incrementing.column.name=id
> table.whitelist=users
> timestamp.column.name=modified
> tasks.max=1
> connection.url=jdbc:mysql://localhost:3306/oltp?user=hzf&password=hzf
> connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
> mode=timestamp+incrementing
> #task ids: 0
> ```
> 
> Connector status:
> 
> ```
> connectorState:  PAUSED
> workerId: 127.0.0.1:8083
> numberOfTasks: 1
> tasks:
>   - taskId: 0
>     taskState: RUNNING
>     workerId: 127.0.0.1:8083
> ```
> 
> Traceback:
> 
> ```
> [2018-03-01 16:31:21,439] INFO Connector mysql-local-source target state change (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1107)
> [2018-03-01 16:31:21,440] INFO Setting connector mysql-local-source state to PAUSED (org.apache.kafka.connect.runtime.Worker:566)
> [2018-03-01 16:31:21,440] INFO Stopping table monitoring thread (io.confluent.connect.jdbc.JdbcSourceConnector:166)
> [2018-03-01 16:56:24,689] INFO 127.0.0.1 - - [01/Mar/2018:08:56:24 +0000] "GET /connectors/mysql-local-source/status HTTP/1.1" 200 171  3 (org.apache.kafka.connect.runtime.rest.RestServer:60)
> [2018-03-01 16:57:00,709] INFO 127.0.0.1 - - [01/Mar/2018:08:57:00 +0000] "GET /connectors/mysql-local-source/status HTTP/1.1" 200 170  2 (org.apache.kafka.connect.runtime.rest.RestServer:60)
> [2018-03-01 16:57:08,153] INFO WorkerSourceTask{id=mysql-local-source-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:306)
> [2018-03-01 16:57:08,153] INFO WorkerSourceTask{id=mysql-local-source-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:323)
> [2018-03-01 16:57:08,254] INFO WorkerSourceTask{id=mysql-local-source-0} Finished commitOffsets successfully in 101 ms (org.apache.kafka.connect.runtime.WorkerSourceTask:405)
> ```
> 
> After insert a record into mysql
> 
> ```
> connectorState:  PAUSED
> workerId: 127.0.0.1:8083
> numberOfTasks: 1
> tasks:
>   - taskId: 0
>     taskState: PAUSED
>     workerId: 127.0.0.1:8083
> ```

Hello - can you please let me know which confluent version has this fix? I am facing similar issue with kafka jdbc source connector 5.4.0

**Comment by pantaoran** [comment]
I'm also observing this problem.
The PR from @Schmidt96u was never actually merged. It was closed without merging.
So questions about which releases contain the fix are meaningless.
Why did you give up on your PR @Schmidt96u ?

**Comment by jbruggem** [comment]
As mentioned above, this issue was closed by the following pull request:

https://github.com/confluentinc/kafka-connect-jdbc/pull/947
