### ISSUE TITLE
Python code to read kafka topic and store it into mysql database

### ISSUE THREAD

**Issue by sushantNaik** [confluentinc/kafka-connect-jdbc#390]

**Comment by sushantNaik** [comment]
If anyone has sample code please post

**Comment by jcustenborder** [comment]
@sushantNaik This project is written in Java against the Kafka Connect framework. It's used to read data from a Kafka topic and write it to a database, or read data from a database and write it to Kafka. Take a look at [confluent-kafka-python ](https://github.com/confluentinc/confluent-kafka-python) for a python library for interacting with Kafka.
