### ISSUE TITLE
Timeouts on Kafka connect after Kafka and connect (confluent 4.0.0) 

### ISSUE THREAD

**Issue by AkshathPatkar** [confluentinc/kafka-connect-jdbc#394]
Hi,

Not sure if this is issue or not. Let me brief about what we are seeing after upgrading (from confluent 3.2.0->confluent 4.0.0) brokers and Kafka connect.

We run Debezium in kafka connect. We recently upgraded to confluent 4.0.0 package on brokers and kafka-connect.

We started to see timeouts which committing offsets.

Here is some of the log messages
```
Failed to flush, timed out while waiting for producer to flush outstanding 174703 messages (org.apache.kafka.connect.runtime.WorkerSourceTask:328)
```

Kafka connect runs with `ACKS=-1` by default.

We tried possible options on kafka connect(producer configs).
`batch.size`=> No impact
`buffer.size`=> reduces the throughput and we are always lagging but timeouts are gone
`linger.ms`=> No impact
`offset.flush.timeout.ms`=> No impact.

What we are seeing us after offset timeouts and we see these network exceptions. Connector was able to flush all remaining messages and throughput spikes up in graph's
```
Got error produce response with correlation id 64933 on topic-partition ******-23, retrying (2147483646 attempts left). Error: NETWORK_EXCEPTION 
```

We tried even tuning brokers configs on `4.0.0`. 

`num.replica.fetchers` increased to 5. Still could not make any progress.

Tried to increase partition by 4x, still no improvement. we still see timeouts.

How ever if we change `acks=1` we don't see timeouts and we are not lagging at all. connector was able to keep up with database inserts.

we use 3 replicas. and acks=-1 on connectors. Even tried `min.insync.replicas=2` with `acks=-1`, still timeouts. 

After this we rolled back to `confluent 3.2.0` on brokers and KC as well. Looks like connector is happy running with same throughput. We don't see timeouts at all.

Is there some config we are missing?

**Comment by rhauch** [comment]
This appears to not have anything to do with the Confluent JDBC source or sink connector, but is instead a question that should be directed to the [Kafka mailing list](https://kafka.apache.org/contact) or the [Confluent discussion group](https://groups.google.com/forum/#!forum/confluent-platform).

**Comment by AkshathPatkar** [comment]
updated in discussion group 
https://groups.google.com/forum/#!topic/confluent-platform/mIoB9u1GyMw
