### ISSUE TITLE
Oracle JDBC Connector driver not found issue for connect distributed

### ISSUE THREAD

**Issue by ramvittal** [confluentinc/kafka-connect-jdbc#418]
When running Confluent 4.1.0 with connect distributed, the kafka jdbc connector is not finding the oracle JDBC driver even though it exists in the path.   However, when running the same configuration through connect standalone it works just fine.   Is this an issue with the software or my configuration. Any guidance will be appreciated.

The error I get is as follows when trying to load the connector:
bin/confluent load timesheet_utc -d ./etc/kafka-connect-jdbc/timesheet-utc.properties

{
    "error_code": 400,
    "message": "Connector configuration is invalid and contains the following 2 error(s):\nInvalid value java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:userxxx/passxxx@host.com:9999:test for configuration Couldn't open connection to jdbc:oracle:thin:userxxx/passxxx@host.com:9999:test\nInvalid value java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:userxxx/passxxx@host.com:9999:test for configuration Couldn't open connection to jdbc:oracle:thin:userxxx/passxxx@host.com:9999:test\nYou can also find the above list of errors at the endpoint `/{connectorType}/config/validate`"
}

**Comment by rhauch** [comment]
This happens when the driver is not located on the plugin path. Check the distributed worker configuration's `plugin.path`. To keep things simple, you should put the drivers into the `share/java/kafka-connect-jdbc` directory.

**Comment by ramvittal** [comment]
I did have the oracle driver on the plugin path of the host where I was trying to load the connect configuration.  But my connect cluster has more than one host.  I just came to know that the driver needs to be in the plugin path across all hosts that forms the connect cluster.  After I included the driver in plugin path on the other hosts this issue is resolved.  Please close this issue.

**Comment by kkonstantine** [comment]
Indeed @ramvittal , to this respect a jdbc driver is no different than the connector jar or any of its dependency jars. For licensing and also packaging reasons, it's not convenient for the connector to ship several jdbc drivers, but when installed in one node, they have to be installed in every node of the Connect cluster. 

Thanks, closing this issue.
