### ISSUE TITLE
Field type warning is of limited use and could be modified to include field name.

### ISSUE THREAD

**Issue by TSheahan** [confluentinc/kafka-connect-jdbc#421]
https://github.com/confluentinc/kafka-connect-jdbc/blob/a1a8360a11d855917e16d7ffc402adc25cf666ee/src/main/java/io/confluent/connect/jdbc/source/DataConverter.java#L104

Regarding this line,
It produces logs such as:
[2018-05-31 10:49:45,316] WARN JDBC type 1111 not currently supported (io.confluent.connect.jdbc.source.JdbcSourceTask:352)

I suggest that line 104 ought to be changed to something like:
`log.warn("JDBC type {} not currently supported for column {}", sqlType, fieldName);`

This would let users know the name of the field which is causing the unsupported type error to be thrown.

**Comment by rhauch** [comment]
Thanks, @TSheahan. Do you want to submit a PR for this simple change?
