### ISSUE TITLE
JDBC mysql connector is not working in case of special character in password

### ISSUE THREAD

**Issue by Chintanvpatel** [confluentinc/kafka-connect-jdbc#422]
Hello,

I'm using this connector to get the data from mysql database. But in case if we have **&** character in password, connector is giving validation error like

`"{"error_code":400,"message":"Connector configuration is invalid and contains the following 2 error(s):\nInvalid value java.sql.SQLException: Access denied for user 'XXXXX'@'XX.XXX.XXX.XXX' (using password: YES) for configuration Couldn't open connection to jdbc:mysql://XX.XXX.XXX.XXX:3306/db?user=username&password=!Pn@QK(he24&)OQ^o2\nInvalid value java.sql.SQLException: Access denied for user 'user'@'XX.XX.XXXX.XX (using password: YES) for configuration Couldn't open connection to jdbc:mysql://XX.XXX.XXX.XXX:3306/db?user=username&password=!Pn@QK(he24&)OQ^o2\nYou can also find the above list of errors at the endpoint `/{connectorType}/config/validate`"}"`

If I"ll remove "&" from password then It will work.

Regards,
Chintan Patel

**Comment by rhauch** [comment]
If you're putting the password in the URL, did you URL-encoded the password?

Better yet, use `connection.user` and `connection.password` configuration settings rather than adding the credentials to the `connection.url` property. This is a better because the `connection.password` value is masked when written to the Connect worker log, whereas the `connection.url` is not. Also, when you use this approach, the username and password are passed to the driver via the `Properties` object rather than being written to the URL.

**Comment by Chintanvpatel** [comment]
Hello @rhauch . I'm passing password in connection URL. Let me check with `connection.user` and `connection.password` options.
Thanks.

**Comment by Chintanvpatel** [comment]
Thanks @rhauch It worked.

**Comment by avinash0720** [comment]
hi @rhauch ,
I am also facing same issue. My password has special characters.
I am passing the password in 'connection.password', still I get the same error({"error_code":400,"message":"Connector configuration is invalid and contains the following 2 error(s):\nInvalid value java.sql.SQLException: Access denied for user **** @***** (using password: YES) for configuration Couldn't open connection to jdbc:mysql:/********.
Is there any other solution to this?
Thanks in advance.
regards, avinash

**Comment by avinash0720** [comment]
hi @rhauch,
I was able to resolve the issue by escaping the special characters in the password. So if the password is: g35fsc$43g, we should write is as:   g35fsc\$43g
