### ISSUE TITLE
Can table name replaced with custom name for topic name?

### ISSUE THREAD

**Issue by joshualouis911** [confluentinc/kafka-connect-jdbc#424]
Is it possible to replace the table name with custom name (related to function) for topic name. i.e. Prefix + Custom name instead of prefix+table name.

**Comment by rhauch** [comment]
The JDBC sink or source connector doesn't have a built-in capability to rename topics in records, but you can use Connect's built-in `RegexRouter` single message transform (SMT) to do this. See the [Kafka documentation](https://kafka.apache.org/documentation/#connect_transforms) or [Confluent's documentation](https://docs.confluent.io/current/connect/transforms/index.html) for details.

When used with the JDBC sink connector, it can change the topic names (if the regex pattern matches) of the records consumed from the topic _before_ the connector sees them, and thus the connector will use the records' new topic names to map to the tables.

When used with the JDBC source connector, it can change the topic names (if the regex pattern matches) of the records _produced_ by the source connector before they are written to Kafka, and Connect will use the records' topic names to determine to which Kafka topic they will be written.
