### ISSUE TITLE
Jar release?

### ISSUE THREAD

**Issue by simplesteph** [confluentinc/kafka-connect-jdbc#427]
Is it possible to have access to the connector JAR released without building the project or installing the whole confluent RPM? 

My hope would be that releases would be here: https://github.com/confluentinc/kafka-connect-jdbc/releases

**Comment by sshaginyan** [comment]
@simplesteph Have you tried creating the JAR from v5.0.0? I need the fixes that went into v5.0.0 asap :-(.

**Comment by rhauch** [comment]
We are publishing the latest releases to Confluent Hub (https://www.confluent.io/hub/). However, if you want to run something that hasn't yet been released, you need to build the code yourself.
