### ISSUE TITLE
unable to create jar of kafka-connect-jdbc 2.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by pradnyaalc** [confluentinc/kafka-connect-jdbc#43]
I am unable to create jar of  kafka-connect-jdbc 2.1.0-SNAPSHOT
When i run mvn clean install it throws the following error
C:\Users\E23228\Desktop\kafka-connect-jdbc-master>mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building kafka-connect-jdbc 2.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://nexus:8443/nexus/content/groups/public/io/confluent/common-config/2.1.0-SNAPSHOT/maven-metadata.xml
Downloading: https://nexus:8443/nexus/content/groups/public/io/confluent/common-config/2.1.0-SNAPSHOT/common-config-2.1.0-SNAPSHOT.pom
[WARNING] The POM for io.confluent:common-config:jar:2.1.0-SNAPSHOT is missing, no dependency information available
Downloading: https://nexus:8443/nexus/content/groups/public/io/confluent/common-config/2.1.0-SNAPSHOT/common-config-2.1.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.212s
[INFO] Finished at: Mon Feb 15 14:25:20 IST 2016
[INFO] Final Memory: 9M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project kafka-connect-jdbc: Could not resolve dependencies for project io.confluent:kafka-connect-jdbc:jar:2.1.0-SNAPSHOT: Could not find artifact io.confluent:common-config:jar:2.1.0-SNAPSHOT in NexusExternal (https://nexus:8443/nexus/content/groups/public) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

I am unable to find the io.confluence in maven repository too..

**Comment by ewencp** [comment]
@pradnyaalc This isn't a bug, this project just has dependencies. You'll need to build confluentinc/common (and make sure it's available in your local maven repo) to compile and run development versions of this repository.
