### ISSUE TITLE
Modifying kafka-connect-jdbc for sending data to broker 

### ISSUE THREAD

**Issue by labhane** [confluentinc/kafka-connect-jdbc#457]
Hi Team,

For a specific message inspection requirement, We have to introduce a component between kafka-jdbc-source-connect and broker to facilitate data inspection. While inspecting, the data should not be in byte array.  Would it be advisable to replace the push mechanism of kafka-jdbc-source-connect with a CustomRest Producer API call ..?

**Comment by cricket007** [comment]
Sounds like you want interceptors or transforms. 

https://www.confluent.io/kafka-summit-nyc17/single-message-transformations-not-transformations-youre-looking/inv/

**Comment by labhane** [comment]
Thanks @OneCricketeer 👍
