### ISSUE TITLE
Kafka connector is not pulling the data from PostgreSQL when mode is timestamp which is not in UTC format

### ISSUE THREAD

**Issue by chinnusujitha** [confluentinc/kafka-connect-jdbc#470]
By using Kafka connector, I'm unable to pull the data from PostgreSQL when mode = timestamp and the timestamp column in psql is in default timestamp. But when i change my timestamp field to 'UTC' format in my database schema, connector is pulling the data.

Due to some reasons i cannot change my database schema, So is there is any way to get the data from PostgreSQL with default timestamp.

**Comment by ussama-rafique** [comment]
Yes: Calculate how much time you are ahead of UTC in milliseconds and set it as negative value for "timestamp.delay.interval.ms" property in JDBC source connector properties.
For example, if your timezone is UTC+1, then 1 hour = 3600 s = 3600000 ms:
`"timestamp.delay.interval.ms": "-3600000"`
I have tested it only with version 5.0 and later

**Comment by gharris1727** [comment]
I believe the `db.timezone` config added in #505 should handle this use-case when the database is not UTC.
