### ISSUE TITLE
Using JdbcSinkConnector to do bulk writes to MS SQL

### ISSUE THREAD

**Issue by PawanMathur** [confluentinc/kafka-connect-jdbc#484]
Hi, current write modes are insert and upsert.
Is it possible to add mode such as "Bulk" where each input message in the Kafka topic will be a file, say a csv with multiple records that can be loaded to the target MS SQL or other database?

**Comment by rhauch** [comment]
Rather than change the connector to support this kind of input, it'd be much better to use stream processing to extract the multiple rows in a single record into multiple records. Then this connector could be used as-is.
