### ISSUE TITLE
Support for DB2 sink: upsert

### ISSUE THREAD

**Issue by sasa-tomic** [confluentinc/kafka-connect-jdbc#487]
I'd first like to thank you for providing the Kafka Connect framework, and for the DB2 sink skeleton in the latest release.
Jumping to the point of this issue, I've found a problem when the DB2 sink is used in the `upsert` mode - the syntax is incorrect.

I have a series of patches targeting DB2 sink, and another targeting the DB2 sink when IBM IIDR (https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/W8d78486eafb9_4a06_a482_7e7962f5ac59) is used as a CDC source for pushing avro data into a topic, capturing all table insert/update/delete operations.

I would like to ask if there is interest for opening PRs with the above changes?

**Comment by rhauch** [comment]
@sasa-tomic, we absolutely welcome improvements, fixes, and other changes.

(Closing this since it's a question.)
