### ISSUE TITLE
how to run two JDBC source connectors with different query but same output schema and push them to same kafka topic

### ISSUE THREAD

**Issue by lixiandai** [confluentinc/kafka-connect-jdbc#517]
Hi, 
Is that supported to create multiple JDBC source connectors which the queries are from different database view from sql server; however it has the same output schema for queries which i wish to dump to the same topic in kafka. 

Had anyone done this before and verify it works?

**Comment by avocader** [comment]
Hi @lixiandai ,

In this case, you would have multiple producers writing to the same topic.
Order of messages being produced will be not deterministic, but it's a totally valid use case, given order doesn't matter for your conditions, nothing prevents you from doing this.

Thanks.

**Comment by lixiandai** [comment]
@avocader yeah, both of my source should have a timestamp field which capture the lastUpdateDt, so i can still use to determine which record will need to go to sink. thanks for confirming that i could have two different source as long as they are schema identical so they can be pushed to same topic
