### ISSUE TITLE
Duplicates mysql data while running in distributed mode

### ISSUE THREAD

**Issue by AkshathPatkar** [confluentinc/kafka-connect-jdbc#52]
While running kafka jdbc connector in distributed connector in incrementing mode,
Connector keeps copying all data of the table every time it polls. 

Any reason this can happen? may be i am missing some thing with config here. Here is my connector config.

{
    "name": "mysql-test1",
    "config": {
    "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
    "tasks.max": "10",
    "connection.url": "<jdbc connection url>",
    "mode": "incrementing",
    "validate.non.null": "false",
    "table.whitelist": "test_table",
    "topic.prefix": "Newtest5-"
    }
}

Can you please suggest?

**Comment by ewencp** [comment]
@AkshathPatkar It looks like you haven't specified the column to track -- you need the `incrementing.column.name` setting. The fact that this isn't causing an error suggests we're missing some validation of configs.

**Comment by AkshathPatkar** [comment]
@ewencp Thanks, sorry for asking basic question 
Basically we want to replicate complete db, not for one table how do we specify for tat for all tables?

**Comment by criccomini** [comment]
@AkshathPatkar docs say it's for all tables. I think what we actually want is this:

https://github.com/confluentinc/kafka-connect-jdbc/issues/36

**Comment by criccomini** [comment]
@AkshathPatkar OK to close this one?

**Comment by AkshathPatkar** [comment]
@criccomini yup. This works with id. Thanks  closing this
