### ISSUE TITLE
Generic Database Dialect - checkConnectionQuery

### ISSUE THREAD

**Issue by rynocav226** [confluentinc/kafka-connect-jdbc#520]
The function checkConnectionQuery() in ../src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java issues a query of 'SELECT 1'.  The database I am using cannot handle this query; it returns an error so I cannot load a jdbc-source using this database.  Is there a jdbc-source property that can be set to override the query that is being issued by the checkConnectionQuery call?

**Comment by avocader** [comment]
Hi @rynocav226 ,

We don't have a configuration parameter to set which would override this query, but you have following options here:
• Use dialect which is already supported, which matches your DBMS
• If none of existing dialect matches your DBMS - create an issue with the request to support dialect for the desired DBMS, with providing more information about it. If you are willing to contribute it - that's very appreciated.

Thanks.
