### ISSUE TITLE
Data truncation: Incorrect datetime value: 'yyyy-MM-dd'T'HH:mm:ssZ' for timestamp column 

### ISSUE THREAD

**Issue by jiancaiHub** [confluentinc/kafka-connect-jdbc#522]
We used debezium as mysql source, and we use kafka-connect-jdbc as mysql sink to async data. And then it does not work properly. 

table structure
` `last_modified ` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,`
 

debezium config
```
 {
 "name": "mysql-source",
    "config": {
        "connector.class": "io.debezium.connector.mysql.MySqlConnector",
       
        "database.history.kafka.topic": "dbhistory.db",

        "include.schema.changes": "false",
        "table.whitelist": "rrc.cp_used_car",
        "mode": "incrementing",
        "incrementing.column.name": "car_id",
        
        "time.precision.mode": "connect",
        "database.serverTimezone": "Asia/Shanghai"
    }
}
```

kafka-connect-jdbc config

```
{
 "name": "mysql-sink",
 "config": {
 "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
 "tasks.max": "1",
 "topics": "mysql.db.test",
 "connection.url": "jdbc:mysql://localhost:3306/db??useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull",

 "transforms": "unwrap", 
 "transforms.unwrap.type": "io.debezium.transforms.UnwrapFromEnvelope",

 "auto.create": "false", 
 "insert.mode": "upsert",
 "pk.fields":"car_id",
 "pk.mode":"record_value",
 "dialect.name": "MySqlDatabaseDialect"
 }
}
```

connect log output
> [2018-11-08 17:23:24,301] ERROR WorkerSinkTask{id=cp_used_car-jdbc-mysql-sink-sandbox-0} RetriableException from SinkTask: (org.apache.kafka.connect.runtime.WorkerSinkTask:577)
> org.apache.kafka.connect.errors.RetriableException: java.sql.SQLException: java.sql.BatchUpdateException: Data truncation: Incorrect datetime value: '2017-10-25T03:29:48Z' for column 'last_modified' at row 1
> com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '2017-10-25T03:29:48Z' for column 'last_modified' at row 1
> 
> 	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:94)
> 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
> 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
> 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
> 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
> 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
> 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.sql.SQLException: java.sql.BatchUpdateException: Data truncation: Incorrect datetime value: '2017-10-25T03:29:48Z' for column 'last_modified' at row 1
> com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '2017-10-25T03:29:48Z' for column 'last_modified' at row 1

**Comment by keith-leung** [comment]
@jiancaiHub How to solve this problem? I ran into a similar problem.

**Comment by jiancaiHub** [comment]
@keith-leung  we write a transform to convert timestamp. Convert the given timestamp to the target timestamp format.

**Comment by ravishankar456** [comment]
Could you please share how to convert one timestamp format to other. Format yyyy-MM-dd'T'HH:mm:ssZ doesnt seem to be recognised

**Comment by Peng-666** [comment]
@jiancaiHub Could you please share how to solve this problem? thanks

**Comment by rotem-ad** [comment]
I had a similar issue and adding this TimestampConverter SMT to the MySQL JDBC sink connector config did the trick:

```
"transforms": "TimestampConverter",
"transforms.TimestampConverter.type": "org.apache.kafka.connect.transforms.TimestampConverter$Value",
"transforms.TimestampConverter.format": "yyyy-MM-dd'T'HH:mm:ss'Z'",
"transforms.TimestampConverter.target.type": "Timestamp",
"transforms.TimestampConverter.field": "my_timestamp_field"
```

HTH
