### ISSUE TITLE
add initial timestamp as the start point of the sync dataset

### ISSUE THREAD

**Issue by fzucxl** [confluentinc/kafka-connect-jdbc#526]
In some use case, we need to sync data start with a time point instead of all the data of a table, so,add initial timestamp as the start point of the sync dataset is usefull.

Can you add it in a futrue version? or this function has exist in a current branch version?

**Comment by cricket007** [comment]
Link #370

**Comment by cricket007** [comment]
Link #441

**Comment by gharris1727** [comment]
This has been implemented by #429 and will appear in the next release.
