### ISSUE TITLE
Problem in loading JDBC source connector while using distributed mode.

### ISSUE THREAD

**Issue by II-VSB-II** [confluentinc/kafka-connect-jdbc#537]
Hi Team,
I have 3 brokers running in 3 different machine. I have started distributed connector using this command.
`sudo ./connect-distributed /etc/kafka/connect-distributed.properties`
In file connect-distributed.properties I have updated the bootstrap servers ip accordingly.
and plugin path` /usr/share/java`
Should I need to update the rest.host and rest.port in  connect-distributed.properties ? My REST Proxy is running on different node.?
But when I am trying to load a connector with the Json file.
JSON File Content:
```
{ 
"name": "quickstart-jdbc-source", 
"config": { 
"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector", 
"tasks.max": 1, 
"connection.url": "jdbc:mysql://IPADDRESS:3306/employee?user=bluedata&password=admin@123", "mode": "incrementing", 
"incrementing.column.name": "empid",
 "query": "select * from emp_data",
"topic.prefix": "quickstart-jdbc-", 
"value.converter": "org.apache.kafka.connect.json.JsonConverter",
"key.converter": "org.apache.kafka.connect.json.JsonConverter",
"poll.interval.ms": "5000",
"table.poll.interval.ms": "120000" 
} 
}
```

Command to load JDBC Connector:
`curl -s -X POST -H "Content-Type: application/json" --data @jdbc.json http://REST_IPADDRESS:8083/connectors
`
Error:
`{"error_code":400,
"message":"Connector configuration is invalid and contains the following 2 error(s):\nInvalid value java.sql.SQLException: No suitable driver found for jdbc:mysql://MYSQLSERVER:3306/employee?user=bluedata&password=admin@123 for configuration Couldn't open connection to jdbc:mysql://MYSQLSERVER:3306/employee?user=bluedata&password=admin@123\nInvalid value java.sql.SQLException: No suitable driver found for jdbc:mysql://MYSQLSERVER:3306/employee?user=bluedata&password=admin@123 for configuration Couldn't open connection to jdbc:mysql://MYSQLSERVER:3306/employee?user=bluedata&password=admin@123\nYou can also find the above list of errors at the endpoint /{connectorType}/config/validate"}`

I am able to login to my database remotely. I try all possible solution suggested by you guys but not able to resolve.
@cricket007

**Comment by cricket007** [comment]
Have you tried searching for the error `No suitable driver found` and found what it means and what you need to do for it?

**Comment by cricket007** [comment]
@gopalakrishnan-subramani 

I do not understand this output

```
root@ubuntu-16gb-nbg1-1:~# ls /usr/share/java/kafka-connect-jdbc/ -l
total 2940
-rw-r--r-- 1 root root 1002812 Dec  5 20:08 mysql-connector-java-5.1.45.jar
-rw-r--r-- 1 root root 1002812 Dec  5 20:08 mysql-connector-java.jar
-rw-r--r-- 1 root root 1002812 Dec  5 20:08 mysql.jar
```

1. Why are there 3 JAR files?
2. Where are the _rest of `kafka-connect-jdbc` dependencies_?

**Comment by cricket007** [comment]
If you download the **tar.gz** file, then extracted it, to `~/Downloads/confluent-5.0.1`, for example

Then, run `echo "$HOME/Downloads/confluent-5.0.1/share/java/kafka-connect-jdbc"` and set `plugin.path` to **that** after you put the right JARs there (you should already see Postgres and SQLite in that folder)

**Comment by gopalakrishnan-subramani** [comment]
@cricket007 

Thank you so much, it worked after I kept the files in confluent-5.0.1/share/java/kafka-connect-jdbc locations. Initially I tried ubuntu  ubuntu package, it kept the files in /usr/share/java/ setting path had issues. After downloading the jar keeping them in confluent-5.0.1/share/java/kafka-connect-jdbc, it worked fine. thank you.

**Comment by cricket007** [comment]
The deb packages should work fine, but then again, I've personally only been running Confluent on CentOS boxes

**Comment by cricket007** [comment]
> Now I not getting where to start distributed connector?

You already have it...

> **Kafka_Connect**---192.168.0.3

You would HTTP Post to that server, your JDBC configuration JSON, for example. 

> what will I need to modify in the connect-distributed.properties.

Well, at the very least everything with `@@@@` in the file you've shown. 

If the documentaion for Kafka Connect in unclear on the Apache Kafka site, please open a JIRA.

**Comment by N-NicK** [comment]
Hi @cricket007,
You mean to say,
I have start the  connect-distributed script with the properties file in Kafka_Connect---192.168.0.3 server and load the connector using the REST POST call.?

**Comment by cricket007** [comment]
Yes.

If the documentation is unclear, please open an issue using the feedback links at the bottom of the page. - https://docs.confluent.io/current/connect/userguide.html#distributed-mode

**Comment by N-NicK** [comment]
Hi @cricket007,
1 last question.
Why only 1 task is running for the below Json.?
I have 3 worker nodes (Kafka_Connect)
JDBC Json:
```
{
"name": "mysql-jdbc-source",
"config": {"connector.class":"io.confluent.connect.jdbc.JdbcSourceConnector","incrementing.column.name":"empid","tasks.max":"3","query":"select emp_data.empid,emp_data.name from emp_data","table.poll.interval.ms":"120000","mode":"incrementing","topic.prefix":"quickstart-jdbc-","poll.interval.ms":"5000","connection.url":"jdbc:mysql://192.168.0.16:3306/employee?user=bluedata&password=admin@123","value.converter":"org.apache.kafka.connect.json.JsonConverter","key.converter":"org.apache.kafka.connect.json.JsonConverter"}}
```

I read somewhere for one table only one task is created. Is it correct?

**Comment by cricket007** [comment]
I do not know. 

>  read somewhere for one table only one task is created. Is it correct?

Makes sense for me. You cannot coordinate more than one JDBC call and not have duplicate records. 

Tasks does not need to map exactly to number of nodes, by the way. Think of tasks as threads, and you can have lots of threads on one single machine

**Comment by NathanNam** [comment]
@II-VSB-II Please re-open this thread if you still face the issue.
