### ISSUE TITLE
Can not set multiple timestamp columns

### ISSUE THREAD

**Issue by shenzhun** [confluentinc/kafka-connect-jdbc#56]
Hi,

I try to use Kafka Connect to dump mysql data to Kafka, but I found that timestamp.column.name only accept one column, but in my case, I have three columns, no matter which one modified, new data will be updated to Kafka.

**Comment by imrenagi** [comment]
Is there any progress on this issue @shenzhun ? I'm facing the similar problem.

**Comment by shenzhun** [comment]
@imrenagi no progress so far.

**Comment by wicknicks** [comment]
This feature was implemented and released with `v5.0.0`.
