### ISSUE TITLE
connect-dsitributed process dies if null value goes into incrementing.column.name is null

### ISSUE THREAD

**Issue by joshivinay** [confluentinc/kafka-connect-jdbc#57]
I have been trying to use the connect-distributed service and it dies for pretty much any error / boundary condition. It dies if 
- the incrementing.column.name is null, 
- if the timestamp.column.name is null, 
- if the topic.prefix is not set
- if incrementing.column.name and timestamp.column.name are both set. 

The only way to recover is to delete / flush the connect-configs topic. I am building an app to automatically create these connectors, and the service keeps dying on me.

**Comment by gwenshap** [comment]
Just to make sure I understand, you'd prefer it if the connector would stay alive (but at error state) and keep checking for new configuration?

**Comment by joshivinay** [comment]
Yup,
Otherwise, we would need to restart "connect-distributed" each time an error occurs even while setting up / adding a connector. If there is stronger error checking with the REST API, recovering and taking corrective actions would be possible. The standard HTTP codes for REST errors could be sent back to let the app developer know that the call has failed. I hope that makes sense

**Comment by Ishiihara** [comment]
@joshivinay Thanks for reporting this issue. We made some improvements of Kafka Connect in CP 3.0 release that supports status tracking of connector and tasks. In case that a connector is not correctly initialized and started, the connector will transit to `FAILED` state, however, the exceptions during connector start are properly caught. As a result, the Worker is not crashed  you should be able to reconfigure the connector with correct configurations. 

CP 3.0 also provides REST API report status of connectors and tasks. You should be able to use that API to inform the App of the connector status.

**Comment by joshivinay** [comment]
Okay,
We will check it out with the CP 3.0 release.

Thanks
Vinay Joshi
*Kwartile, Inc.*
Email: vinay.joshi@kwartile.com <vinay.joshi@javelintools.com>

**Comment by shikhar** [comment]
Connect in distributed mode should not crash if a connector fails. There were improvements in 3.0 that @Ishiihara mentioned. In 3.1, there are further robustness improvements with https://issues.apache.org/jira/browse/KAFKA-4042.
