### ISSUE TITLE
Jdbc sink date type convert exception

### ISSUE THREAD

**Issue by fzucxl** [confluentinc/kafka-connect-jdbc#577]
I am use kafka connect to move data from oracle to mysql  automaticlly. Source is oracle , Sink is mysql.   In auto create table step I run into an error with date type convert.  The generated sql is CREATE TABLE `table` (
	`IS_COUPON` VARCHAR ( 256 ) NULL,
	`CODE` VARCHAR ( 256 ) NOT NULL,
	`STATUS` VARCHAR ( 256 ) NOT NULL,
	`PM_TYPE` VARCHAR ( 256 ) NOT NULL,
	`IS_BANK_CARD` VARCHAR ( 256 ) NULL,
	`MODIFY_DATE` DATETIME ( 3 ) NULL,
	`IS_POINT` VARCHAR ( 256 ) NULL,
	`PCODE` VARCHAR ( 256 ) NOT NULL,
	`IS_WB` VARCHAR ( 256 ) NULL,
	`NAME` VARCHAR ( 256 ) NOT NULL,
`IS_3RD` VARCHAR ( 256 ) NULL 
);   the error is MODIFY_DATE type.

**Comment by rhauch** [comment]
@fzucxl, you be more specific and include the actual error found in the log, your source and sink connector configurations, and information about which versions of Kafka Connect and the JDBC connector you're using? It'd also be helpful to have the Oracle DDL for the table, and the MySQL DDL you might expect if you were to do it by hand.

**Comment by fzucxl** [comment]
@rhauch, 
Kafka Connect Jdbc version  5.1.0
source and sink configurations:
echo '{"name":"kafka-demo2-source","config":{"connector.class":"JdbcSourceConnector","connection.url":"jdbc:mysql://ip:3306/test?user=xxxx&password=xxxx","mode":"timestamp","table.whitelist":"kafka_demo2","validate.non.null":false,"timestamp.column.name":"create_time","topic.prefix":""}}' | curl -X POST -d @- http://ip:port/connectors --header "Content-Type:application/json"
echo '{"name":"kafka-demo2-sink","config":{"connector.class":"JdbcSinkConnector","connection.url":"jdbc:mysql://ip:3306/test-kafka?user=xxxx&password=xxxx","topics":"kafka_demo2","tasks.max":1, "auto.create": "true"}}' | curl -X POST -d @- http://ip:8083/connectors --header "Content-Type:application/json"

source table ddl:
CREATE TABLE `kafka_demo2` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '名',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='kafka测试';



error log:
[2019-01-24 10:45:11,340] INFO Using MySql dialect table "kafka_demo2" absent (io.confluent.connect.jdbc.dialect.MySqlDatabaseDialect:498)
[2019-01-24 10:45:11,342] INFO Creating table with sql: CREATE TABLE `kafka_demo2` (
`create_time` DATETIME(3) NOT NULL,
`name` VARCHAR(256) NOT NULL,
`id` INT NOT NULL) (io.confluent.connect.jdbc.sink.DbStructure:91)
[2019-01-24 10:45:11,352] WARN Create failed, will attempt amend if table already exists (io.confluent.connect.jdbc.sink.DbStructure:62)
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(3) NOT NULL,
`name` VARCHAR(256) NOT NULL,
`id` INT NOT NULL)' at line 2
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

**Comment by fzucxl** [comment]
@rhauch, in th generated ddl, replace DATETIME(3) to DATETIME,  the ddl can execute without error.

the kafka connect jdbc source code in class MySqlDatabaseDialect is 
@Override
  protected String getSqlType(SinkRecordField field) {
    if (field.schemaName() != null) {
      switch (field.schemaName()) {
        case Decimal.LOGICAL_NAME:
          // Maximum precision supported by MySQL is 65
          int scale = Integer.parseInt(field.schemaParameters().get(Decimal.SCALE_FIELD));
          return "DECIMAL(65," + scale + ")";
        case Date.LOGICAL_NAME:
          return "DATE";
        case Time.LOGICAL_NAME:
          return "TIME(3)";
        case Timestamp.LOGICAL_NAME:
          return "DATETIME(3)";
        default:
          // pass through to primitive types
      }
    }

**Comment by fzucxl** [comment]
I solved this problem by update mysql version to 5.6 from 5.5.
