### ISSUE TITLE
Unable to read Oracle View from kafka jdbc

### ISSUE THREAD

**Issue by NetCoder99** [confluentinc/kafka-connect-jdbc#584]
Using Confluent 5.1.0 against Oracle 10g with the OJDBC6.JAR.

I can read an Oracle table using kafka-connect-jdbc and the following oracle-table.properties file ...
`name            = oracle-jdbc-enty-address`
`connector.class = io.confluent.connect.jdbc.JdbcSourceConnector`
`tasks.max       = 1`
`connection.url        = jdbc:oracle:thin:@mtoracle.sercer.com:1521/ORCL1`
`connection.user       = scott `
`connection.password   = scottpa` 
`table.whitelist       = TEST_KAFKA`
`mode                  = timestamp` 
`timestamp.column.name = UPDATE_TIMESTAMP`
`validate.non.null     = false`
`topic.prefix=oracle-jdbc-`

I can create a view in ORCL, same database, same schema, using this ... 
`create view VW_TEST_KAFKA as select * from TEST_KAFKA; `

But when I try to read from the view using this properties file 
`name            = oracle-jdbc-enty-address`
`connector.class = io.confluent.connect.jdbc.JdbcSourceConnector`
`tasks.max       = 1`
`connection.url        = jdbc:oracle:thin:@mtoracle.sercer.com:1521/ORCL1`
`connection.user       = scott `
`connection.password   = scottpass `
`table.whitelist       = VW_TEST_KAFKA`
`mode                  = timestamp `
`timestamp.column.name = UPDATE_TIMESTAMP`
`validate.non.null     = false`
`topic.prefix=oracle-jdbc-`

I get this error ...
`java.lang.IllegalArgumentException: Number of groups must be positive.`

Is this a known bug?

Has anyone gotten kafka-connect-jdbc to read from an Oracle view? If so can you provide the properties that you used?

**Comment by fzucxl** [comment]
add the table.types = "VIEW" for souce connector config and it will works normal.

**Comment by NetCoder99** [comment]
Thanks for help, but no luck. I can see from the logs that it is picking up on the new parameter but the connector still fails with the 'number of groups must be positive' error.  I will probably just switch over to a pure Java process.

**Comment by rmoff** [comment]
As @fzucxl said, you need to tell Kafka Connect to include VIEWs in the list of objects that it will ingest. If you're still getting the (somewhat ambiguous) `number of groups must be positive` error then it is going to be either the view name qualifier or permissions on it. If you run the connector without the `table.whitelist` setting it will ingest all objects that it has access to, and then you can see whether it is picking it up with a different name (e..g qualified schema/owner), or if your user doesn't have permissions to read from it.

**Comment by rmoff** [comment]
Closing for now. Please reopen if this is still an issue.
