### ISSUE TITLE
how to use TimestampConverter

### ISSUE THREAD

**Issue by fzucxl** [confluentinc/kafka-connect-jdbc#587]
Hello, my source connector is a table from oracle, sink connector is mysql. But the MODIFY_DATE filed value in mysql is  not equal to oracle , And mysql time fall behind 8h compare with oracle. The oracle dbtimezone is '+0:00', sessiontimezone is '+8:00', how to solve this problem? Can I use the TimestampConverter to convert the MODIFY_DATE filed? and I don't konw how to use TimestampConverter.

**Comment by rmoff** [comment]
Just to clarify: you have a timestamp field in Oracle, and in MySQL, and when it's streamed to MySQL the value lags by 8 hours? Have I understood correctly?

**Comment by fzucxl** [comment]
> Just to clarify: you have a timestamp field in Oracle, and in MySQL, and when it's streamed to MySQL the value lags by 8 hours? Have I understood correctly?
Yes, the timestamp filed stream to mysql from oracle and it's value lags by 8 hours.
I solved this problem by compile the source code to kafka-connect-jdbc-5.2.0-SNAPSHOT.jar and set db.timezone to 'Asia/Shanghai'.
The default UTC time in current realease version(5.1.0)

**Comment by rmoff** [comment]
If timestamp datatypes are handled correctly, and your timezones are set
correctly on both databases, I don't see why this is necessary.

**Comment by fzucxl** [comment]
Yes,do not need TimestampConverter actrully,Using 5.2.0 and timezone can solve it.
I ask this question  because I don not know how to do before I solving it.
