### ISSUE TITLE
Kafka jdbc connector: No suitable driver found for jdbc:mysql

### ISSUE THREAD

**Issue by venkrishy** [confluentinc/kafka-connect-jdbc#600]
I am trying this in my mac.  Trying to create jdbc source connector (confluent 5.1) and getting errors "No suitable driver..." but I do have the connector jar.  I have placed mysql-connector-java-8.0.13.jar under /usr/share/java/,  /usr/share/java/kafka and  /usr/share/java/kafka-connect-jdbc.  I also tried placing this file under <confluent-dir>/share/java/kafka-connect-jdbc/.  No luck.

In the confluent directory, I execute this command:
confluent load mysql-bulk-source -d etc/kafka-connect-jdbc/source-mysql-bulk-source.properties 

This is my source properties file etc/kafka-connect-jdbc/source-mysql-bulk-source.properties :
name=mysql-bulk-source
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=10
connection.url=jdbc:mysql://<ipaddress>/<db>
connection.user=xxx
connection.password=xxx
mode=bulk
topic.prefix=mysql-

And this is the error I get:
{
  "error_code": 400,
  "message": "Connector configuration is invalid and contains the following 2 error(s):\nInvalid value java.sql.SQLException: No suitable driver found for jdbc:mysql://<ip>/<db> for configuration Couldn't open connection to  jdbc:mysql://<ip>/<db>\nInvalid value java.sql.SQLException: No suitable driver found for  jdbc:mysql://<ip>/<db> for configuration Couldn't open connection to  jdbc:mysql://<ip>/<db>\nYou can also find the above list of errors at the endpoint `/{connectorType}/config/validate`"
}

**Comment by samwal** [comment]
@venkrishy  - Did you find a fix for this? I am running into this exact issue and would like to know how you fixed it.

**Comment by vvaidya-trimble** [comment]
Try this: https://www.confluent.io/blog/kafka-connect-deep-dive-jdbc-source-connector

**Comment by lloyd-e-j-williams** [comment]
I also had this problem but I also added the mysql-connector-java-8.0.13.jar file to: 
confluent-5.4.1/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib
and it started working.

**Comment by m4nuC** [comment]
@lloyd-e-j-williams Worked for me too. Thanks!

**Comment by kamran-sultan** [comment]
I also added the 
mysql-connector-java-8.0.13.jar file to:
confluent-5.4.1/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib
but i still have the same issue. Any suppot please

**Comment by bnymnsntrk** [comment]
I've added it to /kafka/confluent-5.4.1/share/java/kafka/ and looks like it's working for now.

**Comment by quangbilly79** [comment]
I've added it to /kafka/confluent-5.0.0/share/java/kafka/ too and looks like it's working for now too
