### ISSUE TITLE
Primary key not being used for kafka key

### ISSUE THREAD

**Issue by gfodor** [confluentinc/kafka-connect-jdbc#62]
As far as I can tell, there is no key being used for the records being inserted into Kafka when using this connector. This seems problematic for a number of reasons, one being that log compaction is not going to work in the natural way where a single database row's changes will be compacted. I have a PR together that adds support for checking the primary key of the table and using the value of that column as the key for the records, but wanted to see if I was missing something.

**Comment by ewencp** [comment]
@gfodor No, you're not missing anything. See also #28

**Comment by gfodor** [comment]
Great. I'll see if I can get my PR in good shape. The catch is that I'm working with PostgreSQL so I've also pulled in some stuff to fix the boolean column issues.
