### ISSUE TITLE
JDBC connector running with Kafka TLS failing to push messages to brokers.

### ISSUE THREAD

**Issue by AkshathPatkar** [confluentinc/kafka-connect-jdbc#63]
Hi,

When try to run JDBC connector with kafka TLS ports, it starts failing. How ever it does create a config and Offset topics. Unable to put message to database table topic.

ERROR Failed to flush WorkerSourceTask{id=******}, timed out while waiting for producer to flush outstanding messages, 1 left ({ProducerRecord(topic=Newtest-zip, partition=null, key=null, value=[B@6232c19=ProducerRecord(topic=Newtest-zip, partition=null, key=null, value=[B@6232c19}) (org.apache.kafka.connect.runtime.WorkerSourceTask:237)

Let us know if i am missing any thing here.

**Comment by AkshathPatkar** [comment]
Hi,

When try to run JDBC connector with kafka TLS ports, it starts failing. How ever it does create a config and Offset topics. Unable to put message to database table topic.


ERROR Failed to flush WorkerSourceTask{id=******}, timed out while waiting for producer to flush outstanding messages, 1 left ({ProducerRecord(topic=Newtest-zip, partition=null, key=null, value=[B@6232c196=ProducerRecord(topic=Newtest-zip, partition=null, key=null, value=[B@6232c196}) (org.apache.kafka.connect.runtime.WorkerSourceTask:237)

Let us know if i am missing any thing here.

**Comment by ewencp** [comment]
@AkshathPatkar Currently, configuring for secure access is a little bit annoying. We separate out the configs for Connect, the internal producers, and internal consumers into [different namespaces](http://docs.confluent.io/2.0.1/connect/userguide.html#overriding-producer-consumer-settings) in the configs. This allows you to specify different configs for the different parts of the system if necessary, but does come at the cost of having to duplicate some configs if they are the same for all of these components.

You probably just need to duplicate your security settings with `producer.` and `consumer.` prefixes. For example, if you had the following in your worker config already:

```
security.protocol=SSL
ssl.truststore.location=/var/private/ssl/kafka.client.truststore.jks
ssl.truststore.password=test1234
```

you would need to also add

```
producer.security.protocol=SSL
producer.ssl.truststore.location=/var/private/ssl/kafka.client.truststore.jks
producer.ssl.truststore.password=test1234
consumer.security.protocol=SSL
consumer.ssl.truststore.location=/var/private/ssl/kafka.client.truststore.jks
consumer.ssl.truststore.password=test1234
```

**Comment by AkshathPatkar** [comment]
@ewencp Awesome, ya this worked. Thanks for the Info.
