### ISSUE TITLE
kafka-connect not working with Oracle JDBC timeout error

### ISSUE THREAD

**Issue by dazzyrock** [confluentinc/kafka-connect-jdbc#644]
Kafka connect for jdbc is getting timeout error despite increasing timeout values.

curl -X POST http://localhost:8083/connectors -H "Content-Type: application/json" -d '{
        "name": "jdbc_source_oracle_01",
        "config": {
                "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
                "connection.url": "jdbc:oracle:thin:@localhost1521:XE","connection.user": "mylocal",
                "connection.password": "mylocal",
                "topic.prefix": "product",
                "mode":"bulk",
                "poll.interval.ms" : 3600000,
                "table.whitelist" : "products"
                }
        }'

No exception getting printed in Connect log
sudo ./confluent log connect

Please note I have running jdbc connector for mysql in the same system which works perfectly fine.
oracle service is also up
sqldeveloper can connect the same instance.
OJDBC drivers are also in the class path.

Any help is much appreciated.

**Comment by aliasbadwolf** [comment]
@dazzyrock if this is the exact JSON you are using to submit your connector then you might want to add a COLON after "localhost" in "connection.url" 

"connection.url": "jdbc:oracle:thin:@localhost:1521:XE"

Also, this URL is correct assuming "XE" is the SID. If XE is the **service name** then use the following 
"connection.url": "jdbc:oracle:thin:@localhost:1521/XE"

**Comment by kkonstantine** [comment]
Sounds like this was a configuration issue. Closing but feel free to reopen if this was not the case.
