### ISSUE TITLE
ON CONFLICT ("id") DO UPDATE > SET  was aborted: ERROR: syntax error at end

### ISSUE THREAD

**Issue by alibaltschun** [confluentinc/kafka-connect-jdbc#645]
i have an issue about jdbc-sink with this arch.

> postgres1 ---> kafka ---> postgres2

the producer working fine, but the consumer has an error :

> connect_1    | org.apache.kafka.connect.errors.RetriableException:
> java.sql.SQLException: java.sql.BatchUpdateException: Batch entry 0
> INSERT INTO "customers" ("id") VALUES (1) ON CONFLICT ("id") DO UPDATE
> SET  was aborted: ERROR: syntax error at end of input connect_1    |  
> Position: 77  Call getNextException to see other errors in the batch.

this is my source.json

    {
    "name": "src-table",
    "config": {
        "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
        "tasks.max": "1",
        "database.hostname": "postgres1_container",
        "database.port": "5432",
        "database.user": "postgres",
        "database.password": "postgres",
        "database.dbname": "postgres",
        "database.whitelist": "postgres",
        "database.server.name": "postgres1",
        "database.history.kafka.bootstrap.servers": "kafka:9092",
        "database.history.kafka.topic": "schema-changes.inventory",
        "transforms": "route",
        "transforms.route.type": "org.apache.kafka.connect.transforms.RegexRouter",
        "transforms.route.regex": "([^.]+)\\.([^.]+)\\.([^.]+)",
        "transforms.route.replacement": "$3"
    }

and this my jdbc-sink.json

    {
        "name": "jdbc-sink",
        "config": {
            "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
            "tasks.max": "1",
            "topics": "customers",
            "connection.url": "jdbc:postgresql://postgres2_container:5432/postgres?user=postgres&password=postgres",
            "transforms": "unwrap",
            "transforms.unwrap.type": "io.debezium.transforms.UnwrapFromEnvelope",
            "auto.create": "true",
            "insert.mode": "upsert",
            "pk.fields": "id",
            "pk.mode": "record_value"
        }
    }

debezium/zookeeper : 0.9

debezium/kafka:0.9

debezium/postgres:9.6

debezium/connect:0.9

PostgreSQL JDBC Driver 42.2.5

Kafka Connect JDBC 5.2.1

i tried to downgrade jdbc driver and confluent kafka connect but still have the same error

**Comment by alibaltschun** [comment]
solve, the problem coz while i create table for postgres1, the id column not set to a PK value

**Comment by dungnt081191** [comment]
@alibaltschun I'm at your situation. Same issue. But my table in DB source is already set primary key. Could you take a look for me.

my flow is : Postgress 12 --> Debezium connect source --> Kafka --> Connect sink jdbc --> Postgres 12

My db table have key `Id` with type `bigint`
 
My source connector config: 
```
name=connector
connector.class=io.debezium.connector.postgresql.PostgresConnector
tasks.max=1
slot.name=test12
plugin.name=pgoutput
database.hostname=10.10.1.1
database.port=5432 
database.user=postgres 
database.password=123123123
database.dbname=DBsource 
database.server.name=10.10.1.1
table.include.list=public.TestTable
slot.drop.on.stop=true
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://localhost:8081
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://localhost:8081
value.converter.schemas.enable=true
key.converter.schemas.enable=true
internal.key.converter=io.confluent.connect.avro.AvroConverter
internal.value.converter=io.confluent.connect.avro.AvroConverter
transforms=unwrap
transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
decimal.handling.mode=double
time.precision.mode=connect
```


--> after create source connector debezium, data record go into kafka topic ( I confirm is correct number of record ) 
Then add sink connector use confluent kafka connect sink jdbc 
Here is sink connector setting : 
```
{
    "name": "JdbcSinkConnector123",
    "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
    "connection.password": "123123123",
    "topics": "10.10.1.1.public.TestTable",
    "delete.enabled": "false",
    "connection.user": "postgres",
    "connection.url": "jdbc:postgresql://10.10.1.1:5432/DBdest",
    "insert.mode": "upsert",
    "transforms": "renameTopic,tombstoneHandlerExample,TimestampConverter",
    "transforms.renameTopic.type": "org.apache.kafka.connect.transforms.RegexRouter",
    "transforms.renameTopic.regex": "10.10.1.1.public.TestTable",
    "transforms.renameTopic.replacement": "TestTable",
    "transforms.tombstoneHandlerExample.type": "io.confluent.connect.transforms.TombstoneHandler",
    "key.converter": "io.confluent.connect.avro.AvroConverter",
    "key.converter.schemas.enable": "true",
    "key.converter.schema.registry.url": "http://localhost:8081",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "value.converter.schemas.enable": "true",
    "value.converter.schema.registry.url": "http://localhost:8081",
    "auto.evolve": "true",
    "pk.fields": "Id",
    "pk.mode": "record_value",
    "transforms.TimestampConverter.type": "org.apache.kafka.connect.transforms.TimestampConverter$Value",
    "transforms.TimestampConverter.target.type": "Timestamp",
    "transforms.TimestampConverter.field": "CreateDate,UpdateDate"
}
```

After create sink connector, exception on sink connect here : 

```

18:42:51.917+00'::timestamp,'2018-11-22 11:34:19.387+00'::timestamp,'2020-12-28 08:59:39.95+00'::timestamp,'2020-12-28 08:59:39.95+00'::timestamp) ON CONFLICT ("Id") DO UPDATE SET "OrganCode"=EXCLUDED."OrganCode","Ticker"=EXCLUDED."Ticker","ComGroupCode"=EXCLUDED."ComGroupCode","AdjustedDate"=EXCLUDED."AdjustedDate","RateAdjusted"=EXCLUDED."RateAdjusted","Status"=EXCLUDED."Status","CreateDate"=EXCLUDED."CreateDate","UpdateDate"=EXCLUDED."UpdateDate" was aborted: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification  Call getNextException to see other errors in the batch.
org.postgresql.util.PSQLException: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification
org.postgresql.util.PSQLException: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:122)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
	... 10 more
Caused by: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "TestTable" ("Id","OrganCode","Ticker","ComGroupCode","AdjustedDate","RateAdjusted","Status","CreateDate","UpdateDate") VALUES (:timestamp) ON CONFLICT ("Id") DO UPDATE SET "OrganCode"=EXCLUDED."OrganCode","Ticker"=EXCLUDED."Ticker","ComGroupCode"=EXCLUDED."ComGroupCode","AdjustedDate"=EXCLUDED."AdjustedDate","RateAdjusted"=EXCLUDED."RateAdjusted","Status"=EXCLUDED."Status","CreateDate"=EXCLUDED."CreateDate","UpdateDate"=EXCLUDED."UpdateDate" was aborted: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification  Call getNextException to see other errors in the batch.
org.postgresql.util.PSQLException: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification
org.postgresql.util.PSQLException: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification
```


Could you take a look for me ?

**Comment by ahvahsky2008** [comment]
@dungnt081191 same issue. Do you solve it?

**Comment by koureasstavros** [comment]
Same issue, I think this is an issue on JDBC Connector, when the table has only primary key columns and no other column there is nothing to update and thefure the statement syntax is wrong as it always excepts a column to update after the on-conflict.
