### ISSUE TITLE
Kafka-Connect fetching other databases tables which are not specified

### ISSUE THREAD

**Issue by 1abhinandk** [confluentinc/kafka-connect-jdbc#647]
Hello
Following is my connector configuration for the post request to move data from mysql database to topics. 
curl -i -X POST -H "Accept:application/json" -H  "Content-Type:application/json" http://localhost:8083/connectors/ -d '{ 
   "name": "current-classic",
   "config": {
     "connector.class": "io.debezium.connector.mysql.MySqlConnector",
     "tasks.max": "1",
     "database.hostname": "localhost",
     "database.port": "3306",
     "database.user": "jishnu",
     "database.password": "shastha",
     "database.server.id": "4",
     "database.server.name": "current",
     "database.history.kafka.bootstrap.servers": "localhost:9092",
     "database.history.kafka.topic": "current.classicmodels"
   }
 }'

Problem I am facing is that it is fetching other database tables along with specified database table, current.
current
current.classicmodels.customers
current.classicmodels.employees
current.classicmodels.offices
current.classicmodels.orderdetails
current.classicmodels.orders
current.classicmodels.payments
current.classicmodels.productlines
current.classicmodels.products
current.db.employee
current.sakila.actor
current.sakila.address
current.sakila.category
current.sakila.city
current.sakila.country
current.sakila.customer
current.sakila.film
current.sakila.film_actor
current.sakila.film_category
current.sakila.film_text
current.sakila.inventory
current.sakila.language
current.sakila.payment
current.sakila.rental

Please do advice

Thanks
Jishnu

**Comment by Tucker-Allen** [comment]
Jishnu,

I believe that since you did not specify `table.whitelist` in your config, your connector is fuzzy matching to every table that begins with "current". I would include `table.whitelist` to your config to explicitly indicate the tables you are interested in (in your case, just "current").

**Comment by jcustenborder** [comment]
This issue doesn't belong here. `"connector.class": "io.debezium.connector.mysql.MySqlConnector",` This should go in the debezium repository correct?

**Comment by Tucker-Allen** [comment]
I believe you're correct Jeremy, it looks like debezium uses JIRA for issue tracking :-/
https://issues.jboss.org/projects/DBZ/issues/DBZ-1235?filter=allopenissues

**Comment by kkonstantine** [comment]
Closing since this issue is not relevant to this repo (however the workaround mentioned above sounds plausible)
