### ISSUE TITLE
No Suitable Driver - SQLServer

### ISSUE THREAD

**Issue by kevinpthorne** [confluentinc/kafka-connect-jdbc#658]
I've read literally _everywhere_. Any help would be appreciated.

The following config returns 400 with No suitable driver:
`confluent load my-jdbc-connector -d sql-server-config.json`
```
{
  "name": "my-jdbc-connector",
  "config": {
    "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
    "tasks.max": "1",
    "connection.url": "jdbc:sqlserver://<ip>;databaseName=xxx",
    "connection.user": "xxx",
    "connection.password": "xxx",
    "mode": "incrementing",
    "incrementing.column.name": "id",
    "topic.prefix": "sqlserver-",
    "name": "my-jdbc-connector",
    "table.whitelist": "dbo.xxx"
  }
}
```
```
{
  "error_code": 400,
  "message": "Connector configuration is invalid and contains the following 2 error(s):\nInvalid value java.sql.SQLException: No suitable driver found for jdbc:sqlserver://<ip>;databaseName=xxx for configuration Couldn't open connection to jdbc:sqlserver://<ip>;databaseName=xxx\nInvalid value java.sql.SQLException: No suitable driver found for jdbc:sqlserver://<ip>;databaseName=xxx for configuration Couldn't open connection to jdbc:sqlserver://<ip>;databaseName=xxx\nYou can also find the above list of errors at the endpoint `/{connectorType}/config/validate`"
}
```
As [this article directs](https://www.confluent.io/blog/kafka-connect-deep-dive-jdbc-source-connector#no-suitable-driver-found). the driver and connector plugins are loaded and displayed with log level set to DEBUG in `/tmp/confluent.<random>/connect/connect.stdout`
```
**[2019-06-13 13:14:09,811] INFO Added plugin 'io.confluent.connect.jdbc.JdbcSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:167)
[2019-06-13 13:14:09,811] INFO Added plugin 'io.confluent.connect.jdbc.JdbcSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:167)
[2019-06-13 13:14:09,814] DEBUG Registered java.sql.Driver: jTDS 1.3.1 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:272)
**[2019-06-13 13:14:09,861] DEBUG Registered java.sql.Driver: SQLServerDriver:2 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:272)
[2019-06-13 13:14:09,869] DEBUG Registered java.sql.Driver: org.postgresql.Driver@470a9030 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:272)
[2019-06-13 13:14:09,872] DEBUG Registered java.sql.Driver: org.sqlite.JDBC@6c8a68c1 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:272)
```
```
DEBUG Loading plugin urls: [file:/usr/share/java/kafka-connect-jdbc/audience-annotations-0.5.0.jar,
 file:/usr/share/java/kafka-connect-jdbc/common-utils-5.2.1.jar, 
[...], 
file:/usr/share/java/kafka-connect-jdbc/mssql-jdbc-6.4.0.jre8.jar, 
[...]
```

Attempted with the following JDBC Drivers for the SQL Server (11.0.6020):
- `mssql-jdbc-6.4.0.jre8.jar`
- `mssql-jdbc-7.2.2.jre8.jar`
- `sqljdbc41.jar` - 4.1

I've got Microsoft SQL Server Management Studio open to the server, connected with the same credentials given in the config file.

```
$ confluent version
[...]
Confluent Community Software: 5.2.1
```

Any ideas? I know that this error will also be thrown for an invalid url, but the database name and IP are correct ([doc](https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-2017)) Thanks!

**Update:**
Just made a successful connection from a normal JDBC bare-bones application with the following: (using the 7.2.2 JDBC SQL Server Driver) 
```
        String url = "jdbc:sqlserver://<ip>;databaseName=xxx";
        String user = "xxx";
        String password = "xxx";

        try (Connection connection = DriverManager.getConnection(url, user, password)) {
            try (Statement statement = connection.createStatement()) {
                String sql = "select TOP (3) * from xxx";
                try (ResultSet result = statement.executeQuery(sql)) {
                    while (result.next()) {
                        String name = result.getString("Name");
                        Timestamp startDate = result.getTimestamp("StartDate");

                        System.out.println("Name: " + name + " StartDate: " + startDate);
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
```

**Comment by kevinpthorne** [comment]
Moving **ANY** JDBC drivers drawer from `/usr/share/java/kafka-connect-jdbc` to `/usr/share/java/kafka` fixed it. Was this expected behavior?

**Comment by visakhmurukes** [comment]
Hi @kevinpthorne 
I've tried copying jdbc driver to kafka folder too still getting the same error. My jdbc driver used is mssql-jdbc-7.2.2.jre11.jar
The error I get from connector is the below

> "org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: No suitable driver found for jdbc:sqlserver://<ServerIP>:1433;databaseName=<DBName>;username=sa;password=<pwd>;\n\tat io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider

**Comment by kevinpthorne** [comment]
> My jdbc driver used is mssql-jdbc-7.2.2.jre11.jar

JRE 11...is your Kafka installation running in JRE 11?
