### ISSUE TITLE
Custom Database Dialect not being found by ServiceLoader

### ISSUE THREAD

**Issue by mtraynham** [confluentinc/kafka-connect-jdbc#659]
I wrote an extended Postgres database dialect to handle JSONB sinks for Maps/Array/Struct, but it doesn't seem to get picked up by the [ServiceLoader in DatabaseDialects](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/dialect/DatabaseDialects.java#L78) even though the [documentation here suggests it would](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/dialect/DatabaseDialectProvider.java#L39-L45).

I think this is because the ServiceLoader here is not checking the full classpath of Kafka Connect but only a subset because kafka-connect-jdbc is itself a plugin and uses a PluginClassLoader for the ServiceLoader.

![Screen Shot 2019-06-14 at 1 56 12 PM](https://user-images.githubusercontent.com/5741321/59528400-2fdc5a00-8eac-11e9-9768-91e156ed3776.png)
  
If I instead move my plugin jar inside `/usr/share/java/kafka-connect-jdbc` it works.

**Comment by kkonstantine** [comment]
Closing this issue, because indeed adding the dialect as part of the connector plugin itself is the intended way to add the dialect. It the connector is only in the `CLASSPATH` and not the `plugin.path` then the dialect could be picked up from the `CLASSPATH` as well. 

Feel free to reopen if you still think there's a gap in supporting the addition of extra dialects

**Comment by alex88** [comment]
@mtraynham sorry for resurrecting such and old issue, but do you mind sharing your custom dialect? I have the same use case for clickhouse and I'm trying to achieve the same

**Comment by mtraynham** [comment]
@alex88 sure, I don't mind.  Just a fair warning:
- It's written in Kotlin, so you'd have to rewrite to Java
- When I was using it, we depended on Kafka 2.2.0, so it may be outdated
- I had to duplicate [org.apache.kafka.connect.json.JsonConverter](https://github.com/apache/kafka/blob/trunk/connect/json/src/main/java/org/apache/kafka/connect/json/JsonConverter.java) because it needed access to [private JsonNode convertToJson(Schema schema, Object value)](https://github.com/apache/kafka/blob/trunk/connect/json/src/main/java/org/apache/kafka/connect/json/JsonConverter.java#L561) which is used to convert the Connect schema & value to a json blob and shove into a `PGobject`.

https://gist.github.com/mtraynham/a4d4742e1ba712590e6b7c346b8d37bc

**Comment by alex88** [comment]
Oh that's just perfect, we use kotlin too and I was exactly looking into overriding `maybeBindLogical`..
Thanks a lot!

**Comment by ak4153** [comment]
Sorry to double ressurect this issue.

Did you compile the customdialect as part of kafka-connect jar file, or did you compile it separately and dropped the jar at the plugin path?

Do you remember the plugin path ?
