### ISSUE TITLE
java.sql.SQLException: Operation not permit on a closed resultSet

### ISSUE THREAD

**Issue by ashikaumanga** [confluentinc/kafka-connect-jdbc#666]
We are trying to use Kafka Connect JDBC Source connector (3.3.2) to load MySQL database with large amount of data. We use MariaDB Client JDBC. To make streaming/cursor enable, we did a small change to the Connector  to set "fetchSize" in the PreparedStatement.

Change is here : https://github.com/ashikaumanga/kafka-connect-jdbc/pull/1/files

Now we get following exception when Task trying to read records from ResultSet : 
Any tips ?

> ERROR Failed to run query for table TimestampIncrementingTableQuerier{name='null', query='SELECT appl_id,c_id,play_date,play_num,play_mem,res_status_cd,cancel_flg,cancel_date,appl_date,customer_id,memo,device_cd,delegate_name,delegate_name_kana,delegate_mail_address,delegate_zip1,delegate_zip2,delegate_pref_cd,delegate_address1,delegate_address2,delegate_tel1,delegate_tel2,delegate_tel3,delegate_contact_tel1,delegate_contact_tel2,delegate_contact_tel3,plan_id,play_fee,add_fee_2b,add_fee_3b,applicable_advance_flg,close_id,mobile_mail_send_flg,confirm_flg,appl_trans_id,rsv_option_id,before_plan_id,before_play_fee,com_appl_id,point_invest_cancel_flg,insert_date,update_date,update_user_id,del_flg,updated_ts FROM application', topicPrefix='prod-newspdb-pipeline-deltadb-table1', timestampColumn='updated_ts', incrementingColumn='null'}: {} (io.confluent.connect.jdbc.source.JdbcSourceTask)
> java.sql.SQLException: Operation not permit on a closed resultSet
> 	at org.mariadb.jdbc.internal.com.read.resultset.SelectResultSet.next(SelectResultSet.java:637)
> 	at io.confluent.connect.jdbc.source.TableQuerier.next(TableQuerier.java:96)
> 	at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.next(TimestampIncrementingTableQuerier.java:55)
> 	at io.confluent.connect.jdbc.source.JdbcSourceTask.poll(JdbcSourceTask.java:208)
> 	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:163)
> 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
> 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by gharris1727** [comment]
@ashikaumanga Just based on a quick reading of your change, replacing an `! isValid` check with an `isClosed` check probably changes the semantics, and the connector is either closing the connection early, or not re-opening it properly.

I'm not familiar with that driver and it's specific semantics, so you'll have to dig deeper to see what the driver thinks is going on. If you have any more questions, please re-open this ticket and i'll be happy to answer.
