### ISSUE TITLE
Question: Guidelines for mapping Avro Type and JSON/JSONB in Connector

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [confluentinc/kafka-connect-jdbc#670]
I could not find how to map an Avro Properties, either in Stringified JSON Text or Avro MAP to to an JSONB/JSON Types of PostgreSQL.

We get error while string already stringified JSON TEXT into PostgreSQL, below error is what we get while inserting into JSONB column. 

Batch entry 0 INSERT INTO \"test\"(\"name\",\"properties\",\"time\") VALUES('Test','{\"name\"}:\"JSON\"','2019-6-29 18:0:35.786000 +0:0:0') was aborted.  Call getNextException to see the cause.\norg.postgresql.util.PSQLException: ERROR: column \"properties\" is of type jsonb but expression is of type character varying\n  Hint: You will need to rewrite or cast the expression.\n

https://docs.confluent.io/current/connect/transforms/cast.html

any example config for mapping avro string/map types to jsonb will be helpful for the community.

**Comment by bigbang4u2** [comment]
I also need this. With IOT data I get lot of fields and want to use jsonb to map those to avro map. I need this for postgres sink

**Comment by robdesbois** [comment]
Current sink connector supports this; see my comment here: https://github.com/confluentinc/kafka-connect-jdbc/issues/46#issuecomment-730532792

**Comment by NathanNam** [comment]
https://github.com/confluentinc/kafka-connect-jdbc/issues/46#issuecomment-1135209669
