### ISSUE TITLE
Kafka Connect JDBC is possibly missing events

### ISSUE THREAD

**Issue by limadelrey** [confluentinc/kafka-connect-jdbc#683]
Hello,

I'm facing a strange behavior using kafka-connect-jdbc that I would like to share with you. The use case is really simple: there's a PostgreSQL database using Debezium PostgreSQL CDC Connector (source) and another PostgreSQL database using Kafka Connect JDBC (sink). This setup is working for 2 weeks at this moment, but I've noticed that there's already rows missing on the sink database. For that reason I've made three tests:

1. I've consumed every event on this Kafka topic (and I found that every event was saved);
2. I've created one test connector which listened to the very same Kafka topic and saved the events on sink database in a test table (and I found that every row since the beginning was saved unlike the real connector);
3. I've inserted one row on source database (and I found that both connectors, the real one and the test one, listened to the generated event and saved a new row on the respective table).

So, if the information is saved on Kafka and the real connector is still working, how is it possible that the real connector missed saving some of the rows during this two-week span?

**Comment by NathanNam** [comment]
@limadelrey Thanks for opening this issue. Could you share the following information with us?

1. Which version of JDBC Connector did you use? Which version of PostgreSQL JDBC driver did you use?
2. In your Kafka topics, do you see all records from PostgreSQL database (2-week-long records)?
3. What is the primary key you use? Do you happen to have some records with the same primary key?

Thanks,
Nathan

**Comment by limadelrey** [comment]
Hi @NathanNam,

1. When I opened this issue I was using kafka-connect-jdbc-5.3.0 & postgresql-9.4-1206-jdbc41;
2. I couldn't see all records because the topic was configured to compact its records;
3. Since I was using a CDC approach, the primary key was the table's PK itself. So yes, the primary key was reused.

To be honest this unexpected behaviour happened during my vacation period, so it may have occurred something on my side. Also, there isn't much more information that I can share at this moment. You may close this issue. If it happens again I'll report it with more detail.

Thank you so much for your time!
