### ISSUE TITLE
JDBC MySQL sink capture DELETE 

### ISSUE THREAD

**Issue by HungLe123456** [confluentinc/kafka-connect-jdbc#695]
I tried to create a CDC MySQL database using the JDBCSinkConnector from the MySQL source database. I have read that the Confluent support the DELETE but it did not work. I tried using flattening SMT using delete.handling.mode option (https://debezium.io/docs/configuration/event-flattening/#configuration_options) but the sink database did not add the _delete field. Maybe I did a wrong configuration. The configuration for the source is:
curl -i -X POST -H "Accept:application/json" \
    -H  "Content-Type:application/json" http://localhost:8083/connectors/ \
    -d '{
  "name": "source_connect_mysql",
  "config": {
    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
    "tasks.max": "1",
    "database.hostname": "localhost",
    "database.port": "3306",
    "database.user": "root",
    "database.password": "123456",
    "database.server.id": "2",
    "database.server.name": "server_mysql_connect",
    "database.whitelist": "test_db_1",
    "database.history.kafka.bootstrap.servers": "localhost:9092",
    "database.history.kafka.topic": "testing",
    "transforms": "route",
    "transforms.route.type": "org.apache.kafka.connect.transforms.RegexRouter",
    "transforms.route.regex": "([^.]+)\\.([^.]+)\\.([^.]+)",
    "transforms.route.replacement": "$3"
  }
}'
the configuration for the sink is:
curl -i -X POST -H "Accept:application/json" \
    -H  "Content-Type:application/json" http://localhost:8083/connectors/ \
    -d '{
    "name": "sink_server_mysql_product",
    "config": {
        "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
        "tasks.max": "1",
        "topics": "tbl_product",
        "connection.url": "jdbc:mysql://localhost:3306/test_db_2?nullNamePatternMatchesAll=true",
        "connection.user": "root",
        "connection.password": "123456",
        "transforms": "unwrap",
        "auto.create": "true",
        "auto.evolve": "true",
        "insert.mode": "upsert",
        "pk.fields": "id",
        "pk.mode": "record_value",
        "transforms.unwrap.type": "io.debezium.transforms.UnwrapFromEnvelope",
        "transforms.unwrap.drop.tombstones": "false",
        "transforms.unwrap.drop.deletes": "false",
        "behavior.on.null.values": "delete"
    }
}'

Did i config wrong? Could you tell me the config for the source and the the sink so that i could DELETE a reccord in the sink or just enable  the flattening SMT and its delete.handling.mode option .
Thank you

**Comment by wicknicks** [comment]
what version of the connector are you using? looking at the latest release, v5.3.0, looks like you need to set `delete.enabled` to `true` for this feature to kick in. Also, we need `pk.mode` to be set to `record_key`. Looks like you are running with `record_value`.

docs here: https://docs.confluent.io/current/connect/kafka-connect-jdbc/sink-connector/sink_config_options.html#writes

**Comment by HungLe123456** [comment]
I installed the latest release and chnage the cofig like you said but its still not work. Well this is my first set up for debezium so maybe i downloaded the wrong version of JDBC connector, Debezium connector, Kafka connector, MySQL connector that may create a conflict between them. Both my sink and source database are MySQL database. Have you tried set up this type of config before? The INSERT and UPDATE command worked normally, only the DELETE was not working. If you can could you tell me the version of JDBC connector, MySQL connector, Kafka Connector and Debezium you are using and the config for both source and sink that the DELETE function works properly even with a different type of database. Thank you very much.

**Comment by wicknicks** [comment]
Use 5.3 for the connector and Kafka. For debezium mysql connector, I think any version should work, but let's use the latest stable version (0.9).

**Comment by HungLe123456** [comment]
I have a question to ask. Can i have 2 source connectors of 2 databases
stream data to 2 sink database using only 1 kafka port :8083 or with 1
source connector i must use 1 port only. When i tried to create a second
source connector through the same port, the 1st one got an error.

Vào Th 6, 16 thg 8, 2019 vào lúc 06:14 Arjun Satish <
notifications@github.com> đã viết:

**Comment by siva5231** [comment]
In Mysql sink,  What is the name of the jdbc connector need to deply in Docker
