### ISSUE TITLE
timestamp column on huge table performance 

### ISSUE THREAD

**Issue by selvarajchennappan** [confluentinc/kafka-connect-jdbc#701]
We are using Kafka jdbc source connector to read from IBMDB2 . We have approx 100 tables and each one contains 10 million to 100 million records as of now. We have used mode=timestamp and poll.interval.ms=5000 and there is no index on the timestamp column in the source system. we could see for every 5 secs below query is getting fired to detect the changes . 
SELECT * FROM "Schema"."Table" WHERE "Schema"."Table"."UPDATE_TS" > ? AND "Schema"."Table"."UPDATE_TS" < ? ORDER BY "Schema"."Table"."UPDATE_TS" ASC.

Will it not affect performance of source DB ?. 
Did anyone is using  timestamp column  on big tables ? Have you observed any performance issue ?
Please help me .

**Comment by gharris1727** [comment]
@selvarajchennappan Without an index on the timestamp column, the timestamp query could be performing a row-scan on every query, and overloading the database, or stalling for too long in the connector.

I would suggest using a test database with data of similar scale to your production system to that the connector performance is sufficient for your use-case. I would predict that the index on the timestamp column would be necessary for using this connector with that amount of data.

**Comment by gharris1727** [comment]
If you have any further questions, you can re-open this issue, and i'd be happy to answer them.
