### ISSUE TITLE
Single message transforms not applied to sink column names

### ISSUE THREAD

**Issue by jowparks** [confluentinc/kafka-connect-jdbc#702]
I have a jdbc connector set up with the following config:
```
class: "io.confluent.connect.jdbc.JdbcSinkConnector"
  config:
    "tasks.max": "1"
    "max.retries": "10"
    "retry.backoff.ms": "3000"
    "topics": "mytopic"
    "table.name.format": "mytable"
    "insert.mode": "upsert"
    "pk.mode": "record_key"
    "pk.fields": "resource_id"
    "auto.create": "true"
    "auto.evolve": "true"
    "connection.url": "<url>"
    "connection.user": "<user>"
    "connection.password": "<password>"
    "transforms": "fieldNamesToUnderscore"
    "transforms.fieldNamesToUnderscore.type": "com.github.jcustenborder.kafka.connect.transform.common.ChangeCase$Key"
    "transforms.fieldNamesToUnderscore.from": "LOWER_CAMEL"
    "transforms.fieldNamesToUnderscore.to": "LOWER_UNDERSCORE"
```

The connector is running and data is being sinked into the postgresql database, but the column names do not adhere to the SMT transforms stated in the config above. I know the SMT is running because the connector fails if I use `"pk.fields": "resourceId"` instead of `"pk.fields": "resource_id"`. 
To be specific, our Avro schema for our data in Kafka is defined with `LOWER_CAMEL`, and we want the field names of the postgres db to be `LOWER_UNDERSCORE` after running thru the jdbc sink connector. We are using @jcustenborder 's [transforms](https://github.com/jcustenborder/kafka-connect-transform-common) to modify the case.

Example
Actual:
Original field `myField`, database column name `myField`
Expected:
Original field `myField`, database column name `my_field`

**Comment by jowparks** [comment]
I just noticed that the only field that has the transformation applied in the db field names is the primary key field `resource_id`, where the rest of the fields are still camel case.

**Comment by jowparks** [comment]
Update:

I ended up determining that this was my error. I needed to have a second transform for the values. I was only transforming the keys previously.

**Comment by khasanjon-dev** [comment]
In my experience, using schema changes is not correct
I don't know exactly how the jdbc sink connector detects schema changes, but the pgoutput plugin cannot listen to ddl changes for postgres and does not send them to the kafka topic
My advice is to make the schema changes custom
