### ISSUE TITLE
kafka-connect-jdbc source connector OOM

### ISSUE THREAD

**Issue by Rahul7794** [confluentinc/kafka-connect-jdbc#705]
I am using kafka-connect-jdbc:5.3.1 and when I am running the connector it kicks me out with ```  Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-11"```

My source properties file looks something like this
`name=jdbc_source_postgres
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
key.converter=org.apache.kafka.connect.storage.StringConverter
key.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false

connection.url=jdbc:postgresql:/localhost:5432/demo?user=********&password=*******&defaultFetchSize=10000&useCursorFetch=true    
tasks.max=10
table.types=TABLE
table.whitelist=sample_table
mode=timestamp
timestamp.column.name=last_modified
validate.non.null=false
batch.max.rows=100
topic.prefix=kafka02-
poll.interval.ms=3600000`

Any help would be much appreciated. I am able to get the data in topic with the bulk mode and query with limit option but with timestamp its just fails

Note: **I am running it on EC2 instance with instance type as t2.large and no of records is atmost 4 million**

**Comment by gharris1727** [comment]
@Rahul7794 

With a default fetch size of 10000 and 10 tasks, the JDBC driver could potentially load 100k records before the connector ever has a chance to consume them. With 8gb of ram in a t2 instance, each row in the dataset can only be 80kb wide before the connector is going to start having issues. With memory overhead, you'd probably start experiencing issues at 50-60kb/row.

If you reduce the defaultFetchSize to 100, to match the `batch.max.rows`, do you still experience an OOM exception?

**Comment by yohei1126** [comment]
This issue might be fixed with this PR https://github.com/confluentinc/kafka-connect-jdbc/pull/758

**Comment by gharris1727** [comment]
Closing as fixed, if your issue persists please open a new issue.
