### ISSUE TITLE
Send message to multiple topics

### ISSUE THREAD

**Issue by mithunmanohar** [confluentinc/kafka-connect-jdbc#707]
Is it possible split a message and send it to two separate topics using SMT? The use case is I have a table which has both sensitive and non sensitive columns. I want to send the sensitive columns to a particular Kafka topic and non-sensitive columns to another Kafka topic using JDBC connector. Is this possible ?

**Comment by mariusneo** [comment]
If you look at https://github.com/axbaretto/kafka/blob/master/connect/api/src/main/java/org/apache/kafka/connect/transforms/Transformation.java#L38 , which is the interface implemented by all the SMT classes ( see https://docs.confluent.io/current/connect/transforms/index.html ) you'll see that the `apply` method looks like this:

```
R apply(R record);
```

Out of a record you can therefor receive exactly one record through the transformation. So i assume that it is not possible to achieve the outcome you want by simply using SMT.

Nevertheless, by using `ksql` in between 

```
your db > kafka connect jdbc > kafka > ksql server
```

you can achieve the functionality that you're looking for.

See https://docs.confluent.io/current/ksql/docs/tutorials/examples.html#ksql-examples to get you started.
