### ISSUE TITLE
Incorrect Schema getting registered for ORACLE NUMBER data types

### ISSUE THREAD

**Issue by aliasbadwolf** [confluentinc/kafka-connect-jdbc#716]
It was interesting to see that the Kafka Sink Connector is not honoring the schema registered by Kafka Source Connector (although I believe Kafka Sink Connector has every right to do so as the registered schema is incorrect and that is caught correctly by Kafka Sink Connector). 

While creating schema for fields having NUMEBR data types (without precision and scale) from Oracle DB, Kafka JDBC source by defaults assign a precision of "64" (which is fine) but assigns a scale of "127" (which is more than the precision) and Kafka Sink connector is complaining about it.

Sample from Schema for a NUMBER data type field
`{\"name\":\"TAX_RATE\",\"type\":[\"null\",{\"type\":\"bytes\",\**"scale\":127,**\"precision\":64,\"connect.version\":1,\"connect.parameters\":{\"**scale\":\"127**\"},\"connect.name\":\"org.apache.kafka.connect.data.Decimal\",\"logicalType\":\"decimal\"}`

Error received from Kafka S3 Sink connector:

`"state": "FAILED",
            "trace": "org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.IllegalArgumentException: **Invalid decimal scale: 127 (greater than precision: 64)**\n\tat org.apache.avro.LogicalTypes$Decimal.validate(LogicalTypes.java:217)\n\tat org.apache.avro.LogicalType.addToSchema(LogicalType.java:70)\n\tat org.apache.avro.LogicalTypes$Decimal.addToSchema(LogicalTypes.java:182)\n\tat io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:944)\n\tat io.confluent.connect.avro.AvroData.addAvroRecordField(AvroData.java:1059)\n\tat io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:900)\n\tat io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:732)\n\tat io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:726)\n\tat io.confluent.connect.s3.format.avro.AvroRecordWriterProvider$1.write(AvroRecordWriterProvider.java:69)\n\tat io.confluent.connect.s3.TopicPartitionWriter.writeRecord(TopicPartitionWriter.java:477)\n\tat io.confluent.connect.s3.TopicPartitionWriter.checkRotationOrAppend(TopicPartitionWriter.java:265)\n\tat io.confluent.connect.s3.TopicPartitionWriter.executeState(TopicPartitionWriter.java:210)\n\tat io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:174)\n\tat io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:193)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:565)\n\t... 10 more\n",`

Guess this should be fixed to set scale same as precision i.e. "64" in case of NUMBER data types where precision and scale are not provided by the source table schema.

**Comment by slu-gh** [comment]
I am having the same issue. Also tried out the "numeric.mapping" and "query" options but still not doing what we want (bulk ingesting entire table with NUMBER fields that without specified precision and scale). If anyone knows any workaround on this will be greatly appreciated.

**Comment by aliasbadwolf** [comment]
@slu-gh Are you facing the same issue while writing data to S3 using S3 Sink? We are able to ingest all the data into Kafka (even if the schema registered for NUMBER fields were incorrect) and were able to process data using Spark but we were facing this issue specifically when saving data from topics to S3 using S3 Sink Connector. If you have other frameworks that can read data from Kafka and put to S3 then you can use them.

**Comment by slu-gh** [comment]
@aliasbadwolf Thanks for the update. To me the problem happened when creating the JDBC source connector instance and it seems like it failed to create the schema in registry in the first place because of the NUMBER fields. But the `query` option I mentioned actually helped (by manually casting NUMBER fields with some precision and scale).

**Comment by aliasbadwolf** [comment]
@slu-gh Well, the schema gets registered in registry for NUMBER fields (even without precision and scale) but a NUMBER field without precision and scale cannot be used as incrementing field in connector.

**Comment by gharris1727** [comment]
@aliasbadwolf Thanks for bringing this to our attention. This is definitely a bug in the JDBC Source Connector, and should be fixed.

It looks like the relevant functions are:
- [`GenericDatabaseDialect::columnConverterFor`](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java#L1091) 
- [`GenericDatabaseDialect::addFieldToSchema`](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java#L870)
- [`GenericDatabaseDialect::decimalScale`](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java#L1326) 

If you or anyone else has time, try to fix the issue yourself. Feel free to open a PR and ping me to review and merge it.

**Comment by C0urante** [comment]
Thanks @aliasbadwolf and @slu-gh for looking into this. I've come up with a proposed patch in https://github.com/confluentinc/schema-registry/pull/1381 that should prevent the error you're seeing in this issue from arising.

Setting the scale of the schema published by the connector to be equal to the precision of the column is an approach that we could take, but would involve some heavy lifting[1] and also incur a risk of data loss in some cases[2].

[1] - Columns defined with the `NUMBER` type (no fixed precision or scale) may implicitly utilize a precision of 38, but don't provide a precision with the `ResultSet::getMetadata::getPrecision` method (or, more accurately, provide a precision of `0`). We could possibly default to a precision of 38 in this case, but this would have to be looked into carefully, and still wouldn't handle the case of...

[2] - Setting the scale to match the precision would strip certain values of some of their information. Assume we're using a precision of 38, and that the value `0.000000000000000000000000000000000000000000000000001` (equivalent to `1E-51`) is present in the database. Retrieving it with a scale of 38 would result in the value `0E-38` being published by the connector, which would end up rounding off the actual value present in the database. By defaulting to a scale of 127, we're at least preserving these values, a behavior which may be actively relied upon by some of our users.

**Comment by C0urante** [comment]
As https://github.com/confluentinc/schema-registry/pull/1381 has now been merged, I'd like to close this issue.

If anyone runs into this problem again, please first ensure that you are running a version of the Avro converter that has that fix in it, and if so, feel free to re-open the issue (preferably with a stack trace, connector config, and the DDL for the source tables 🙂).
