### ISSUE TITLE
Timestamp column double quotes are considered quoted identifiers in Postgres

### ISSUE THREAD

**Issue by SokratisVidros** [confluentinc/kafka-connect-jdbc#732]
### Introduction
I am using **Kafka & Kafka Connect Version : 2.2.1-L0**, **JDBC connector 5.3.0** along with **Postgres 9.6** and I came across the following scenario on which I'd really appreciate your input.

### Schema
Imagine having two tables `authors` and `books`. These tables are connected with a one-to-many relationship. That is, a book has one author and an author has many books. The tables schema is the following:

|authors|
|---|
|id|
|name|
|created_at|
|updated_at|

|books|
|---|
|id|
|title|
|author_id|
|created_at|
|updated_at|

### Streaming

The requirement is to stream new and updated book data along with the author name to a Kafka topic. Thus, Kafka Connect JDBC is used in `timestamp` mode. The setup is the following: 

```
...
mode=timestamp
query=select books.title, authors.name as author_name, books.created_at, books.updated_at from books inner join authors on authors.id = books.author_id
table.types=VIEW
timestamp.column.name=books.updated_at
...
```

The connector then builds the final polling query by appending the timestamp condition based on the timestamp column enclosed in double quotes. 

```SQL
SELECT books.title,
       authors.name AS author_name,
       books.created_at,
       books.updated_at
FROM books
INNER JOIN authors ON authors.id = books.author_id
WHERE "books.updated_at" > ?
  AND "books.updated_at" < ?
ORDER BY "books.updated_at" ASC;
```

Unfortunately the connector fails with the following error:

`org.postgresql.util.PSQLException: ERROR: column "'books.updated_at'" does not exist`

This is because double-quotes also work as delimiter identifiers. In further detail and according to [Postgres docs](https://www.postgresql.org/docs/9.6/sql-syntax-lexical.html):

> There is a second kind of identifier: the delimited identifier or quoted identifier. It is formed by enclosing an arbitrary sequence of characters in double-quotes ("). A delimited identifier is always an identifier, never a key word. So "select" could be used to refer to a column or table named "select", whereas an unquoted select would be taken as a key word and would therefore provoke a parse error when used where a table or column name is expected.

All in all, it seems that Kafka Connect JDBC should not append double quotes in query mode and the user should be allowed to configure the connector accordingly. Are there any workaround on this?

Thanks in advance.

**Comment by gharris1727** [comment]
@SokratisVidros This is a known issue, and the workaround is to set `quote.sql.identifiers=never` in your configuration. Let me know if this addresses the issue you're having.

It appears that this configuration option never made it to the documentation, so I'll make sure that gets updated with the most recent configurations.

**Comment by SokratisVidros** [comment]
Thanks a lot @gharris1727 ! Appreciated!

**Comment by keerthivasan-r** [comment]
> Thanks a lot @gharris1727 ! Appreciated!

Hi @SokratisVidros I have also updated in the config. but, it doesn't seem to work. Is there any other config? I have added this, after the query property. Please help

**Comment by SokratisVidros** [comment]
@keerthivasan-r A workaround is to use a temporary table e.g. with CTE in Postgres and also apply the filtering there as well. Then, the connector will work on a smaller single resource and quotes won't be required. Hope that helps.
