### ISSUE TITLE
MSSQL doesn't work with incremeting or timestamp source connector

### ISSUE THREAD

**Issue by wowo** [confluentinc/kafka-connect-jdbc#733]
I'm trying to create source connector for my SQL Server tables, here's example:

```
{
  "name": "test",
  "config": {
      "tasks.max":"1",
      "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
      "connection.url": "jdbc:sqlserver://REDACTED;databaseName=REDACTED",
      "connection.user": "REDACTED",
      "connection.password": "REDACTED",
      "topic.prefix": "test",
      "poll.interval.ms" : 2000,
      "table.whitelist": "dbo.Client",
      "mode":"incrementing",
      "incrementing.column.name": "Id"
  }
}
```

I'm getting following error, which doesn't say anything...

`java.lang.IllegalArgumentException: Number of groups must be positive. at org.apache.kafka.connect.util.ConnectorUtils.groupPartitions(ConnectorUtils.java:41) at io.confluent.connect.jdbc.JdbcSourceConnector.taskConfigs(JdbcSourceConnector.java:148) at org.apache.kafka.connect.runtime.Worker.connectorTaskConfigs(Worker.java:305) at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnector(DistributedHerder.java:997) at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnectorTasksWithRetry(DistributedHerder.java:950) at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$900(DistributedHerder.java:110) at org.apache.kafka.connect.runtime.distributed.DistributedHerder$17$1.call(DistributedHerder.java:963) at org.apache.kafka.connect.runtime.distributed.DistributedHerder$17$1.call(DistributedHerder.java:960) at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:270) at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:219) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)`

The same happens when I use mode timestamp with `timestamp.column.name` (column Modified with type `datetimeoffset`).

When I use mode bulk with custom query, it works fine.

Any ideas?

**Comment by wowo** [comment]
Hi everyone, anyone has a clue what's wrong here?

**Comment by gharris1727** [comment]
@wowo It appears that this exception appears when you don't specify a custom query, and the connector can't find any tables to read from in the database. I noticed that your config includes `"table.whitelist": "dbo.Client"`, so it's possible that the table exists in the database but is getting accidentally filtered out.

You can try changing the `table.whitelist` to `Client`, `client`, or `CLIENT`, to see if there's a case sensitivity issue. If that still doesn't work, you can enable `DEBUG` logging, and try and find this statement in the log:

```
Got the following tables: 
```

This should be a list of tables that the connector finds, before filtering with the whitelist/blacklist. You can confirm that your table is being found, and then try adjusting the whitelist to get it to match correctly.

In more recent releases, this exception is replaced with a more descriptive error message, so hopefully the next person will have an easier time debugging this.

**Comment by gharris1727** [comment]
You may also need to change your [`table.types` config](https://docs.confluent.io/current/connect/kafka-connect-jdbc/source-connector/source_config_options.html#connector), if your table is not a regular table.

**Comment by gharris1727** [comment]
If you have any more questions, you can re-open this issue and i'd be happy to answer them.

**Comment by wowo** [comment]
indeed @gharris1727 , dropping `dbo.` suffix helped. Thanks!
