### ISSUE TITLE
Wrong Kafka Version

### ISSUE THREAD

**Issue by BBartosz** [confluentinc/kafka-connect-jdbc#74]
In pom.xml there is version 0.10.1.0-SNAPHOT and it is not present in confluent repo. When I try to compile project I get:

Downloading: http://packages.confluent.io/maven/org/apache/kafka/connect-api/0.10.1.0-SNAPSHOT/maven-metadata.xml
Downloading: http://packages.confluent.io/maven/org/apache/kafka/connect-api/0.10.1.0-SNAPSHOT/connect-api-0.10.1.0-SNAPSHOT.pom
[WARNING] The POM for org.apache.kafka:connect-api:jar:0.10.1.0-SNAPSHOT is missing, no dependency information available
Downloading: http://packages.confluent.io/maven/org/apache/kafka/connect-api/0.10.1.0-SNAPSHOT/connect-api-0.10.1.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.871 s
[INFO] Finished at: 2016-05-18T18:23:26+07:00
[INFO] Final Memory: 11M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project kafka-connect-jdbc: Could not resolve dependencies for project io.confluent:kafka-connect-jdbc:jar:3.1.0-SNAPSHOT: Could not find artifact org.apache.kafka:connect-api:jar:0.10.1.0-SNAPSHOT in confluent (http://packages.confluent.io/maven/) -> [Help 1]

I don't know where to find proper version so this is why I report it here.

**Comment by ewencp** [comment]
@BBartosz Sometimes our in-development versions depend on development versions of dependencies. In this case, we've updated this branch to work with the trunk version of Kafka. To get the dependency, you can checkout Kafka and install to your local Maven repo using `./gradlew installAll`

**Comment by gwenshap** [comment]
or just build the 3.x branch of this repo. They should be identical at this time :)

**Comment by BBartosz** [comment]
Sorry for this newbie issue but it works after all. Thank you for help 👍
