### ISSUE TITLE
JDBC connector currently does not support partitioned topics. 

### ISSUE THREAD

**Issue by mborade** [confluentinc/kafka-connect-jdbc#75]
JDBC connector currently does not support partitioned topics. I think JDBC connector should have a default partitioning logic to publish the messages to the different partitions in the topic. It should also support a way to plug-in any custom partitioning logic.

**Comment by ewencp** [comment]
@mborade Is this different from #28? Do you have use cases other than either a) unkeyed messages delivered in order to a single partition or b) keyed messages delivered to multiple partitions as determined by the key?

**Comment by mborade** [comment]
One of the cases would be, where I would want to use a custom partitioning logic to partition the messages while sending to Kafka. Currently, I think JDBC connector does not support sending the message to a particular partition of a topic or provide any extension to plug-in any custom partitioning logic to calculate the partition.

**Comment by ewencp** [comment]
@mborade I was looking for a more concrete use case. It's easy to just add completely pluggable components, but its not necessarily the right design choice for a couple of reasons. First, its relatively complex, makes configuration harder, . Second, if 99% of use cases can be addressed with a small, fixed set of modes, that's simpler for users to understand and for us to explain than a completely generic solution.

You're always going to have to choose the destination partition somehow. If its not ok to round-robin, and using the primary key wouldn't work, how else are you choosing the partition? By manually specifying a column to use? And if so, why wouldn't that just be the key?

**Comment by mborade** [comment]
@ewencp We are using the default partitioning logic. I thought that the connector should also support any custom partitioning logic if required. However, I agree to your points.

**Comment by wilaszekg** [comment]
This issue has been closed but isn't it different from #28 ? Does JDBC connector support balancing of unkeyed messages between multiple partitions of one topic? I have a topic with 4 partitions and `partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner` in config but all messages go to only one partition.
