### ISSUE TITLE
JDBC Source Connector for Oracle mode is incrementing and/or timestamp , How to differentiate update event or insert event?

### ISSUE THREAD

**Issue by HXDe** [confluentinc/kafka-connect-jdbc#753]
I need to add update events  insert  events or delete events to data

**Comment by gharris1727** [comment]
@HXDe By it's query-based design, the source connector cannot generate deletion events. You will need to use some sort of CDC connector, or use explicit soft-delete flags in your data.

You can only determine if an event is an update if you're using `timestamp+incrementing` mode, and you see your incrementing ID more than once.

I hope this answers your question, and if you want to ask any follow-up questions please re-open the issue. Thanks!
