### ISSUE TITLE
Postgres ALTER TABLE fails when column type is BOOLEAN

### ISSUE THREAD

**Issue by jmakuc** [confluentinc/kafka-connect-jdbc#755]
Hi there. I'm trying to write a record to a postgres table but it fails when tries to modify the table definition:

`[2019-12-04 20:25:30,590] WARN Amend failed, re-attempting (io.confluent.connect.jdbc.sink.DbStructure:170)
org.postgresql.util.PSQLException: ERROR: column "active" is of type boolean but default expression is of type integer
  Hint: You will need to rewrite or cast the expression.`

The error is triggered by this modification:

`ADD "active" BOOLEAN DEFAULT 1,`

I've tried on psql 10 and 11 directly in the command line and in fact you cannot define a default value for boolean column using the number 1. 

I've tracked the issue down to this line:

https://github.com/confluentinc/kafka-connect-jdbc/blob/237e4dcb88ace630fc5670520a4727216d3e568b/src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java#L1718

It says that '1' and '0' has better portability, so I didn't wanted to just overwrite the value because it could break some other dialect. On the other hand, copying the entire method to the Psql dialiect just to change that, seams too much duplication.

Ideas?

Thanks!

**Comment by liukrimhrim** [comment]
> Hi there. I'm trying to write a record to a postgres table but it fails when tries to modify the table definition:
> 
> `[2019-12-04 20:25:30,590] WARN Amend failed, re-attempting (io.confluent.connect.jdbc.sink.DbStructure:170) org.postgresql.util.PSQLException: ERROR: column "active" is of type boolean but default expression is of type integer Hint: You will need to rewrite or cast the expression.`
> 
> The error is triggered by this modification:
> 
> `ADD "active" BOOLEAN DEFAULT 1,`
> 
> I've tried on psql 10 and 11 directly in the command line and in fact you cannot define a default value for boolean column using the number 1.
> 
> I've tracked the issue down to this line:
> 
> https://github.com/confluentinc/kafka-connect-jdbc/blob/237e4dcb88ace630fc5670520a4727216d3e568b/src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java#L1718
> 
> It says that '1' and '0' has better portability, so I didn't wanted to just overwrite the value because it could break some other dialect. On the other hand, copying the entire method to the Psql dialiect just to change that, seams too much duplication.
> 
> Ideas?
> 
> Thanks!

Hello! Thanks for reporting and diagnosing this bug. We believe your diagnosis is correct. We have reproduced the bug, created a bug fix ticket, and we are working on the ticket right now. 

To answer your question: 
In order to avoid duplication, we can just overwrite the logic for the boolean type case, and for the rest cases, just call super class method. An example code would be like: 
`
if (schemaName == null && Type.BOOLEAN.equals(type)) {
    builder.append((Boolean) value ? "TRUE" : "FALSE");
} else {
    super.formatColumnValue(builder, schemaName, schemaParameters, type, value);
}
`

**Comment by liukrimhrim** [comment]
The fix has been merged. It will appear in 5.0.4, 5.1.4, 5.2.4, 5.3.4 and 5.4.0 and later versions.
