### ISSUE TITLE
java.sql.SQLException: No suitable driver found for jdbc:mysql:

### ISSUE THREAD

**Issue by jslusher** [confluentinc/kafka-connect-jdbc#771]
I can't seem to get this JDBC connector to work. I'll try to give as much information as I can:

- My kafka cluster is hosted in a kubernetes cluster using the strimzi operator
- I'm using a distributed version of kafka-connect also using the strimzi containers
- I've been able to successfully configure a few debezium connectors that are streaming events into kafka topics
- The jdbc plugin is in the same directory as my other plugins, all of which seem to be recognized
- I see in the logs that the plugin is being loaded
- I want to connect a jdbc-mysql-sink to one of the topics to stream the events to a separate database on the other side
- I have verified that the mysql server is reachable from the kafka-connect pods
- I've verified the user and password information

My connector configuration:

```
{
  "name": "mytable-mysql-sink",
  "config": {
    "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
    "connection.password": "XXXXXxxxxxxxXXXXxxxxx",
    "tasks.max": "1",
    "topics": "my-topic",
    "transforms": "unwrap",
    "value.converter.schema.registry.url": "http://avro-registry.kafka:8081",
    "connection.user": "jdbc",
    "name": "my-mysql-sink",
    "auto.create": "true",
    "transforms.unwrap.type": "io.debezium.transforms.UnwrapFromEnvelope",
    "connection.url": "jdbc:mysql://mysql.my-namespace.svc.cluster.local:3306/mydb",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "insert.mode": "upsert",
    "pk.mode": "record_value",
    "key.converter": "io.confluent.connect.avro.AvroConverter",
    "key.converter.schema.registry.url": "http://avro-registry.kafka:8081",
    "pk.fields": "id"
  },
  "tasks": [
    {
      "connector": "my-mysql-sink",
      "task": 0
    }
  ],
  "type": "sink"
}
```

```
ls -l /opt/kafka/plugins/
...
Nov 12 23:57 confluentinc-kafka-connect-elasticsearch-5.3.1
Dec 20 00:23 confluentinc-kafka-connect-jdbc-5.3.2
Dec 20 00:41 debezium-connector-mysql
```

```
2020-01-10 22:24:21,960 INFO Loading plugin from: /opt/kafka/plugins/confluentinc-kafka-connect-jdbc-5.3.2 (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader) [main]
2020-01-10 22:24:22,728 INFO Registered loader: PluginClassLoader{pluginLocation=file:/opt/kafka/plugins/confluentinc-kafka-connect-jdbc-5.3.2/} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader) [main]
2020-01-10 22:24:22,728 INFO Added plugin 'io.confluent.connect.jdbc.JdbcSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader) [main]
2020-01-10 22:24:22,728 INFO Added plugin 'io.confluent.connect.jdbc.JdbcSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader) [main]
```

```
kx platform-connect-7d7f9474cb-qqrz6 -- nc mysql.my-namespace.svc.cluster.local 3306
M
5.7.28-31ns;0eUR.!�����Y%fLsr=jXDmysql_native_password
```

For some reason I have this in the status:

```
{
  "name": "my-mysql-sink",
  "connector": {
    "state": "RUNNING",
    "worker_id": "10.22.6.190:8083"
  },
  "tasks": [
    {
      "id": 0,
      "state": "FAILED",
      "worker_id": "10.22.6.190:8083",
      "trace": "org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: No suitable driver found for jdbc:mysql://mysql.my-namespace.svc.cluster.local:3306/mydb\n\tat io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:69)\n\tat io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:56)\n\tat io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)\n\t... 10 more\nCaused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://mysql.my-namespace.svc.cluster.local:3306/mydb\n\tat java.sql.DriverManager.getConnection(DriverManager.java:689)\n\tat java.sql.DriverManager.getConnection(DriverManager.java:208)\n\tat io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getConnection(GenericDatabaseDialect.java:217)\n\tat io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:88)\n\tat io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:62)\n\t... 13 more\n"
    }
  ],
  "type": "sink"
}
```

**Comment by jslusher** [comment]
Here are the logs from the KC pod of a failed start of the connector. It seems that the mysql connection isn't being made? https://gist.github.com/jslusher/fdb28209604cf47d57c47149779148c6

**Comment by gharris1727** [comment]
@jslusher Yes, if there's no suitable driver found, then the connector will never be able to open the connection at all.

You need to install a suitable MySQL JDBC 4.0 driver jar in the same directory as the kafka-connect-jdbc jar file, so that the connector can use that driver jar to connect.

**Comment by jslusher** [comment]
@gharris1727 Looking at the logs though, it seems like the driver I have installed is being found. It's a later version. Is there something you're seeing that indicates it needs to be an earlier version? Also, here is a snippet of DEBUG logs that shows an attempt at a connection that failed. Is that because of the driver version? https://gist.github.com/jslusher/57b8898bf2711c60b15a77a72916f923

**Comment by gharris1727** [comment]
@jslusher Dialect and Driver are two different resources. The Dialect is something connector-specific that lets it handle multiple different databases, and the Driver is a much more general piece of software. It looks like the dialect selection mechanism is working fine, but it's not finding the driver because of plugin path issues.

**Comment by jslusher** [comment]
Pardon me if I'm being dim, but are you saying that there are two separate drivers necessary? I have the connect driver `confluentinc-kafka-connect-jdbc-5.3.2` installed but I need a separate MySQL jdbc driver as well?

**Comment by gharris1727** [comment]
@jslusher That is correct, there there is one set of jar files for the connector (confluentinc-kafka-connect-jdbc-* and it's dependencies like common-utils and zookeeper) and a jar for each external database (postgresql, sqlite, jtds, etc).

Because of licensing/packaging reasons you have to download and install the MySQL jar separately, and it sounds like you've found the right download site. You should use the latest version, as that will most likely be compatible with your server's version.

**Comment by jslusher** [comment]
@gharris1727 I added the jar file of the latest mysql jdbc plugin and looking at the logs it seems to be loading: 

```
2020-01-14 17:51:44,761 INFO Loading plugin from: /opt/kafka/plugins/mysql-connector-java-8.0.19.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader) [main]
2020-01-14 17:51:45,012 INFO Registered loader: PluginClassLoader{pluginLocation=file:/opt/kafka/plugins/mysql-connector-java-8.0.19.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader) [main]
```

I still seem to be getting the same result however:

```
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://mysql.my-namespace.svc.cluster.local:3306/mydatabase
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getConnection(GenericDatabaseDialect.java:217)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:88)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:62)
	... 13 more
2020-01-14 17:57:04,653 ERROR WorkerSinkTask{id=my-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-my-sink-0]
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
```

```
ls -l /opt/kafka/plugins/
total 2308
drwxr-xr-x 6  501 games     110 Nov 12 23:57 confluentinc-kafka-connect-elasticsearch-5.3.1
drwxr-xr-x 6  501 games     139 Dec 20 00:23 confluentinc-kafka-connect-jdbc-5.3.2
drwxr-xr-x 2 root root     4096 Jan 14 01:07 debezium-connector-mysql
-rwxrwxr-x 2 root root  2356711 Jan 14 00:20 mysql-connector-java-8.0.19.jar
```

I don't see any complaints about the driver itself in the logs.

**Comment by gharris1727** [comment]
@jslusher 
> You need to install a suitable MySQL JDBC 4.0 driver jar in the same directory as the kafka-connect-jdbc jar file.

That jar file is not in the same directory as the jar file, it's too far up in the plugins tree. You should move it down into the confluentinc-kafka-connect-jdbc-5.3.2 directory.

**Comment by jslusher** [comment]
@gharris1727 After moving the jar file into the same directory as the connect jar file, It looks like I'm finally at least getting a connection. There's a `PK mode...` error, but I think that at least means the driver is working. Thank you for being so helpful!
