### ISSUE TITLE
JDBC SQL Server Sink fail when try sink wal2json message from Postgres to SQL Server

### ISSUE THREAD

**Issue by Yosafat1997** [confluentinc/kafka-connect-jdbc#798]
Hello i got similar problem , but now between postgres and sql server. For the connection, i use Debezium-powered connection and default config from kafka connect standalone.

connect-standalone connection:
into Kafka
```
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=true
value.converter.schemas.enable=false
```

postgresql source :                                          

```
name=dbz-test-connector
connector.class=io.debezium.connector.postgresql.PostgresConnector
tasks.max=1
plugin.name=wal2json
database.hostname=XXX.XXX.XXX.XX
database.port=5432
database.user=postgres
database.password=XXX
database.dbname = test
database.server.name=postgres
database.history.kafka.bootstrap.servers=127.0.0.1:9092
database.history.kafka.topic=user
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
```
and for sql server:

```
name=jdbc-sink
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
tasks.max=1
topics=postgres.public.user
connection.url=jdbc:sqlserver://XXX.XXX.XXX.XX:1433;databaseName=XXX;user=XX;password=XXXXXXXXXXXXXXX
transforms=unwrap
transforms.unwrap.type=io.debezium.transforms.UnwrapFromEnvelope
auto.create=true
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
insert.mode=upsert
pk.fields=id
pk.mode=record_value
table.name.format=XXX.dbo.XXX

```
with this config, i got java.lang.NullPointerException, but when i set all to true i got DataError that i need to provide schema.

**Comment by gharris1727** [comment]
@Yosafat1997

The JDBC connector requires schemas in order to work, so you'll need to enable schemas for both key and value on both connectors.

Can you also provide the stack trace of the NPE?

**Comment by Yosafat1997** [comment]
I'm sorry i afraid i can't provide the log. I'm not on my working computer right now, but with that configuration, it always bring me error. I don't want to give any schema due I use JSON as data source from wal2json and want to consume it directly to my SQL Server DB.

**Comment by gharris1727** [comment]
Since schemas are required, you'll need to find a way to generate the schemas before they get to the connector, either through an SMT on the source or sink, or changing the source plugin itself.

**Comment by Yosafat1997** [comment]
This is additional process that lead me to this error:
I left my connect_standalone.properties as same as same as default kafka properties. But I did this config to my source:
```
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
```
and this is the sink
```
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
```
And give me this error
```
    "org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:561)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: java.sql.BatchUpdateException: String or binary data would be truncated in table 'pm_datascience_playground.dbo.pj_user', column 'user_google'. Truncated value: '{\"user\": {\"id\": \"102057XXXXX\", \"name\": \"aaaa\", \"email\": \"asasa@gmail.com\", \"photo\"'.\n\n\tat io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:87)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)\n\t... 10 more\nCaused by: java.sql.SQLException: java.sql.BatchUpdateException: String or binary data would be truncated in table 'pm_datascience_playground.dbo.pj_user', column 'user_google'. Truncated value: '{\"user\": {\"id\": \"102057XXXXX\", \"name\": \"aaaa\", \"email\": \"asasa@gmail.com\", \"photo\"'.\n\n\t... 12 more\n"
```

when i set my source converter and my standalone.properties to True and sink to FALSE, it give me an error that I need to give an schema, but when i set my config like this it give me NullPointer error

**Comment by gharris1727** [comment]
> String or binary data would be truncated in table

This is probably due to the raw JSON string being too long to insert into whatever string datatype that the table has, and is indicative that the connector is not destructuring your data into columns properly.

**Comment by Yosafat1997** [comment]
I still doesn't have idea if I need to put a schema for my JSON. Is there any problem if I use a plug-in like wal2json to provide WAL translation into JSON then feed directly to my SQL Server? I have test SQLServer into SQLServer standalone workers without plugins and it's work. And i try to only use pure Kafka with Kafka Connect connector plus Debezium

**Comment by gharris1727** [comment]
I'm not familiar with the wal2json plugin, but if any stage in the process does not forward the schemas, then the schemas will not be available to the JDBC connector at the end of the pipeline. It's entirely possible for the wal2json plugin to produce JSON without any schema information, and  no combination of converter configurations will recover them.

**Comment by Yosafat1997** [comment]
My fault, after i convert my datatype to longer one, it works. Great thanks.
