### ISSUE TITLE
Link in README broken?

### ISSUE THREAD

**Issue by tedyoung** [confluentinc/kafka-connect-jdbc#8]
README links to https://github.com/confluentinc/copycat when it mentions *CopyCat*, but that repo(?) doesn't exist.

**Comment by ewencp** [comment]
@tedyoung All this code was based on my prototype which was housed at that URL before we submitted anything upstream to Kafka. The first Copycat patch landed in Kafka, so now this (and the copycat-hdfs repo) can be updated to be based on that. I'll be doing that very soon.

**Comment by ewencp** [comment]
Should be fixed as of #13
