### ISSUE TITLE
jdbc sink connector to postgres db error

### ISSUE THREAD

**Issue by danseo-reisys** [confluentinc/kafka-connect-jdbc#810]
we are trying out kafka with jdbc sink connector to stream data into a remote postgresSQL db. 

on our kafka, we run a producer with following schema definition example

--property value.schema='{"type":"record","name":"myrecord","fields":[{"name":"id","type":"int"},{"name":"product", "type": "string"}, {"name":"quantity", "type": "int"}, {"name":"price",
 "type": "float"}]}'

then we paste in following example into producer.
{"id": 999, "product": "foo", "quantity": 100, "price": 50}

But our jdbc sink connector shows following error.

Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask) [task-thread-jdbc-sink-femadex-data2-0]
--

can someone give me some pointer?  

thanks

**Comment by gharris1727** [comment]
@danseo-reisys That error is only the top of the stacktrace, and doesn't have any information about what has caused the error. Can you provide a complete stack trace?

**Comment by gharris1727** [comment]
@danseo-reisys I'm closing this issue as it has been inactive, feel free to re-open the issue once you have more diagnostic information.
