### ISSUE TITLE
kafka-connect-jdbc  sink doubt about topics.regex

### ISSUE THREAD

**Issue by winghuer520** [confluentinc/kafka-connect-jdbc#813]
as below picture , I use the topics.regex in sink connect json .
I want to know  how long  the connect will rescan the topic list and get the new topic if  I create .
And , if anyway to config the rescan period  ?

![微信图片_20200313163444](https://user-images.githubusercontent.com/47166389/76603874-b3fd6400-6548-11ea-8fcd-7788c0c9e933.png)

Thanks  for help.

**Comment by gharris1727** [comment]
This is not implemented by the JDBC connector, but instead the Connect Framework. The framework uses the Kafka Consumer API to [subscribe](https://kafka.apache.org/11/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#subscribe-java.util.regex.Pattern) to new topics, and the consumer is responsible for discovering new topics. I could not find additional documentation about any scan period, but i did find a configuration [metadata.max.age.ms](https://kafka.apache.org/documentation/#consumerconfigs) that might limit the staleness of the subscription, and pick up new topics more often. You can change this configuration for the consumer through the [worker configs](https://docs.confluent.io/current/connect/userguide.html#worker-override) or the [connector configs](https://docs.confluent.io/current/connect/userguide.html#per-connector-override).
