### ISSUE TITLE
I've made some changes in my fork to allow DB-specific query generation

### ISSUE THREAD

**Issue by slowenthal** [confluentinc/kafka-connect-jdbc#82]
Hi,

I made some revisions in a fork of this project off of 2.0.1 release to allow DB-specific SQL.  The current implementation of the timestamp/incrementing queries is very inefficient due to the OR clause with many optimizers.   In addition, there is no limit as how many rows may be returned.  The current implemenation uses auto-commit, which disables paging of rows.  Disabling autocommit is not desirable anyway as it can create excessive locking on the database.   I take advantage of paging predicates (timestamp, incr) > (?,?)  and the LIMIT clause.  

The original query is generated by the "generic" query generator.  I've created a postgres generator, which has uses paging predicates and a limit clause. Ostensibly that form should work on several different RDBMS's, as well with perhaps a few variants.

The head seems to have added a new lower bound to the timestamp which is unnecessary for the my new generator.   I removed the ability to automatically add a where clause to a custom query, and I would like to add a parameter which describes the bind variables.  Internally, the query generators work that way so queries may have any combination of timestamp, and incementing parameters.  We can all add the limit as a bind variable for some platforms, but is probably unnecessary, and if we want to add a lower_bound_timestamp as a parameter type we can too.

Should I submit a pull request, or do you want to peek at me repo first?

**Comment by ewencp** [comment]
@slowenthal Feel free to submit a PR and then we can iterate from there. We haven't gotten too much into database-specific code yet (and for obvious reasons we'd like to keep it to a minimum). I'm curious if any of the changes that made it into your Postgres-specific part could be pulled out and made generic? For example, you mentioned `LIMIT` clauses. We already limit the number of results returned per `poll()` call, but we could also apply that via a `LIMIT` clause for incremental queries (although you need to be pretty careful with this -- things like timestamp resolution between different databases starts to matter once you add the `LIMIT` clause as timestamps are not guaranteed to be unique).

Probably my biggest concern with adding anything database specific is testing and regressions. What was your strategy for testing these DB-specific queries?

**Comment by slowenthal** [comment]
I'll send the pull request.  I think it can be made relatively generic.  I need to connect to MSSQL, and I think the same code will work.  The key is to do SQL that give you stateless paging.

**Comment by bruce-szalwinski** [comment]
Did anything become of this?  The OR logic is killing my postgres db on a large table (300M records).

**Comment by wicknicks** [comment]
the JDBC connector now supports dialect specific queries. If this problem still exists in the latest version of the connector, we can re-open this ticket and add this feature to the specific dialects.
