### ISSUE TITLE
"delete.enabled":"true" not delete row, instead add __delete collumn

### ISSUE THREAD

**Issue by Yosafat1997** [confluentinc/kafka-connect-jdbc#840]
I have connectors with config like this:

```
{"name" :"sqlservercon_'$topic_name'",
	"config":{"connector.class":"io.confluent.connect.jdbc.JdbcSinkConnector",
			"topics":"'$table'",
			"connection.url":"",
			"connection.user":"",
			"connection.password":"",
			"transforms":"unwrap",
			"transforms.unwrap.type": "io.debezium.transforms.UnwrapFromEnvelope",
			"transforms.unwrap.drop.tombstones": "false",
			"transforms.unwrap.drop.deletes": "false",
			"auto.create":"true",
			"auto.evolve":"true",
			"insert.mode":"upsert",
			"pk.fields":" '$pk'",
			"pk.mode":"record_key",
			"delete.enabled":"true",
			"destination.table.format":"db.dbo.'$table'",
			"kafkaPartition": "0"

}}
```

For insert operation looks normal, but when using delete, it add new coll ```__delete``` and set it true. I want the row deleted from my tables instead add new collumn to flagged it deleted. How i handle it?

**Comment by alexpee** [comment]
> I have connectors with config like this:
> 
> ```
> {"name" :"sqlservercon_'$topic_name'",
> 	"config":{"connector.class":"io.confluent.connect.jdbc.JdbcSinkConnector",
> 			"topics":"'$table'",
> 			"connection.url":"",
> 			"connection.user":"",
> 			"connection.password":"",
> 			"transforms":"unwrap",
> 			"transforms.unwrap.type": "io.debezium.transforms.UnwrapFromEnvelope",
> 			"transforms.unwrap.drop.tombstones": "false",
> 			"transforms.unwrap.drop.deletes": "false",
> 			"auto.create":"true",
> 			"auto.evolve":"true",
> 			"insert.mode":"upsert",
> 			"pk.fields":" '$pk'",
> 			"pk.mode":"record_key",
> 			"delete.enabled":"true",
> 			"destination.table.format":"db.dbo.'$table'",
> 			"kafkaPartition": "0"
> 
> }}
> ```
> 
> For insert operation looks normal, but when using delete, it add new coll `__delete` and set it true. I want the row deleted from my tables instead add new collumn to flagged it deleted. How i handle it?

Hi @Yosafat1997 , how did you solve the delete in sink connector jdbc for SQL Server, I am having the same problem. Thank you.

**Comment by Patricklz** [comment]
Hi @alexpee you could solve this add the property in yout sink:

"fields.whitelist": "foo, bar, etc"

this property will just consider the fields there and don't will create the column.

**Comment by rahulchandawat22aug** [comment]
@Yosafat1997 I tried the config you are using and it is actually working. I am able to delete the records from target.

**Comment by jinijava** [comment]
> @Yosafat1997 I tried the config you are using and it is actually working. I am able to delete the records from target.
@rahulchandawat22aug 
hi can you please provide the configuration how you solved the above issue of @alexpee
