### ISSUE TITLE
JDBC Sink connector: fields.blacklist feature

### ISSUE THREAD

**Issue by Iskuskov** [confluentinc/kafka-connect-jdbc#845]
JDBC Sink connector has a very useful `fields.whitelist` feature, but often messages contain a huge number of fields, and if necessary to exclude only a few fields, it would be more convenient to just blacklist them. 

What do you think about it? Are there any plans to implement this?

**Comment by gharris1727** [comment]
I believe that you can get the same functionality with an SMT:
https://docs.confluent.io/current/connect/transforms/replacefield.html

**Comment by Iskuskov** [comment]
@gharris1727 thank you for reply! 

Typically, messages contain `schema` and `payload` fields at the top level.
And as I understand it, this SMT can replace just the top-level fields (similar [issue](https://stackoverflow.com/q/58641219/7109598)).

**Comment by gharris1727** [comment]
The `schema` and `payload` fields sound like you're using data that was serialized with a `JsonConverter` with schemas enabled. This only appears when the events are in the topic, and when the records are being read by another JsonConverter with schemas enabled, the fields inside `payload` become the top-level fields in the struct.

SMTs for sink connectors operate after the converter and before the connector, and will see only the fields in `payload`.

**Comment by Iskuskov** [comment]
Thank you for such detailed explanation!
ReplaceFiekd SMT is excatly what I was looking for.
