### ISSUE TITLE
`upsert` mode doesn't work when starting from non-existent table in postgres

### ISSUE THREAD

**Issue by aarondwi** [confluentinc/kafka-connect-jdbc#848]
Hi, I want to setup my connectors to use the `upsert` mode. The target db (postgres) is still empty, so I also set `auto.create` to true. But after setting the connectors, the table won't appear (If using mode `insert`, then the target table would appear)

config:
```
{
  "name": "jdbc_sink_pg",
  "config": {
    "dialect.name": "PostgreSqlDatabaseDialect",
    "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
    "connection.url": "jdbc:postgresql://postgres:5432/somedb",
    "connection.user": "someuser",
    "connection.password": "somepass",
    "topics": "topic_name",
    "poll.interval.ms": 5000,
    "insert.mode": "upsert",
    "auto.create": true,
    "auto.evolve": true,
    "task.max": 10
  }
}
```

Is this the expected behavior? or is this a bug?

**Comment by asthraa** [comment]
Did you check the status of the connector? Are the connectors running successfully?

**Comment by aarondwi** [comment]
@asthraa yes, I even tried to have the table first, running the connector, see data flowing in, then deletes the table, and after that it won't insert the next data (for those already inserted before, I know it is lost already)

**Comment by asthraa** [comment]
@aarondwi: Can you add these two properties in the sink connector configuration ?```"pk.mode": "record_value", "pk.fields": "id"```.

**Comment by aarondwi** [comment]
@asthraa adding `"pk.mode": "record_value"` and `"pk.fields":"id"` works. Any explanation why would it be? it is not documented [here](https://docs.confluent.io/current/connect/kafka-connect-jdbc/sink-connector/sink_config_options.html)

**Comment by aarondwi** [comment]
is it because without thouse fields, `kafka-connect-jdbc` doesn't know what to use in `INSERT .. ON CONFLICT (here?) DO ...`?

**Comment by asthraa** [comment]
You can use ```"pk.mode":"none"``` but it expects that configuration to be passed in sink configuration. I haven't looked further into this issue. May be someone from confluent team can answer

**Comment by rmoff** [comment]
You can't use `upsert` if you've not specified a key for the table. @asthraa is correct with their solution. You can also use `pk.mode=record_key` to use field(s) from the message key. Ref: https://docs.confluent.io/current/connect/kafka-connect-jdbc/sink-connector/sink_config_options.html#data-mapping
