### ISSUE TITLE
The document configuration for the JdbcSinkConfig is missing

### ISSUE THREAD

**Issue by shenzgang** [confluentinc/kafka-connect-jdbc#895]
The description for topics property is not found in the document, how do I map multiple Topic records to the specified table, and how do I use Topics? Where you can see the full configuration description or sample. I browse the document address is： https://docs.confluent.io/4.1.2/connect/connect-jdbc/docs/sink_config_options.html

**Comment by gharris1727** [comment]
This is a configuration from the framework, not from the JDBC sink in particular.
https://docs.confluent.io/current/installation/configuration/connect/sink-connect-configs.html
