### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by bruwozniak** [confluentinc/kafka-connect-jdbc#898]
@gharris1727 @rhauch @kkonstantine 
Hi, it seems like the maintainer activity on this repository ceased around the beginning of the second quarter this year. We have some issue that we opened PR for and it does not get any attention (as do many others). Is this still an official project of Confluent? Asking because if we can't count on the issues being fixed moving forward, we will need to consider migrating to alternatives.
Thanks!

**Comment by kkonstantine** [comment]
Hi @bruwozniak 
Thanks for your contributions and your interest in this connector. 

Indeed, the project is alive and actively maintained. In fact, starting with the upcoming release, this connector as well as the other community available Confluent connectors are being decoupled from the release pipeline of the overall Confluent Platform and they'll have their own independent release cadence for new releases moving forward. The work on this decoupling might have resulted in a slowdown of the reviews and approvals of new features, but I believe that with this new process fixes and features will actually get merged more frequently from here on. 

I'll try to help prioritizing some of the open PRs in the next few weeks. Let me know if there are specific PRs that block your adoption of this connector at the moment.

**Comment by bruwozniak** [comment]
@kkonstantine Thank you for quick response! That's great news. Since you asked, I can selfishly mention https://github.com/confluentinc/kafka-connect-jdbc/pull/887 - this is needed because of particular database dialect that we use, and we are forced right now to run our own fork of this repo (with related change in the dialect: https://github.com/smaspe/kafka-connect-jdbc-exasol/compare/master...smaspe:feature/sql_type_for_null_value).

**Comment by kbegrow** [comment]
I would like to add [#726 ](https://github.com/confluentinc/kafka-connect-jdbc/pull/726) as one of blockers not just for us. Would be really appreciated if this on could be reviewed and merged asap too.

**Comment by kkonstantine** [comment]
@kbegrow added the right team for review to the PR you mentioned above. 

The original fix mentioned on this ticket has been merged and `v10.0.0` of the connector has been released. This version is the first independent version and this will allow us to iterate faster. Closing, please leave any additional comments to PRs and new or existing open issues.
