### ISSUE TITLE
Data mismatch

### ISSUE THREAD

**Issue by kzharas210** [confluentinc/kafka-connect-jdbc#916]
Facing an issue of data mismatch. Value inside PostgreSQL is different than kafka message.

> Kafka -> kafka-connect-jdbc -> PostgreSQL

Here is my sink config:
	
    {
        "name": "test-sink",
        "config": {
            "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
            "tasks.max": "1",

            "connection.url": "jdbc:postgresql://localhost:5432/test_db?user=test&password=test",
            "dialect.name": "PostgreSqlDatabaseDialect",

            "topics.regex": "test.public.(.*)",

            "transforms": "dropPrefix, unwrap",
            "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
            "transforms.unwrap.drop.tombstones": "false",

            "transforms.dropPrefix.type": "org.apache.kafka.connect.transforms.RegexRouter",
            "transforms.dropPrefix.regex": "test.public.(.*)",
            "transforms.dropPrefix.replacement": "public.test_$1",

            "auto.create": "true",
            "auto.evolve": "true",
            "insert.mode": "upsert",
            "pk.fields": "id",
            "pk.mode": "record_key",
            "delete.enabled": "true",
            "batch.size": "1"
        }
    }

Message inside kafka topic:

    {
        "schema": {
            "type": "struct",
            "fields": [
                {
                    "type": "struct",
                    "fields": [
                        {
                            "type": "int64",
                            "optional": false,
                            "field": "id"
                        },
                        {
                            "type": "int64",
                            "optional": true,
                            "field": "test_c_id"
                        },
                        {
                            "type": "string",
                            "optional": true,
                            "field": "test_b_c"
                        },
                        {
                            "type": "string",
                            "optional": true,
                            "field": "test_a_t"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string",
                                "optional": true
                            },
                            "optional": true,
                            "field": "test_p"
                        },
                        {
                            "type": "int64",
                            "optional": true,
                            "field": "test_d_id"
                        }
                    ],
                    "optional": true,
                    "name": "test.public.test.Value",
                    "field": "before"
                },
                {
                    "type": "struct",
                    "fields": [
                        {
                            "type": "int64",
                            "optional": false,
                            "field": "id"
                        },
                        {
                            "type": "int64",
                            "optional": true,
                            "field": "test_c_id"
                        },
                        {
                            "type": "string",
                            "optional": true,
                            "field": "test_b_c"
                        },
                        {
                            "type": "string",
                            "optional": true,
                            "field": "test_a_t"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string",
                                "optional": true
                            },
                            "optional": true,
                            "field": "test_p"
                        },
                        {
                            "type": "int64",
                            "optional": true,
                            "field": "test_d_id"
                        }
                    ],
                    "optional": true,
                    "name": "test.public.test.Value",
                    "field": "after"
                },
                {
                    "type": "struct",
                    "fields": [
                        {
                            "type": "string",
                            "optional": false,
                            "field": "version"
                        },
                        {
                            "type": "string",
                            "optional": false,
                            "field": "connector"
                        },
                        {
                            "type": "string",
                            "optional": false,
                            "field": "name"
                        },
                        {
                            "type": "int64",
                            "optional": false,
                            "field": "ts_ms"
                        },
                        {
                            "type": "string",
                            "optional": true,
                            "name": "io.debezium.data.Enum",
                            "version": 1,
                            "parameters": {
                                "allowed": "true,last,false"
                            },
                            "default": "false",
                            "field": "snapshot"
                        },
                        {
                            "type": "string",
                            "optional": false,
                            "field": "db"
                        },
                        {
                            "type": "string",
                            "optional": false,
                            "field": "schema"
                        },
                        {
                            "type": "string",
                            "optional": false,
                            "field": "table"
                        },
                        {
                            "type": "int64",
                            "optional": true,
                            "field": "txId"
                        },
                        {
                            "type": "int64",
                            "optional": true,
                            "field": "lsn"
                        },
                        {
                            "type": "int64",
                            "optional": true,
                            "field": "xmin"
                        }
                    ],
                    "optional": false,
                    "name": "io.debezium.connector.postgresql.Source",
                    "field": "source"
                },
                {
                    "type": "string",
                    "optional": false,
                    "field": "op"
                },
                {
                    "type": "int64",
                    "optional": true,
                    "field": "ts_ms"
                },
                {
                    "type": "struct",
                    "fields": [
                        {
                            "type": "string",
                            "optional": false,
                            "field": "id"
                        },
                        {
                            "type": "int64",
                            "optional": false,
                            "field": "total_order"
                        },
                        {
                            "type": "int64",
                            "optional": false,
                            "field": "data_collection_order"
                        }
                    ],
                    "optional": true,
                    "field": "transaction"
                }
            ],
            "optional": false,
            "name": "test.public.test.Envelope"
        },
        "payload": {
            "before": null,
            "after": {
                "id": 4441,
                "test_c_id": 3606,
                "test_b_c": "QWERTY",
                "test_a_t": null,
                "test_p": [
                    "qwe",
                    "asd",
                    "zxc"
                ],
                "test_d_id": 22827
            },
            "source": {
                "version": "1.2.2.Final",
                "connector": "postgresql",
                "name": "test",
                "ts_ms": 1599543319277,
                "snapshot": "false",
                "db": "test",
                "schema": "public",
                "table": "test",
                "txId": 3914206,
                "lsn": 108940649328,
                "xmin": null
            },
            "op": "u",
            "ts_ms": 1599543319509,
            "transaction": null
        }
    }

For some reason values of `test_c_id` and `test_b_c` are different inside sink database
    
    Kafka                  Sink DB
    ---------------------------------------
    test_c_id: 3606        test_c_id: 22632
    test_b_c: QWERTY       test_b_c: null

**Comment by ncliang** [comment]
@kzharas210 , those look like entirely different records. Can you double check that other fields on the record, especially the id, are matching?

**Comment by kzharas210** [comment]
Seems like the issue was because of `RegexRouter`, after changing topic names everything works as expected.
