### ISSUE TITLE
Jdbc Sink for JSON with schema registry not supported ? 

### ISSUE THREAD

**Issue by Ycallaer** [confluentinc/kafka-connect-jdbc#922]
Hi all,
So I am running into a weird issue but after reading a lot of blogs I am not sure if my solution is supported.
We currently have a couple of IOT devices that are producing messages towards kafka (in proper json structure) and we use schema registry to track the schema.

I wanted to use kafka-connect-jdbc to read the JSON messages from kafka and dump them in postgresql but I keep getting the following error
`
Caused by: org.apache.kafka.connect.errors.DataException: Converting byte[] to Kafka Connect data failed due to serialization error: 
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:366)
	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$0(WorkerSinkTask.java:488)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
	... 13 more
Caused by: org.apache.kafka.common.errors.SerializationException: java.io.CharConversionException: Invalid UTF-32 character 0x2213136 (above 0x0010ffff) at char #1, byte #7)
`

I manually checked the data and there are no empty records, everything is valid.
This is a subset:
`
{"time":"1600695298.285","temperature":"21.525","debug":"7.444"}
{"time":"1600695299.285","temperature":"21.525","debug":"7.444"}
{"time":"1600695300.285","temperature":"21.513","debug":"7.442"}
`

This is my current configuration for the worker:

**_group.id=postgresql-worker
config.storage.topic=postgresql-worker-config-topic
offset.storage.topic=postgresql-worker-offset-topic
status.storage.topic=postgresql-worker-status-topic
bootstrap.servers=broker:9092
offset.storage.file.filename=/tmp/postgresql-sink.offsets
offset.flush.interval.ms=50000
offset.flush.timeout.ms=10000
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schema.registry.url=http://kafka-registry.local:8081
key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schema.registry.url=http://kafka-registry.local:8081_**

So my question, can I use schema registry with JSON or do I really need to make the schema part of the message ? (which makes schema registry kind of obsolete in my story).

**Comment by epheatt** [comment]
You can inject an internal JsonSchema with an envelope to the message using source AvroSchema in the registry in 3.x using a custom Converter used by a Sink worker. I am still on 3.3.2 and have a simple converter that does this in https://github.com/epheatt/kafka-connect-jsonavroschema if you are willing to author an Avro schema that matches the topic name. I will be upgrading to 5.x later this year and will simplify the extended converter now that null/default fields are handled properly by the Kafka JsonConverter.

**Comment by jay999123** [comment]
Hello,
@Ycallaer 
I believe you're using wrong type of converters. You've to use :

```
value.converter=io.confluent.connect.json.JsonSchemaConverter
value.converter.schema.registry.url=http://localhost:8081
```

**Comment by Ycallaer** [comment]
OK thanks for the feedback
