### ISSUE TITLE
JDBC Sink Connector Now Working

### ISSUE THREAD

**Issue by Surbhi27946** [confluentinc/kafka-connect-jdbc#946]
Hi,

I am using JDBC Sink connector and getting this error :

ERROR WorkerSinkTask{id=local-console-sink3-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. **Error: Sink connector 'local-console-sink3' is configured with 'delete.enabled=false' and 'pk.mode=none' and therefore requires records with a non-null Struct value and non-null Struct schema, but found record at (topic='test1-employee_source',partition=0,offset=0,timestamp=1603270492670) with a HashMap value and null value schema.** (org.apache.kafka.connect.runtime.WorkerSinkTask:566)
org.apache.kafka.connect.errors.ConnectException: Sink connector 'local-console-sink3' is configured with 'delete.enabled=false' and 'pk.mode=none' and therefore requires records with a non-null Struct value and non-null Struct schema, but found record at (topic='test1-employee_source',partition=0,offset=0,timestamp=1603270492670) with a HashMap value and null value schema.
	at io.confluent.connect.jdbc.sink.RecordValidator.lambda$requiresValue$2(RecordValidator.java:86)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:82)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:73)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:546)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:326)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

The sink properties is as follows:

name=local-console-sink3
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
tasks.max=1
topics=test1-employee_source
connection.url=jdbc:mysql://127.0.0.1:3306/test_db2
connection.user=root
connection.password=******
auto.create=true

And I am producing a new record in the topic as follows:
bin/kafka-console-producer.sh --broker-list 127.0.0.1:9092 --topic test1-employee_source  **--property value.schema='{"type":"record","name":"myrecord","fields":[{"name":"id","type":"int"},{"name":"product", "type": "string"}, {"name":"quantity", "type": "int"}, {"name":"price","type": "float"}]}'**
>{"id": 999, "product": "foo", "quantity": 100, "price": 50}

Can someone please suggest what is the issue?

**Comment by srikanth-sankurthi** [comment]
I am also getting the same error.

![image](https://user-images.githubusercontent.com/48278727/97355432-3009a980-1897-11eb-859a-656b9bc0ce9b.png)

**Comment by bjaggi** [comment]
IT only works with AVRO , but not with JSON. is that a limitation ?

**Comment by Surbhi27946** [comment]
For me also it worked only after adding AVRO schema in source properties as well as in sink properties.

**Source.properties :**

name=local-console-source6
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=1
topic.prefix=e_
connection.url=jdbc:mysql://127.0.0.1:3306/test_db
connection.user=user
connection.password=******
table.whitelist=employee_source
mode=incrementing

incrementing.column.name=id
value.converter.schema.registry.url=http://localhost:8081
key.converter.schema.registry.url=http://localhost:8081
**key.converter=io.confluent.connect.avro.AvroConverter
value.converter=io.confluent.connect.avro.AvroConverter**

**Sink.Properties:**

name=local-console-sink8
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
tasks.max=1
topics=e_employee_source
connection.url=jdbc:mysql://127.0.0.1:3306/test_db2
connection.user=root
connection.password=*****
auto.create=true

value.converter.schema.registry.url=http://localhost:8081
key.converter.schema.registry.url=http://localhost:8081
**key.converter=io.confluent.connect.avro.AvroConverter
value.converter=io.confluent.connect.avro.AvroConverter**

With JSON schema is it failing.
Why we can't use JSON schema?

**Comment by bjaggi** [comment]
it worked for me, use this post: https://rmoff.net/2020/01/22/kafka-connect-and-schemas/

also i wrote a custom java json producer...this should help 

        com.fasterxml.jackson.databind.JsonNode;
        properties.setProperty(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, JsonSerializer.class.getName());
        KafkaProducer<String, JsonNode> producer = new KafkaProducer<>(properties);

**Comment by shoaib1505** [comment]
hello guys,

I am having a question ?.

connector.class=io.confluent.connect.jdbc.JdbcSourceConnector

the above line is given by confluent but if we want to replace the above line with some other thing which is not related to confluent 

connector.class = localhost or any other ip or something which we can make this live in real world .
