### ISSUE TITLE
Big table in mysql cause java "heap space problem" 

### ISSUE THREAD

**Issue by shootingstar123** [confluentinc/kafka-connect-jdbc#956]
Well，I know we can change the run time memeroy setting to solve this problem. But in practice there won't be enough memory for a connector to use. Can we optimize the connector to read jdbc table incremently for the initial pass?For example, 1000w line in table A, connector source read 1w line per iteration, it will decrease the memeory usage significantly.

**Comment by gharris1727** [comment]
This should have been fixed as part of #34, can you provide some more details about what version and configuration you're using, and what error you're seeing?

**Comment by shootingstar123** [comment]
> This should have been fixed as part of #34, can you provide some more details about what version and configuration you're using, and what error you're seeing?

Hello, sorry for long wait, I replayed the issue and snapshot the runtime log for you just now. I am using confluent-6.0.0 local mode, mysql version is 5.7.32, batch.max.rows=100, connect-distributed jdbc jvm set '-xms256m -xmx4g'
![image](https://user-images.githubusercontent.com/13234004/98618639-97663580-233c-11eb-9621-e1d294d22b7b.png)

**Comment by gharris1727** [comment]
I believe that you'll need to set one additional configuration parameter to enable cursors in the mysql driver:
https://github.com/confluentinc/kafka-connect-jdbc/blob/72f1e0ab0ad466935f845922d3babd0f6a483cb0/src/test/java/io/confluent/connect/jdbc/source/integration/MySQLOOMIT.java#L34

**Comment by shootingstar123** [comment]
> I believe that you'll need to set one additional configuration parameter to enable cursors in the mysql driver:
> https://github.com/confluentinc/kafka-connect-jdbc/blob/72f1e0ab0ad466935f845922d3babd0f6a483cb0/src/test/java/io/confluent/connect/jdbc/source/integration/MySQLOOMIT.java#L34

Great, It works well after I set this property ! Thanks very much for your patient help! But this setting is not mentioned in confluent instructions and website blogs, it may be confused for newer directly using confluent I think.

**Comment by gharris1727** [comment]
I'm glad that it works for you now. We'll update the documentation to better describe this for the next person. Thanks!
