### ISSUE TITLE
Is there any way to set property[linger.ms] into JDBC Source Connector?

### ISSUE THREAD

**Issue by zer0fla9** [confluentinc/kafka-connect-jdbc#965]
Hi, all

I searched the linger.ms property to improve performance, but there is no linger.ms property in document.

Also I just tried to put the linger.ms property in the source connector config file and created it, but it didn't apply.(i.e: linger.ms = 0)

Is there any way for me to set this property into connector? 

Thanks for any help.

**Comment by gharris1727** [comment]
[`linger.ms`](https://docs.confluent.io/current/installation/configuration/producer-configs.html#linger.ms) is a producer configuration, so you'd have to specify it as a [producer override](https://docs.confluent.io/current/connect/references/allconfigs.html#override-the-worker-configuration). For example: `producer.override.linger.ms=0`, along with enabling overrides in your worker configuration.

**Comment by zer0fla9** [comment]
It works good for me. Thank you 👍
