### ISSUE TITLE
Add support for larger tinyint column values - mysql 

### ISSUE THREAD

**Issue by arunmenon** [confluentinc/kafka-connect-jdbc#98]
We have some tables in our legacy mysql schema which have  rows with tinyint column values greater than 127. I think the connector is converting TINYINT to java byte ranging from -127 to 127. 
https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/DataConverter.java#L291
Can their be a fix to address TINYINT column having larger values. 

According to the JDBC documentation
**The recommended Java mapping for the JDBC TINYINT type is as either a Java byte or a Java short. The 8-bit Java byte type represents a signed value from -128 to 127, so it may not always be appropriate for larger TINYINT values, whereas the 16-bit Java short will always be able to hold all TINYINT values.**

**Comment by ewencp** [comment]
@arunmenon That makes sense. I think supporting this isn't too hard, but needs to be put behind a config option for compatibility since it would result in a schema change.

**Comment by shikhar** [comment]
Contained by #165
